### ISSUE TITLE
Failed to install xdg-utils from Azure CLI

### ISSUE THREAD

**Issue by guestdj** [Azure/dev-spaces#100]
when I enter the following command on the Azure CLI to enable AZDS CLI I get the following error:

You may be prompted for your administrator password to authorize the installation process.
/tmp/tmp_ln81pca/azds-linux-setup.sh: line 88: sudo: command not found
[INFO]    Installing xdg-utils...
/tmp/tmp_ln81pca/azds-linux-setup.sh: line 29: sudo: command not found
[FATAL]   Failed to install xdg-utils.
Azure Dev Spaces CLI not installed properly. Visit 'https://aka.ms/get-azds' for Azure Dev Spaces.

**Comment by guestdj** [comment]
Also, I have enabled Dev Spaces in the Azure portal prior to trying the above command

**Comment by stepro** [comment]
In what kind of Linux environment are you trying to run the command? I think we may currently assume that you can always "sudo" on a Linux machine.

**Comment by guestdj** [comment]
I installed Azure Kubernetes Service through the Azure portal, not sure but I think it's a Windows machine, and the command is entered using the Portal Azure CLI bash terminal. Sorry if that's not enough info, I'm a bit of a newby at Kube.

**Comment by stepro** [comment]
Thanks, that's the information I needed. We don't currently support running the dev spaces command line from within the portal bash terminal (aka "cloud shell"). It should work if you try from another place (e.g. your machine) where you have the "az" command line tool installed.

**Comment by guestdj** [comment]
Thanks Stephan, that's a bit weird because this article (which I was following) suggests it's possible:
https://docs.microsoft.com/en-gb/azure/dev-spaces/troubleshooting
The the section Error 'Failed to create Azure Dev Spaces controller' specifies that you can delete the controller using the AZDS CLI
However I will try your suggestion by using this on my local

**Comment by stepro** [comment]
Sorry about that, the docs are a little unclear. I'll ask our doc writer to update this.
