### ISSUE TITLE
How do I attach persistent storage?

### ISSUE THREAD

**Issue by dazinator** [Azure/dev-spaces#106]
I have followed the dev-spaces quick start tutotirals, and spun up a simple "dev" space that has two services, one that makes a http request to the other.

However I now need them both to have access to some persistent file storage (shared between them).

How would I go about achieving that? Is this something I add to the azds.yaml file?

**Comment by stepro** [comment]
Dev spaces currently helps you with your code but not so much with external dependencies. To do that, you will need to modify the Helm chart that was produced by dev spaces to include the necessary objects and/or configuration to reference external storage. For example, you might create an Azure file share and mount that into both of your containers. See [here](https://docs.microsoft.com/en-us/azure/aks/azure-files-volume) for one example of how to do that.

**Comment by dazinator** [comment]
@stepro I followed that documentation already. However after creating the storage account and file share, the next step was to manually create a pod using kubectl specifying storage options in a local .yaml file. I rely on dev spaces controller to deploy the pod so I cant use that approach to attach storage because I'm not the one spinning up the pod. So.. what would you recommend?

**Comment by stepro** [comment]
This is where you want to modify the pod spec in the deployment template yaml in the Helm chart. You can start out by creating the secret separately and then referring to it using the spec in the Helm chart. Later, you might want to have the Helm chart create the secret using values that you pass in.

**Comment by dazinator** [comment]
Hmm slowly getting there.. 

I added the following to the bottom of the deployment template:

```
          volumeMounts:
            - name: azure
              mountPath: /mnt/azure
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: devbranch
          readOnly: false

```

However when I build I get this error:

> pods/hubplatformserver-6fd94d7bc7-xfbsr: FailedMount: MountVolume.SetUp failed for volume "azure" : Invalid default/azure-secret, couldn't extract azurestorageaccountname or azurestorageaccountkey

When I followed the docs linked earlier, I used kubectl to set this secret in my local environment, I am assuming that it won't exist however where the helm build actually takes place. Looking around I found that the template populates secrets from the values.yaml file `secrets` section. However these comments are in that section:

```
secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
```

Note: This values.yaml file contains all sorts of other things and it seems I would want to check it in to source control. How do I move the secrets out to another file that I wouldn't check in? And shoudn't your template be set up to do that by default?

**Comment by stepro** [comment]
Looks like you are close. When you ran `kubectl create secret`, it created the secret from the literal values you provided and stored it in the cluster, so it's not on your local machine. It seems there is something wrong about how the secret was created. Check `kubectl get secret azure-secret -o yaml` to make sure that the two data properties you specify exist. It will show the values as base64 encoded so don't worry if they look wrong.

Don't worry (yet) about the secrets section in the values.yaml file. I can tell you more about that after we get the basic scenario working with a pre-created secret.

**Comment by dazinator** [comment]
Thank you. Yup, deleting the secret with `kubectl delete secret azure-secret` and recreating it has solved that issue! It looks like the basic scenario is now working! :-)

**Comment by stepro** [comment]
Glad that's working now. If you want to explore having the Helm chart itself deploy the secret, and how dev spaces helps you with that, take a look at [this](https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/manage-secrets) article.

**Comment by dazinator** [comment]
Excellent, thanks I will.
