### ISSUE TITLE
 azds.yaml where is the documentation for this file?

### ISSUE THREAD

**Issue by dazinator** [Azure/dev-spaces#107]
I'm trying to figure out how I can attach my pod to persistent storage.
In my solution I have an `azds.yaml` file and I can hit f5 with dev spaces selected and see my app running.
I am familiar with docker and the DOCKERFILE.
However I am not familiar with `azds.yaml` or `helm` (completely new to me) - in fact kubernetes in general is new to me, but I have some docker swarm experience.
I have read this: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume which describes how to spin up a POD manually using `kubectl` directly, and a `yaml` file which has the spec for the POD including it's storage options. 
However as I rely on hitting F5 in VS to build my container and spin up my POD/s, I need to find the appropriate config file to amend so that I can supply POD storage options.
The `azds.yaml` file looks like it might be a promising candidate but I can't find any documentation that describes its format / this file. Is there anything you can point me at?
Thanks

**Comment by stepro** [comment]
The format for this file is described quite well [here](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works#how-running-your-code-is-configured), but this is not the right place to re-configure the `yaml` for your workloads, e.g. to add an Azure file volume. You should do that by modifying the Helm chart directly. The `azds.yaml` file exists to help configure how your code should run for development purposes only, while the Helm chart describes your workload as it is intended to be configured for production.

**Comment by dazinator** [comment]
@stepro thank you. Helm charts are new to me, but I have discovered the charts directory that the client side tooling has created for me. It looks like it's some sort of template system but I cant see any files in there relating to POD storage options. Are you able to point me on a sensible direction for example to extend what has been created by default to include pod storage options?

**Comment by stepro** [comment]
The place to look is in the templates/deployment.yaml file. In Kubernetes, pods are typically managed by a controller of some type, the most common being a deployment object. In the spec for that object you'll find a template for pods that the deployment object creates and manages. That's where you will want to be putting settings regarding volumes etc.

**Comment by dazinator** [comment]
Thanks that was what I was after, sorry for discussing this across two issues :-).
