### ISSUE TITLE
VSCode prelaunch task fails when trying to debug

### ISSUE THREAD

**Issue by timjroberts-inty** [Azure/dev-spaces#11]
Executing the command `azds up --keep-alive --await-exec --no-telemetry` (as part of debugging an application) produces the following error:

```
Could not locate an applicable session to keep ports and file synchronization alive.
If calling from a tool with built-in support for Azure Dev Spaces, restartthe tool.
```

What would be the reasons for this error? Running a normal `azds up` works fine.

**Comment by lisaguthrie** [comment]
Thanks for reporting this issue. Our dev team is looking into it.

**Comment by YuzorMa** [comment]
When you run with the '--keep-alive' flag, azds relies on a long-running background process to keep the ports and synchronization working.  This works from within Visual Studio or VS Code because those applications run the background task for you.

Are you running from within VSCode?  What scenario are you trying to achieve?

**Comment by timjroberts-inty** [comment]
Yes, I've run the Prepare Dev Spaces command from within VS Code, and I can see that it creates a `launch.json` and a `tasks.json` file. I can also see that the `tasks.json` file contains a pre-launch task to run `azds up` with the keep alive and await exec options. Is that the long running process you talk about? Or is there another process.

**Comment by YuzorMa** [comment]
There is another process that is launched automatically by the Dev Spaces VS Code extension.  The pre-launch task '--keep-alive' flag actually tells azds to use the background process as well.  If that background task is not running, then the whole thing fails - which is what you are seeing.

We have found a bug where the background process may be exiting early if no controller has been selected *before* launching VS Code.  We are working on a fix for that bug, but can you try the following workaround:

1. Close all VS Code instances
2. Use the az CLI to select a controller (az aks use-dev-spaces)
3. Launch VS Code again

**Comment by sushilraje** [comment]
I faced the exact same error. Also, I followed the steps as mentioned in the previous comment, but it doesn't work.

I also tried removing the --keep-alive flag, but doesn't help. Any ideas on what might be happening?

OS: mac

**Comment by YuzorMa** [comment]
@sushilraje What version of the AZDS CLI are you using?  Just in case it's related to the issue above, after you close all VS Code instances, can you make sure that there are no remaining azds processes running?  Then proceed with steps 2 and 3.

**Comment by sushilraje** [comment]
What version of the AZDS CLI are you using?
> I am running the azds with foll. version 0.1.20180919.5.

Just in case it's related to the issue above, after you close all VS Code instances, can you make sure that there are no remaining azds processes running? Then proceed with steps 2 and 3.
> Will give it a try and get back

**Comment by spboyer** [comment]
This is still an issue, just replicated using the .NET Core walk through. [Repair steps ](on Aug 2) do not fix this. Can we get some focus on this issue?

**Comment by philon-msft** [comment]
Apparently this can be caused by a bug in an older version of the AZDS CLI. @spboyer was able to fix the issue by running "az aks use-dev-spaces --update" to install the latest CLI.
