### ISSUE TITLE
Sync error in build output

### ISSUE THREAD

**Issue by dazinator** [Azure/dev-spaces#110]
Just did a build and noticed:

>  Uploading Hub.Platform.Shared\ValidateResponse.cs.
 Uploading Hub.Platform.sln.
File syncing failed with error 'The server closed the connection with the following error: Connection closed with an error. InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.'.
 Uploading Hub.Platform.Server\Dockerfile.develop.
Enabling debugging...
Using dev space 'default' with target 'MyAKS'
Release "azds-8e78f7-default-hubplatformserver" does not exist. Installing it now.
Error: release azds-8e78f7-default-hubplatformserver failed: object is being deleted: pods "mypod" already exists
Helm install failed with exit code '1': Release "azds-8e78f7-default-hubplatformserver" does not exist. Installing it now.

The sync error is the primary reason I opened this issue, but the "object is being deleted: pods" ~~messages don't look too clever either.~~ turns out to be related to a stray yaml file I placed in my helm chart - just including that message for completeness.

**Comment by xinyanmsft** [comment]
thanks for reporting this issue. can you confirm this happens sporadically when larger files are being changed? if this is the case, it seems we are hitting a buffer size limit at the transport layer. we should be able to fix it by applying a better batching logic adhere to the transport buffer size limit.

**Comment by YuzorMa** [comment]
We have deployed changes as @xinyanmsft described.  Closing this issue.
