### ISSUE TITLE
Access denied in azds CLI when different accounts have access to the same tenant.

### ISSUE THREAD

**Issue by lolodi** [Azure/dev-spaces#115]
There is a known issue the cause access denied error even when the logged in user has access to the subscription hosting the controller. 
When multiple user accounts have access to the same tenant that owns the controller's subscription, and one of the user doesn't have access to that subscription, the azds cli might erroneously pick the wrong user's credentials and then fail to get access to the resource. 
To work around this issue please delete the accessTokens.json file and then az login again with the user account that have access to the controller's subscription.
You can find the accessTokens.json in ~/.azure/ in MacOS or Linux and in C:\Users\<your_user>\.azure\ in Windows.

**Comment by YuzorMa** [comment]
This has been fixed.
