### ISSUE TITLE
Foreign characters in Method names makes the build crash

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#118]
I am not sure in what repo this bug belongs to so I'll start here

To reproduce:
1) Use Swedish Win 10 x64
1) Create a AKS cluster with dev spaces
2) Create a ASP.Net Core Web Project

Notice that all files generated by the template has the "Unicode (UTF-8 with signature) - Codepage 65001" encoding.

4) Add a new Razor Page

Notice that this file is now added with "Western European (Windows) - Codepage 1252" encoding.

5) In the .cs file of the new page add the following code:
```
    private void MyMäthod()
    {

    }
```

6) Start debug so DevSpace build container starts to build.

The build will now fail with the following error:
```
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
Pages/Index1.cshtml.cs(16,31): error CS1056: Unexpected character '�' [/src/WebK8/WebK8.csproj]
Pages/Index1.cshtml.cs(16,32): error CS1002: ; expected [/src/WebK8/WebK8.csproj]
Pages/Index1.cshtml.cs(16,57): error CS1519: Invalid token '�' in class, struct, or interface member declaration [/src/WebK8/WebK8.csproj]
Pages/Index1.cshtml.cs(16,57): error CS1056: Unexpected character '�' [/src/WebK8/WebK8.csproj]
Pages/Index1.cshtml.cs(16,62): error CS1519: Invalid token '�' in class, struct, or interface member declaration [/src/WebK8/WebK8.csproj]
Pages/Index1.cshtml.cs(16,62): error CS1056: Unexpected character '�' [/src/WebK8/WebK8.csproj]
Build FAILED.
```

However, adding the code above to any of the pages created by the template works fine.

It looks like the build container can only build files containing foreign characters, if the file is unicode encoded. If you build localy in VS it works in both cases.

**Comment by xinyanmsft** [comment]
thanks for reporting this issue. unfortunately this seems to be a limitation when building any Docker container. on your local machine, if you do 'docker build .' it should fail with the same error.

**Comment by xinyanmsft** [comment]
The problem is that Visual Studio is saving some C# files (such as Razor page) in a file encoding (Western Europe - Code Page 1252) that the .NET Core CLI tools (and .NET Core in general) cannot properly read.  Consequently, using Visual Studio to add non-ascii characters to such C# files causes compilation using dotnet on the CLI to fail. 

The proper way is to fix the Visual Studio template to use UTF8 instead. 

To workaround this issue, please manually change the file to use UTF-8 encoding, instead of code page 1252. I use notepad++ to do this myself.

**Comment by Eneuman** [comment]
Yeah I noticed this strange behavior aswell. Adding a new controller will add it with UTF8 encoding so foreign characters will work, but adding a razer page adds it with Western Europe -Code Page 1252 so the compilation works fine localy, but failes when compiling inside a Linux Docker Container as Azure Dev Spaces is doing.

@DamianEdwards Is this bug already posted somewhere or should this be moved to ASP.Net Core repo?

**Comment by xinyanmsft** [comment]
Link to https://github.com/Azure/dev-spaces/issues/118 as the cause of the issue.
