### ISSUE TITLE
Failed to pull image "azds/devhostagent:0.1.5" when trying to run a devspace (from VS)

### ISSUE THREAD

**Issue by eiximenis** [Azure/dev-spaces#12]
Hi.
I am trying to run one service deployment in DevSpaces. After building Dockerfile.Develop I see the following error:

```
Successfully built b515369330da
Built container image in 1m 49s
Waiting for container...
pods/catalogapi-69bc6c679-9ndw9: Failed: Failed to pull image "azds/devhostagent:0.1.5": rpc error: code = Unknown desc = Error response from daemon: manifest for azds/devhostagent:0.1.5 not found
pods/catalogapi-69bc6c679-9ndw9: Failed: Error: ErrImagePull
pods/catalogapi-69bc6c679-9ndw9: Failed: Error: ImagePullBackOff
```

I checked in dockerhub and this image (`azds/devhostagent`) do not have tag 0.1.5.

**Note**: Using the command line (`azds up`) deploys **succesfully** with no issues.

I am using:
* Azure CLI 2.0.42
* Devspaces extension: dev-spaces-preview (0.1.6)
* Azure Devspaces CLI 0.1.1918.5
* Visual Studio Tools for Kubernetes 0.20.20180725.1

**Comment by lisaguthrie** [comment]
Thanks for reporting this issue. Our dev team is looking into it.

**Comment by sanar-microsoft** [comment]
@eiximenis This issue should be resolved now, please try running the service again.
