### ISSUE TITLE
Calling service (in default dev space) with different dev space URL is not working

### ISSUE THREAD

**Issue by Vijay-Nirmal** [Azure/dev-spaces#121]
I have two services say service A and service B. Service A calls Service B. I have pushed this into AKS via Azure Dev Space. Both the service are in Default dev space. Now I can call service A http://default.servicea.1aa1aa.cus.azds.io/api/values which in turn call service B with http://default.serviceb.1aa1aa.cus.azds.io/api/values.

Now I have created new dev space (with *default* as the parent) to work on service B. Now I can call service B directly via http://newspace.default.serviceb.1aa1aa.cus.azds.io/api/values but I want to call service B from service A. Calling service A (this is in *default* dev space) via http://newspace.s.default.servicea.1aa1aa.cus.azds.io/api/values is not working.

Now how can I test my whole application?

![image](https://docs.microsoft.com/en-us/azure/dev-spaces/media/azure-dev-spaces/collaborate-graphic.gif)

As the above image suggests it is supposed to work, right?

**Original Post**
https://stackoverflow.com/questions/56648298/calling-service-b-from-service-a-with-server-bs-azure-dev-space-url

**Comment by stepro** [comment]
Did you include code in service A that propagates the `azds-route-as` header from the incoming request headers to the outgoing request you are making to service B?

**Comment by Vijay-Nirmal** [comment]
@stepro Yes, Problem is that I can even hit the service A

**Comment by stepro** [comment]
Looking carefully at your url, did you include the ".s." part of the domain after `newspace`?

http://newspace.s.default.servicea.1aa1aa.cus.azds.io/api/values

**Comment by Vijay-Nirmal** [comment]
Yes, here is my output

![image](https://user-images.githubusercontent.com/24755596/59894821-a8d53780-93ff-11e9-8abe-9f89832c9542.png)

![image](https://user-images.githubusercontent.com/24755596/59894852-c5716f80-93ff-11e9-8540-66cc4dd9a4ec.png)

**Comment by stepro** [comment]
Ok, this is an indication that the ingress objects in your cluster did not get configured correctly. What is the output of the following commands:

```
kubectl get ingress -n default
kubectl get ingress -n backend-work
```

**Comment by Vijay-Nirmal** [comment]
![image](https://user-images.githubusercontent.com/24755596/59991283-68c2be80-9664-11e9-92bc-e146f7751709.png)

**Comment by stepro** [comment]
As I thought, there is an ingress rule missing for `backend-work.s.default.maincontroller`. This indicates a problem on our side. Is your cluster in central US? I will work with the team to figure out what is wrong and get back to you.

**Comment by Vijay-Nirmal** [comment]
@stepro I think it is East US. Just to clarify, How there will be ingress for `maincontroller` in `backend-work` if I am only working on other services in that dev space?

**Comment by stepro** [comment]
Dev spaces runs an ingress manager that watches the ingress objects you define and creates derivative ingress objects based on the state of dev spaces in your cluster. In your case, you have a `default` dev space and a child `backend-work` dev space. With this configuration, if an ingress object is created in the `default` dev space that does not also existi in the `backend-work` dev space, a derivative ingress object is created in `default` that includes a rule for `backend-work.s.default.maincontroller` that maps to the same service as the original ingress. However, because the domain is prefixed with `backend-work.s.`, dev spaces identifies this and produces an `azds-route-as` header before it reaches your maincontroller code. When maincontroller calls to one of the backend services and propagates this header, it will redirect the call to the version of that backend service running in `backend-work`.

Probably more detail than you wanted, but that's what is supposed to be happening!

**Comment by Vijay-Nirmal** [comment]
@stepro Nice insights. This info is missing in [How Azure Dev Spaces works doc](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works#run-your-code).

So, Is the problem on your side? Any ETA if yes?

**Comment by stepro** [comment]
I'm looking into it now and will update shortly. I agree that information should be in the documentation; I'll ask our doc writer to make some updates.

**Comment by stepro** [comment]
Actually there's a section in that doc that talks about the ingress manager and how routing works: https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works#how-routing-works. Do you feel there is some additional context I provided above that is missing in the documentation?

**Comment by Vijay-Nirmal** [comment]
@stepro But in that doc, there is no info about "what happens in child dev space when it doesn't have ingress"

This part

> With this configuration, if an ingress object is created in the default dev space that does not also existi in the backend-work dev space, a derivative ingress object is created in default that includes a rule for backend-work.s.default.maincontroller that maps to the same service as the original ingress.

**Comment by stepro** [comment]
You are right, I was more specific on that than in the docs (it only says "The ingressmanager service monitors AKS clusters with dev spaces and augments the Azure Dev Spaces Ingress Controller in the cluster with Ingress objects for routing to application pods." which is pretty vague). I'll see if we can get another paragraph added to that section that talks more about precisely how the ingress manager augments the set of ingress objects. Thanks!

**Comment by stepro** [comment]
Ok, so I drilled in and you have found a bug that we fixed 10 days ago but will not be in production until next week. Your best workaround right now is to not have any ingress objects that do *not* specify a host as part of the ingress rule.

Right now, it looks like you have a `orm-manager` ingress object that does not specify a host name. If you either remove this ingress or specify a host on the ingress rule, the ingress manager should turn around and generate the necessary ingress object for your maincontroller service. You'll know that this worked when you see an additional ingress object named something like `maincontroller-dev-1234abcd`.

If neither of these options are possible for you, then you will need to wait until our fix has been pushed to production near the end of next week. Sorry for the inconvenience. If you are able to try the workaround I suggested and it doesn't work, please let me know.

**Comment by Vijay-Nirmal** [comment]
@stepro I will try the workaround. Thanks

**Comment by Vijay-Nirmal** [comment]
@stepro How to remove a particular service (`orm-manager`)? Commands?

**Comment by stepro** [comment]
The raw command you would need is `kubectl delete ingress orm-manager`, but I would advise against that. Instead, you'd want to look at how you installed `orm-manager` into your cluster and use the reverse of whatever that mechanism is to remove it along with all the related assets from the system. For instance, if you got that there through `azds up`, you'd want to `azds down` it. If you got it there using `helm install`, you'd want to `helm delete`. Etc.

If you want to try modifying the ingress object, you can run `kubectl edit ingress orm-manager` and add a `host` property to the ingress rule. That might be a safer and quicker thing to try first.

**Comment by Vijay-Nirmal** [comment]
@stepro I deleted that service, now it works. Thanks

**Comment by stepro** [comment]
Glad that solution worked for you!
