### ISSUE TITLE
Missing devspace buildnumber in K8 events

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#124]
Is this realy correct?
It looks like something should have been replaced here

![image](https://user-images.githubusercontent.com/12099277/60250533-1df4b100-98c7-11e9-82bc-a4f07f005daa.png)

**Comment by stepro** [comment]
I believe this is correct event output (it's the name of the init container, not the name of the image being used). Are you running into a specific issue that you think may be caused by something like this?

**Comment by Eneuman** [comment]
No, I though it just looked strange since { and } are often used as prefix and sufix for variables to be replaces by values, and It looks like k8 is using " " (space) as delimiter in the "Source" field before it.
I'll close this issue since this is by design :)
