### ISSUE TITLE
Document all $(...) values available in azds.yaml

### ISSUE THREAD

**Issue by skwasiborski** [Azure/dev-spaces#125]
Is there a list of $(...) place holders that are substituted in azds.yaml during `azds up`? I am specifically interested in getting the namespace that is used for the deployment.

In my setup I am explicitly assigning namespaces to my resources because my meta chart deploys to multiple namespaces thus I do not relay on the `--namespace` flag passed to `helm install`. This does not play well with azds and child spaces. I need to override the namespace from azds.yaml for the azds deployment to target appropriate namespace. Currently I am using `$(spacePrefix)`, `$(rootSpacePrefix)` and some helm gymnastics to get name of the space but it is quite ugly.

**Comment by stepro** [comment]
The two you mention are the only ones. This particular placeholder syntax has a single purpose - to allow a dev spaces user to get a public endpoint without needing to know and manually specify the host name to use in the ingress rule.

If you are looking for your code to have access to the namespace in which it was deployed, check out the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/).

**Comment by skwasiborski** [comment]
I am new to Helm, of course I can use `.Release.Namespace` to get the namespace to which the chart is being deployed which is what I was after.
