### ISSUE TITLE
Error deploying service when following the CI documentation

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#127]
I have been trying to deploy my microservice using the CI documentation found here: https://docs.microsoft.com/sv-se/azure/dev-spaces/how-to/setup-cicd

My build works fine and the container is pushed to ACR.
I can confirm that the tag and the acr file found in the image catalog looks fine.

When the release pipleline runs, it failes on the "helm upgrade" task with the following error:
`UPGRADE FAILED: timed out waiting for the condition`

Log:
```
2019-07-03T20:02:15.9357534Z ##[debug]execResult: {"code":1,"stdout":"[debug] Created tunnel using local port: '46661'\n\n[debug] SERVER: \"127.0.0.1:46661\"\n\n","stderr":"Error: UPGRADE FAILED: timed out waiting for the condition\n"}
2019-07-03T20:02:15.9361055Z ##[debug]task result: Failed
2019-07-03T20:02:15.9427648Z ##[error]Error: UPGRADE FAILED: timed out waiting for the condition

2019-07-03T20:02:15.9437188Z ##[debug]Processed: ##vso[task.issue type=error;]Error: UPGRADE FAILED: timed out waiting for the condition%0A
2019-07-03T20:02:15.9438069Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: UPGRADE FAILED: timed out waiting for the condition%0A
```

Doing a `kubectl get event -n dev` reveals this:
```
Error: ErrImageNeverPull
Container image "acrweeclinicdev.azurecr.io/klinikportalservice:1210" is not present with pull policy of Never
```

Looking at my ACR repository I can see that no image has been pulled but the image is there with the correct tag.

But I followed the topic "Grant AKS Access to ACR" on the docs https://docs.microsoft.com/sv-se/azure/container-registry/container-registry-auth-aks to the letter. And I can also confirm by looking at the role asignments in ACR that my AKS Service principal have AcrPull permissions.

Does the CI documentation asume that I use "Kubernetes Secrets"?
Any idea on what I can check next?

**Comment by sanar-microsoft** [comment]
@Eneuman Can you check the image pullPolicy defined in deployment.yaml for your project? If it says something like this {{ .Values.image.pullPolicy }} then you'll have to check the values.yaml file that is being used. 

The correct image pullPolicy should be 'IfNotPresent'. From the error it looks like the pullPolicy is set to 'Never'.

**Comment by Eneuman** [comment]
Hi

The deployment.yaml has it set to `{{ .Values.image.pullPolicy }}` and in the values.yaml it is set to
```
image:
  repository: integrationsmsservice
  tag: stable
  pullPolicy: IfNotPresent

```
It's realy strange.  
I can also see that the help  upgrade command, set the image.repository and image.tag correctly in the command line.

**Comment by sanar-microsoft** [comment]
Was this chart deployed using azds earlier? In that case azds.yaml file is used which has pullPolicy set to 'Never'.

In the helm upgrade command, can you also override image.pullPolicy to IfNotPresent?
image.pullPolicy=Never

**Comment by Eneuman** [comment]
Aaa, yeah, Im trying to deply to a namespace where I previously have deployed my service to using DevSpaces from VS. So maby thats what causing this issue.

Looking at this image, it looks like this should be working (DevSpaces is enabled in Dev namespace). 
 
![image](https://user-images.githubusercontent.com/12099277/60832714-dae6e780-a1bc-11e9-90b8-e2a7b85cc24c.png)

**Comment by sanar-microsoft** [comment]
I believe this image doesn't take into account doing helm upgrade and debugging on the same deployment. Because if you do CD and then use AZDS for VS for the same deployment, image pull policy will be overridden. I'll add a work item on the team to fix this. 
To unblock your CD scenario, setting image.pullPolicy in the helm upgrade step should hopefully solve this issue.

**Comment by Eneuman** [comment]
Awesome!
Thanks alot for helping me out!
