### ISSUE TITLE
Any chance to remove tiller when helm 3 is ready?

### ISSUE THREAD

**Issue by solacens** [Azure/dev-spaces#128]
helm 3 is in alpha stage and its quite a revolution that the tiller is finally gone!

Any chance that devspace will get upgraded to helm 3 after the official release of helm 3?

**Comment by sanar-microsoft** [comment]
@solacens There are plans to upgrade to Helm 3(or remove Tiller dependency) in the pipeline. Helm 3 isn't stable enough yet to test and make changes, once it is closer to a stable release we will upgrade.

**Comment by solacens** [comment]
Good to hear that. Looking forward to see its coming!

**Comment by solacens** [comment]
It's time. @sanar-microsoft

**Comment by sanar-microsoft** [comment]
@solacens Since Helm 3 is now public, we are working on it. Thanks for the patience.

**Comment by YuzorMa** [comment]
@solacens @jskulavik We will be rolling out preview support for Helm3 pretty soon.  If you're interested in being part of the preview, the details are included in #272 .

**Comment by YuzorMa** [comment]
Dev Spaces now uses Helm3 for all new controllers.

**Comment by Eneuman** [comment]
@YuzorMa Whats the easiest way to check if my controllers are using Helm3 or not?
If they are not, can I trigger a recreate of them?

**Comment by YuzorMa** [comment]
@eneuman The easiest difference to check for is by "up'ing" a service and checking if the release information for that service is stored in the “azds” namespace or the namespace where the service exists. Helm2 stores the release information in a configmap in the tiller namespace while for helm3 stores it in the namespace where the service is deployed and as a secret.

We are working on a plan to migrate existing controllers to use Helm3, but that will roll out slowly as there are some subtleties in migrating existing releases.  The manual way is to stop all "azds release", disable the controller and then re-enable the controller.
