### ISSUE TITLE
Dev Spaces and Kured does not seem to work well together

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#133]
I have a 2 node cluster with dev spaces and kured. Yesterday I received a mail telling me that I needed to reboot my nodes because of pathed linux kernel.
I’m using Kured to handle this as suggested by the AKS documentation.

This morning my app in the dev space cluster says, Service Unavailable.

Doing a Kubectl get nodes, reveals that a lot of my pods are down with status ErrImageNeverPull.

Any idea what’s going on here?

**Comment by sanar-microsoft** [comment]
@Eneuman Was any webhook pod in `azds` namespace running when these pods were re-scheduled? If it is running now, can you try deleting the pod so that they can be re-scheduled? Webhook will try to insert the init container that is responsible for generating the Docker image.

**Comment by Eneuman** [comment]
Hi
Yes, all services in azds namespace is running fine, and the webhook pod is also up and running.
About 1/2 of all my pods (roughly 12) was down with ErrImageNeverPull status.
After deleting them, they started up fine (rescheduled). 

Any Idea what can causes the pods to wrongly initialize when Kured reboots the nodes?

**Comment by sanar-microsoft** [comment]
My guess is either Kured took down both webhook pods or at least the pod that was serving the request for these pods, or after the reboot webhook pod reached a running state after these pods. So these pods were not instrumented. I'll add a bug on the team to handle this scenario.

**Comment by YuzorMa** [comment]
We've made a couple changes to handle Kured (or more accurately, recovering when the webhook goes down).  Please let us know if you see any more issues using Kured and Dev Spaces together.
