### ISSUE TITLE
Cannot install AZDS CLI.

### ISSUE THREAD

**Issue by robvet** [Azure/dev-spaces#140]
Want to present Dev Spaces to customer.

I can install DevSpaces from Visual Studio and it does work, but cannot install the command line tool onto the client.

Here are the errors I see: 

1) I attempt to install dev spaces tooling on client....

c:\,,,,,,,,,>az aks use-dev-spaces -g <rg> -n <cluster name>

Failed to list Azure Dev Spaces Controllers.
Please include the following Request ID when contacting support: 8f284224-faff-4d02-864c-8850c81bcf02

2) Then, I try removing the client side tooling, perhaps start over:

c:\.....>az aks remove-dev-spaces -g DevSpaceSandBox -n DevSpaceSandBox

Could not find Azure Dev Spaces Controller that targets resource 'DevSpaceSandBox' in resource group 'DevSpaceSandBox'.

3) Finally, I try to do an update:

c:\...>az aks use-dev-spaces -g DevSpaceSandBox -n DevSpaceSandBox

Installing Dev Spaces (Preview) commands...
A separate window will open to guide you through the installation process.
Azure Dev Spaces CLI not installed properly. Visit 'https://aka.ms/get-azds' for Azure Dev Spaces.

Have tried this on two different cluster with the same behavior. 

Any help would be greatly appreciated as customer has expressed interested dev spaces.

Thanks

**Comment by jikuma** [comment]
Hi @robvet can you try doing az aks use-dev-spaces with --upgrade flag. This will install the latest azds client for you.

**Comment by spaelling** [comment]
> 
> 
> Hi @robvet can you try doing az aks use-dev-spaces with --upgrade flag. This will install the latest azds client for you.

I am having somewhat the same issue. Already enabled DevSpaces from the portal. When running below nothing happens.

```bash
az aks use-dev-spaces -g rg-aks-dev -n aks-cl01-dev
Installing Dev Spaces (Preview) commands...
A separate window will open to guide you through the installation process.
```

and with the `--upgrade` flag

```bash
 az aks use-dev-spaces -g rg-aks-dev -n aks-cl01-dev --upgrade
az: error: unrecognized arguments: --upgrade
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {aks} ...
```

**Comment by YuzorMa** [comment]
@robvet Were you able to upgrade successfully with @jikuma's instructions?

**Comment by madan81k** [comment]
not able to install azds cli in win 7.

**Comment by YuzorMa** [comment]
The AZDS CLI is only supported on Windows 8 and above: https://docs.microsoft.com/en-us/azure/dev-spaces/about#supported-regions-and-configurations

**Comment by madan81k** [comment]
ok thank you. i thought i could play around dev spaces in my local machine, but turns out i might have to use vm.
