### ISSUE TITLE
AZDS debugging and API Gateway pattern (Ocelot)

### ISSUE THREAD

**Issue by aaronwjha** [Azure/dev-spaces#143]
I am currently working to setup an AZDS team development environment. The application uses the API Gateway pattern with Ocelot. Are there any known issues with debugging services in child spaces in this type of configuration? I am finding that API calls are not being routed properly when using child namespace URI's.

**Comment by garybond** [comment]
We came across a couple of issues when starting to use Ocelot with Kubernetes and DevSpaces.

1. When setting namespace in Ocelot config, just use the child namespace without the parent. So if you main namespace is “dev” and your child is “Aaron”, just use “Aaron”, not “dev/Aaron”.

2. If you are overriding the namespace in an `ocelot.Development.json` file, and that file is in your `.gitignore` and you try to unignore it in your `azds.yaml`, be aware of the following [issue](https://github.com/MicrosoftDocs/azure-docs/issues/35159)

**Comment by aaronwjha** [comment]
Thanks for the response, Gary. The only way I can get debugging to work is to run Ocelot in the child namespace along with the service I'm trying to debug. Did you find the same thing?

**Comment by garybond** [comment]
It depends on what your entry point is. If you’re running your backend service in VS using debug with DevSpaces, then hitting the public endpoint on your Ocelot deployed to parent namespace will get routed to the parent namespace backend, not your debugging instance in your child namespace. Can you not make a request directly to your backend service once it’s running in DevSpaces? If you HAVE to go via Ocelot, then it WILL need to also be running in DevSpaces from a VS debug session.

**Comment by aaronwjha** [comment]
Thanks again for the help.
