### ISSUE TITLE
Liveness and readiness probes not working

### ISSUE THREAD

**Issue by csnance** [Azure/dev-spaces#146]
Hello,

I am trying to test liveness and readiness probes inside an ASP.NET Core 2.2 application running in devspaces.
What I did:

1) Edit values.yaml to set probes.Enabled: true
2) Edit deployment.yaml with appropriate values for my applications 
 Microsoft.Extensions.Diagnostics.HealthChecks.IHealthCheck probes:
`{{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          {{- end }}`
3) Set breakpoints on my probes
4) Start debugging

What I expect:
Based on the probes being enabled, and the settings, I would expect my probes to be called by kubernetes and I should be able to debug those requests

What is happening:
The application starts and loads. I can debug requests made to Controllers. I can debug the health probe by doing a curl or browsing to the health endpoint (/live or /ready), but the probe is not being called by AKS. When I perform a kubectl describe on the deployment generated by azure devspaces I see the probes which have been defined for my application container. However, when I do a kubectl describe on the pod that is generated for the deployment the probes are not part of the container description.

Has anyone seen this or tried to hook up a liveness and readiness probe using IHealthChecks? I have tested doing a kubectl apply manually with a deployment and the liveness and readiness probe show up in both the description of the pod and the description of the deployment, and the probe works as expected.

**Comment by stepro** [comment]
What you are observing here is that when Dev Spaces runs a container for debugging, it automatically removes any probes. If it didn't, then any time you stop on a breakpoint, the application is hung and won't respond to any probes, causing Kubernetes to kill the pod.

Is there a scenario where you need to be able to live debug that the actual calls Kubernetes is making to probe the pod?

**Comment by csnance** [comment]
I suppose not, I am working on moving our application from local docker into AKS so I was running through the different aspects of the application. Thank you very much for the information and quick response!
