### ISSUE TITLE
Exception of type 'Microsoft.Mindaro.Client.ManagementClients.CommandExecuteException' when synchronizing files

### ISSUE THREAD

**Issue by eiximenis** [Azure/dev-spaces#15]
I am trying to do a deploy to a Devspaces using a helm chart located in another folder. I updated the  `azds.json` file with the correct location of the chart:

```
install:
  chart: ../../../../k8s/helm/catalog-api
```
It worked. Chart did not install because it need an additional values file located in the same folder, so I added a new entry in `install.values`:

```
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  - ../../../../k8s/helm/inf.yaml
```

After adding the command `azds up` fails with "CommandExecuteException":

```
Using dev space 'default' with target 'edu-devspaces3'
Synchronizing files...Exception of type 'Microsoft.Mindaro.Client.ManagementClients.CommandExecuteException' was thrown. 
```

I tried (with no success):

- Use windows backslash instead of unix slash
- Use the question mark at the end

Note that If I use an invalid path in the file:

```
- ../../../../invalid-folder/helm/inf.yaml
```

I receive the error `Synchronizing files...Required values file {0} not found.` (so it seems is processing the path)

**Comment by lisaguthrie** [comment]
Thanks for reporting this issue. Our dev team is looking into it.

**Comment by pragyamehta** [comment]
Hi! Gentle reminder! Would be great if you could share with us if this still repros for you and share the logs if possible.
