### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by benmed00** [Azure/dev-spaces#160]
- Issue Type: `Performance`
- Extension Name: `azds`
- Extension Version: `1.0.120190904`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mbenyakoub\azuredevspaces.azds-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by daniv-msft** [comment]
Thank you for reporting this issue.
In order for us to investigate, could you please attach the "azuredevspaces.azds-unresponsive.cpuprofile.txt" file generated by VS Code?
Also, do you remember doing anything specific with the extension when this happened?
Did this issue happen once, or every time you do a specific action?

**Comment by benmed00** [comment]
[azuredevspaces.azds-unresponsive.cpuprofile.txt](https://github.com/Azure/dev-spaces/files/3649879/azuredevspaces.azds-unresponsive.cpuprofile.txt)

**Comment by daniv-msft** [comment]
Thanks @benmed00. We're progressively converting synchronous file system operations to asynchronous ones, and it seems that the remaining ones contributed to the hang you experienced.
I'm fixing this, and I'll update this issues once the fix is ready.

**Comment by benmed00** [comment]
Thak you daniv-msft, you're awesome

**Comment by daniv-msft** [comment]
The fix to remove all synchronous file system operations has been checked-in, and will be part of the next release of the VS Code extension in 2-3 weeks.
@benmed00 > Please feel free to reopen this issue if you see any other hang after this fix is available.

**Comment by daniv-msft** [comment]
Reopening the issue, in case other users encounter the same problem. I'll close the issue once the version including this fix is released.

**Comment by YuzorMa** [comment]
This has been fixed in the latest release.
