### ISSUE TITLE
Exception when attempting to access Dev Space from VS2019

### ISSUE THREAD

**Issue by BillMincey** [Azure/dev-spaces#161]
Keep getting the error shown in the image when I try to connect my sample .NET Core Web App to a Dev Space. Enhanced log also attached.

![image](https://user-images.githubusercontent.com/55559567/65291644-30b70480-db09-11e9-93ab-85bc5d3e711c.png)
[azds-sdk-2019-09-20-00-00-02-18408.txt](https://github.com/Azure/dev-spaces/files/3633761/azds-sdk-2019-09-20-00-00-02-18408.txt)

cluster info
![image](https://user-images.githubusercontent.com/55559567/65291865-f863f600-db09-11e9-9130-5439b9ccf479.png)
![image](https://user-images.githubusercontent.com/55559567/65291910-2a755800-db0a-11e9-908b-941933e082aa.png)

**Comment by philon-msft** [comment]
Hi @BillMincey, it looks like you're running an older version of the Visual Studio Tools for Kubernetes extension. Could you try updating the extension?

**Comment by BillMincey** [comment]
Upgrading to the latest version of  VS2019 (16.2.5) seems to have done the trick.
