### ISSUE TITLE
azds up fails to bind port for .Net Core 3.0 Asp.Net Core service (bad gateway, err_empty_response)

### ISSUE THREAD

**Issue by danegsta** [Azure/dev-spaces#163]
Asp.Net Core 3.0 Dev Spaces services are attempting to bind the wrong port when launched with `azds up` (or the VS/VS Code extensions) due to a change in the mcr.microsoft.com/dotnet/core/sdk:3.0 Docker image (https://github.com/dotnet/dotnet-docker/pull/1322) which removed the ASPNETCORE_URLS environment variable from the base sdk image that Dev Spaces scaffolds in Dockerfile.develop for services targeting .Net Core 3.0.

If you're running into this issue, you'll see a network gateway error page when browsing to a publicly accessible service or an empty response error for a private service through the port forwarding address after running `azds up`. In addition, you should see the following error message in the `azds trace` output (or the debug logs in the VS/VS Code extensions): `Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.`

**Comment by danegsta** [comment]
To workaround the issue, add the following line below the other `ENV` declarations at the top of the Dockerfile.develop file for the impacted project: `ENV ASPNETCORE_URLS=http://+:80`

Dockerfile.develop before:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80
...
```

Dockerfile.develop after:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
...
```

**Comment by dariuszbz** [comment]
so it's the line: ENV ASPNETCORE_URLS=http://+:80
thank you ... one day lost but finally, make it work.
