### ISSUE TITLE
Dev Spaces CLI installer has multiple issues

### ISSUE THREAD

**Issue by rcarmo** [Azure/dev-spaces#17]
I would like to install the Dev Spaces tools inside my home directory on my Mac instead of modifying system paths (for a number of reasons). At first I saw no reason for the installer to use `sudo` to install in `/usr/local/lib` AND polluting my home directory with `~/lib`, which is inconsistent (and feels like a cop-out).

I eventually inspected `azds-osx-setup.sh` and modified it to a working configuration, but it has a number of problems:

* It downloads files directly to `$HOME` without using an isolated temporary folder
* It runs `curl` with `sudo` multiple times, which may be construed as a security risk (and was blocked by default by my Little Snitch ruleset).
* It also runs `unzip` with `sudo` without verifying any sort of signature on the ZIP file.
* It runs `sudo rm -rf` on temporary files (inside `$HOME`!) without extensive checks (other than `-w`), even for deleting single files.

My suggestion is that besides fixing the above to be safer in all regards, the Mac script be changed to use `~/Library/Azure/bin` (and `lib`) by default and that the user is directed to modifying `$PATH` by providing two sample lines to add to `.bashrc` at the end of the install - one for modifying `$PATH` and another for setting up `bash` completion.

**Comment by rcarmo** [comment]
My sanitised version of the script is at https://gist.github.com/rcarmo/64e133abe9254f3ecdc5a6efa3e8c58b - it's a hack job, but works for me.

I also noticed this adds another version of `kubectl` for some reason...

**Comment by rcarmo** [comment]
A further issue. If you're using `pyenv`, this section of the script incorrectly parses `az`'s location and spectacularly misplaces `azds`:

```bash
# Setup AZDS CLI
if [ ! -z $(which az) ]; then
    AZDS_BIN=$(dirname $(which az))/azds
fi
```

**Comment by lisaguthrie** [comment]
Thanks for the feedback. Our dev team is looking into this.

**Comment by YuzorMa** [comment]
These issues should be addressed in the latest version of the Mac install script.
