### ISSUE TITLE
Support for external helm repositories

### ISSUE THREAD

**Issue by mprigge** [Azure/dev-spaces#19]
I'm fairly new to dev spaces, so I may be missing something very fundamental here. I cannot seem to figure out a way to support helm dependencies (requirements.yaml) together with azds. Relative references do not seem to work nor can I determine how to add a repository that the azds version of helm can see (I am prompted to execute `helm repo add` despite the fact that my local helm already has the referenced repository).

What is the the preferred approach to deployments that have external dependencies that aren't in the `stable` helm repo? Additionally, is there a document that describes the full schema for azds.yaml?

**Comment by stepro** [comment]
Support for Helm charts with dependencies is on our backlog for a future release. I can't say we have thought much about external dependencies that aren't in the `stable` helm repo, however our general principal on these things is that however it works locally, it should work the same way with azds.

We do not currently have a document describing the full schema for azds.yaml. For now, feel free to ask if something is supported and we'll let you know if there is a way to configure azds.yaml.

**Comment by mprigge** [comment]
Okay, understood. I'll look forward to that support.

Pardon the dumb question, but when azds is actually executing helm during a deploy, where is that actually happening? I know there's a Tiller instance inside the azds namespace which I assume it's speaking to. Is Helm actually running on the development workstation or is that living in a container or somewhere entirely different?  Just trying to sort out whether I can throw an add repo command or modify the `repositories.yaml` wherever that's occurring (even if it's not precisely supported).

**Comment by stepro** [comment]
No dumb questions here :) Azds removes the need to have docker, kubectl, helm installed on your local machine. To achieve that, it copies (or specifically, incrementally synchronizes) your code and your Helm chart to a remote location (an Azure file share) from which the helm install command is issued.

Given this, you could mount the Azure file share somewhere and try to run commands directly on it, but it would be very hard to do this at the appropriate time (the next sync will delete anything that got added, and the helm install is run almost immediately after the sync is complete).

**Comment by mprigge** [comment]
Got it. I had assumed some degree of smoke and mirrors was involved. Worth asking, though! I'm guessing that in order to support this use case, you'd probably need to add a repos node to the azds.yaml to drive helm repos add commands. So, it'd need to be worth doing for you. I'm not sure how many other people have this requirement, so I've no idea how likely that'd be. 

I suppose this may be a sign that I should find a different way of accomplishing what I'm trying to do. On the one hand, being forced to do that by development tooling feels bad, but on the other it's maybe a sign I'm doing something the hard way. :-)

In any event, do you already have an issue tracking this backlog item I can watch for?

**Comment by stepro** [comment]
We maintain our backlog internally, but you can treat this issue as the external work item tracking it.

**Comment by walterfranssen** [comment]
Is there a workaround  for it, i reaaaalllly need it

**Comment by chrisjohnson** [comment]
With dev spaces out of preview, what is the solution to this problem? What is the `azds` command for calling `helm repo add`?

**Comment by sanar-microsoft** [comment]
@walterfranssen @chrisjohnson Because the repo information is not available to the helm client that `azds` uses right now, one way is to add a charts sub-directory and [adding the dependencies there manually](https://helm.sh/docs/developing_charts/#managing-dependencies-manually-via-the-charts-directory) or you can do a `helm repo add` and `helm dep update` manually for the chart and once the dependencies are updated you can remove them from requirements.yaml before doing `azds up`. Does that work?

**Comment by YuzorMa** [comment]
@mprigge @walterfranssen @chrisjohnson This is now supported!

Check out the docs at https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/use-private-helm-repo to see how to use it.

Please let us know if you see any issues or have any feedback.
