### ISSUE TITLE
Preview signup link broken

### ISSUE THREAD

**Issue by devonbarrett** [Azure/dev-spaces#2]
The first link in the readme leads to a broken hubspot page:

https://aka.ms/signup-azds -> http://landinghub.visualstudio.com/devspaces

>Expired Account
>The HubSpot account associated with the domain "landinghub.visualstudio.com" has expired.

**Comment by philon-msft** [comment]
@devonbarrett, thanks for reporting this! Should be fixed now.

**Comment by bremnes** [comment]
@philon-msft, you might want to update [the landing page](https://visualstudio.microsoft.com/azure-dev-spaces/) as well:
> _Public Preview Coming Soon!_

Related announcement:
https://blogs.msdn.microsoft.com/visualstudio/2018/07/09/announcing-the-public-preview-of-azure-dev-spaces/
