### ISSUE TITLE
Multiple subscription issue

### ISSUE THREAD

**Issue by AceHack** [Azure/dev-spaces#20]
I have multiple subscriptions some of which I am admin and some of which I am not, Dev Spaces is giving me the error "The current user is not authorized to register the 'Microsoft.DevSpaces' resource provider for subscription 'xxx'.  Make sure that the current user has Owner or Contributor access to the subscription"

This is not the subscription I want it to use but there seems no way to change it.

**Comment by lisaguthrie** [comment]
@AceHack - we just pushed an updated version of the VS extension that should fix this issue. VS should auto-update your version, or you can download from here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vs-tools-for-kubernetes

Let me know if you're still having issues with the updated extension. Thanks for your patience!
