### ISSUE TITLE
azds up started to fail

### ISSUE THREAD

**Issue by mllab-nl** [Azure/dev-spaces#202]
We have an issue with ''azds up" ATM. It started taking too long and fails in the end

Using dev space 'alexander' with target 'legalmoldaks-dev'
Synchronizing files...<1s
Installing Helm chart..**.3m 20s**
Waiting for container image build...6s
Building container image...
Step 1/24 : ARG SDK_IMAGE_TAG=3.0.100
Step 2/24 : ARG CLIENTAPP_IMAGE_TAG=0.1.0-linux
Step 3/24 : FROM mcr.microsoft.com/dotnet/core/sdk:${SDK_IMAGE_TAG} as base
Step 4/24 : FROM node:12.13-buster-slim as client-build
Step 5/24 : COPY ClientApp/package*.json /clientApp/
Step 6/24 : WORKDIR /clientApp
Step 7/24 : RUN npm install --no-audit
Step 8/24 : COPY ClientApp /clientApp/
Step 9/24 : RUN npm run ng build --outputPath=dist/
Step 10/24 : FROM mcr.microsoft.com/dotnet/core/sdk:${SDK_IMAGE_TAG}
Step 11/24 : ARG BUILD_CONFIGURATION=Debug
Step 12/24 : ENV ASPNETCORE_ENVIRONMENT=Development
Step 13/24 : ENV DOTNET_USE_POLLING_FILE_WATCHER=true
Step 14/24 : ENV ASPNETCORE_URLS="http://+:80"
Step 15/24 : EXPOSE 80
Step 16/24 : EXPOSE 443
Step 17/24 : WORKDIR /src/mold.web
Step 18/24 : COPY ["mold.web.csproj", "."]
Step 19/24 : RUN dotnet restore "mold.web.csproj"
Step 20/24 : COPY . .
Step 21/24 : RUN dotnet build --no-restore "mold.web.csproj" -c Debug
Step 22/24 : RUN echo "exec dotnet run --no-build --no-launch-profile -c Debug --" > /entrypoint.sh
Step 23/24 : COPY --from=client-build /clientApp/dist ClientApp/dist
Step 24/24 : ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
Built container image in 2s
Waiting for container...**3m 22s**
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at 'C:\Users\Alexander\AppData\Local\Temp\Azure Dev Spaces'.
Please include the following Request ID when contacting support: 7e1faafc-9fbc-4c1a-b650-fbe9435d6ee0

The Dev namespace is completely epmty
P.S: While digging into it we see that files at "C:\Users\...\AppData\Local\Temp\Azure Dev Spaces" are exclusively locked when azds up is still running.
It makes it more complicated to find the root cause of our problem.

IMHO there is no reason to exclusively lock a log file.

**Comment by mllab-nl** [comment]
This is what helped us:
1. Disabling Dev Space on AKS cluster
2. Cleanup of all namespaces in AKS 
3. Re-enabling Dev Spaces on AKS cluster

**Comment by lolodi** [comment]
Thanks for reporting this. I'm glad you got unlocked.
I'll make sure that both issues: log files locked and bad state after failing to pull images, get investigated. I'll let you know once we have the fixes ready.

**Comment by sanar-microsoft** [comment]
@mllab-nl Did you upgrade the Tiller image in `azds` namespace? 
Dev Spaces relies on `2.14.3` version and looks like the Tiller version was upgraded to `2.15.1`. This was leading to a version mismatch in our service and we should've handled it better considering both versions are compatible.
Re-enabling Dev Spaces recreated the Tiller `2.14.3` pod and everything started working again.
