### ISSUE TITLE
Generated Dockerfile will not work for containers not running on port 80

### ISSUE THREAD

**Issue by bdelsaz** [Azure/dev-spaces#209]
**System info**
```
Azure Dev Spaces CLI v. 1.0.20191025.15
Azure CLI v. 2.0.75
dev-spaces Extension v. 1.0.3
```

**Background info**
I am trying out Dev Spaces for an existing AKS cluster, with existing .net applications. These applications run in a port different to port 80. We already have docker files.
I am debugging with both visual studio and visual studio code. As stated in the docs, when debugging, both VS and VSCode call `azds prep` and `azds up`. 

**Expected behavior**
The container created by Dockerfile.develop (creatd by azds)  exposes port 5000, as stated on our existing dockerfile.

**Actual behavior**
Azds does not set the environment `ASPNETCORE_URLS` to port 5000, even thought the port 5000 is exposed. This is the output of the created Dockerifle.develop:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 5000
```
On the output window I see that the service exposes port 80:
```
Now listening on: http://[::]:80
```

Result: the connection cannot be made. Kubernetes port-forwards the pod to listen to port 80, which of course is not working.

I don't see anywhere in the docs how to configure this. I would however expect azds to be smart enough to pick up this from my existing dockerfile / application?

**Comment by lolodi** [comment]
Thanks for reporting this. 
We'll start investigating and I'll keep you posted.

**Comment by YuzorMa** [comment]
HI @bdelsaz In earlier versions of Dev Spaces, we did not set the ASPNETCORE_URLS environment variable as it was set by the base docker image.  Recent updates to the dotnetcore Docker image removed that environment variables so it now needs to be explicitly set in Dockerfile.develop.  We have updated the tools to generate Dockerfile.develop with the environment variable set.

The manual workaround is explained in #163 or you can delete your Dockerfile.develop and re-run prep to generate a new one.

**Comment by bdelsaz** [comment]
Thank you!!  Will recheck and close this issue.
