### ISSUE TITLE
Documentation: can you specify in azds.yaml what docker target to use?

### ISSUE THREAD

**Issue by mllab-nl** [Azure/dev-spaces#211]
We are using multi-stage Docker builds and would like to use single dockerfile for azds as well.

Can you specify in azds.yaml what docker target to use? 

Specifying "target" as mentioned in https://docs.docker.com/compose/compose-file/
 did not worked.

kind: helm-release
apiVersion: 1.1
build:
  context: ..\..
  dockerfile: ..\..\Dockerfile.develop
  **target: dev-app1**
  useGitIgnore: true
....

**Comment by lolodi** [comment]
Unfortunately as of today we don't support a Target parameter in the azds.yaml.
I created a work item to track this and I'll keep you posted on the progress.
In the mean time you will have to use the Dockerfile.develop as a workaround.

**Comment by mllab-nl** [comment]
Thank you @lolodi  !
Any rough ETA - week, month ?

**Comment by lolodi** [comment]
We have still to get a full estimate of the work to be done, but I'd expect in the ~month range. Can't be more precise right now.
