### ISSUE TITLE
Helm v3 Support

### ISSUE THREAD

**Issue by pheuter** [Azure/dev-spaces#219]
Now that it is [officially out](https://github.com/helm/helm/releases/tag/v3.0.0), would be great for `azds` to support it.

**Comment by philon-msft** [comment]
Agreed! We're looking into adding Helm 3 support now.

**Comment by ShrutiPPathak** [comment]
We will be rolling out preview support for Helm3 pretty soon. If you're interested in being part of the preview, the details are included in #272 .
