### ISSUE TITLE
Non-web apps

### ISSUE THREAD

**Issue by cocowalla** [Azure/dev-spaces#22]
Does Dev Spaces support the development of non-web apps, such as background processing daemons/services?

**Comment by cocowalla** [comment]
Yes, I was specifically thinking about services that use Azure Storage Queues. Is there tooling built-in to Visual Studio and/or VS Code for seamlessly deploying .NET console apps to Dev Spaces, so you get a similar experience to working with web apps?

**Comment by stepro** [comment]
@mthalman-msft, does the VS extension for Dev Spaces allow you to select Dev Spaces as a target for apps other than web apps? The VS Code extension would work for any kind of .NET app, so long as it's long running, e.g. waiting on a queue.

**Comment by mthalman-msft** [comment]
Not currently, no.  In VS, it's just ASP.NET Core projects that are supported.

**Comment by jessebarocio** [comment]
I just tried this in VS today before I found this issue. Hopefully selecting Dev Spaces as a target for non-ASP.NET Core projects is available soon.

**Comment by darkmyst** [comment]
Is there any word regarding eventing or queue support?

**Comment by jonhoare** [comment]
Is there any update on this? At the moment, VS2019 and VSCode can only add Dev Spaces to Asp.Net Core Applications. 

I would very much like to make use of Azure Dev Spaces within our Team, however our system doesn't just comprise of Web Applications. We are also running .Net Core Console Applications, with Akka.Net that communicate internally using DNS and TCP Ports. If there was a way to be able to develop these console applications in Visual Studio and to then run them up in Dev Spaces, we would be able to make the switch over.

**Comment by YuzorMa** [comment]
@jonhoare @cocowalla We are working on support for adding Dev Spaces to .Net Core Console Application and it will be coming in an upcoming Visual Studio update.  I'll post back here once it's available.

**Comment by YuzorMa** [comment]
@jonhoare @cocowalla This is now available with the latest Visual Studio Preview (VS 16 Preview 5).  Please try it out and let us know if you have any feedback.
