### ISSUE TITLE
Samples need to be updated to support Helm 3

### ISSUE THREAD

**Issue by JimBlizzard** [Azure/dev-spaces#222]
Now that Helm 3 is GA, the sample apps need to be updated, such as: https://github.com/Azure/dev-spaces/tree/master/samples/BikeSharingApp. The instructions and charts, etc, do not work with Helm 3.

**Comment by philon-msft** [comment]
Dev Spaces does not yet support Helm 3, but when we do we'll be sure to update documentation and samples.
