### ISSUE TITLE
How to specify config maps and secrets objects in the azds.yaml file

### ISSUE THREAD

**Issue by abhall724** [Azure/dev-spaces#227]
Is there a way to configure the named resources to use for the deployment, such as configmaps and secrets in the namespace already? Furthermore, how can we specify additional initcontainers without interfering with the default init containers already provided?

**Comment by rakeshvanga** [comment]
@abhall724 You can update the deployment.yaml file present in the charts folder. You can add the names of the configmaps/secrets you want to use in the deployment file. 
If you want different values for your environment, you can even add values.dev.yaml file to customize the deployment.

Regarding init containers: Yes, you can update the deployment.yaml file to add additional init containers that are required for your use.

**Comment by abhall724** [comment]
To further elaborate, we can safely modify all the yaml files in the charts directory without affecting the deployments for Visual Studio.

**Comment by rakeshvanga** [comment]
Yes, you can modify all the yaml files inside the charts folder. If there are any issues in the modified charts folder you would see errors while debugging the the project.
