### ISSUE TITLE
Publish fails if one of multiple subscription cannot register the Azure DevSpaces provider

### ISSUE THREAD

**Issue by GiancarloLelli** [Azure/dev-spaces#23]
Hi all
I'm currently hitting a roadblock when I try to debug on Azure DevSpace a blank Kubernetes Application created with File -> New Project. 

The error seems to be related to my Dreamspark subscription (A "free" Azure subscription for students) which has limited capability due to its billing limitation. 

Unfortunately, when VS tries to register the DevSpaces provider on this subscripton it fails and it blocks the publishing process even if I have multiple Azure Subs associated to the same account, and by the checks that I have made some already have this providere registered so should ebe visible in the drop down.

Below a screenshot of the error I get:
![image](https://user-images.githubusercontent.com/6195018/45915873-11858880-be5d-11e8-95bb-880c1389c0f7.png)

And how the publish window appears after clicking "Ok"
![image](https://user-images.githubusercontent.com/6195018/45915891-63c6a980-be5d-11e8-9f6e-12807107a355.png)

**Comment by lolodi** [comment]
@GiancarloLelli could you make sure you have the latest VS extension installed? We had an [issue](https://github.com/Azure/dev-spaces/issues/20) with multiple subscriptions in the past and this might help.
@mthalman-msft could we have a better handling of scenarios in which we cannot register our provider in all the subscriptions that are accessible to the user?

**Comment by lolodi** [comment]
@GiancarloLelli could you make sure you have the latest VS extension installed? We had an [issue](https://github.com/Azure/dev-spaces/issues/20) with multiple subscriptions in the past and this might help.
@mthalman-msft could we have a better handling of scenarios in which we cannot register our provider in all the subscriptions that are accessible to the user?

**Comment by mthalman-msft** [comment]
@GiancarloLelli Would you be able to provide some more diagnostic information?  I'm wondering whether there's an underlying exception being thrown that could provide more context.  Can you please attach a second instance of VS to the VS instance that produces this error.  And then configure the debugging VS instance to break on exceptions.  The exception to look for is named InvalidUsageException.  I'm interested in knowing if it has an InnerException and what the details of that InnerException are.

**Comment by GiancarloLelli** [comment]
@mthalman-msft I don't see any exception being thrown. Once this dialog pops up the output window is clear and it only displays the AppInsights Telementry logs.
![image](https://user-images.githubusercontent.com/6195018/46080001-fab29f00-c198-11e8-8385-869d55afb44f.png)
![image](https://user-images.githubusercontent.com/6195018/46080027-0d2cd880-c199-11e8-953a-a46448ca9ef6.png)

**Comment by mthalman-msft** [comment]
Have you disabled the "Enable Just My Code" option in Tools -> Options -> Debugging?

**Comment by GiancarloLelli** [comment]
@mthalman-msft Right, forgot about that - now I can see the exception.
![image](https://user-images.githubusercontent.com/6195018/46081276-68ac9580-c19c-11e8-8930-4dd7c3ce5e49.png)
I'm unable to load the PBDs to drill down with historical debugging, if you can help me with that I can see if I can gather some more detailed information.

**Comment by mthalman-msft** [comment]
Yeah, that's just showing what we already know from the error message.  I need to know what the InnerException is.  You shouldn't need to use historical debugging.  Just configure VS to break on all CLR exceptions and keep executing until you hit this InvalidUsageException.  Then you should be able to examine its InnerException.

**Comment by GiancarloLelli** [comment]
Gotcha - but it is the same message, even the Inner exception.
![image](https://user-images.githubusercontent.com/6195018/46082210-d8238480-c19e-11e8-806e-c3b497b14e90.png)

**Comment by darthkurak** [comment]
Im facing exactly the same error. It seems that VS extension validate DevSpaces against all the subscriptions, and if one of them failes (in my case DreamSpark subscription which doesn't has permission to register this provider) - whole extension fail, and i cannot set-up DevSpace in another subscription. There is no workaround for this? :(

**Comment by lisaguthrie** [comment]
@darthkurak sorry to hear you are hitting it too :( The fix for this problem is checked in, but we've had some unrelated issues that have prevented us from releasing a new version of the extension. I'm pushing to get an updated build released in the next few days. I'll keep you posted.

**Comment by lisaguthrie** [comment]
Hi @GiancarloLelli and @darthkurak - we just pushed a new version of the extension that should address this issue. Can you give it a shot and let me know if it helps? Thanks!

**Comment by darthkurak** [comment]
Hi! It works now! Thanks for quick response.
I wonder - this debugging feature doesn't work for .net core console app in AKS? Because, i cannot choose Azure Dev Space when switching to it. :(

**Comment by lisaguthrie** [comment]
Dev Spaces doesn't currently support console apps, but we've gotten that feature request from other customers as well, and it's under consideration :)

**Comment by GiancarloLelli** [comment]
@lisaguthrie @mthalman-msft Thanks guys. It works now :) 
![image](https://user-images.githubusercontent.com/6195018/46860099-f67cb780-ce0f-11e8-946f-91467eb7317d.png)
