### ISSUE TITLE
How to use traefik or ingress to inject route headers

### ISSUE THREAD

**Issue by abhall724** [Azure/dev-spaces#234]
I need to get the routing to work correctly for Dev Spaces without modifying the existing code. There are annotations we can add to inject headers into each request, but I can't seem to find what the value of the "azds-route-as" property. Can we manually manipulate the request headers and inject this value without having to modify the code?

**Comment by stepro** [comment]
@abhall724, it will depend on what language you are using as to whether it can support automatically propagating headers from a particular incoming request to outgoing requests associated with that incoming request. If you are using ASP .NET core, it is possible to hack something together today but the team is working on providing a better solution. I believe it is possible in Java as well, but I'm not sure of the details.

If you can provide some more details on the language you are using, I might be able to provide some more helpful pointers.

**Comment by abhall724** [comment]
We are using ASP .Net core, we currently use AutoRest to build clients to communicate from service to service inside the cluster. Each service is owned by different teams and would require a significant effort to copy and paste the header code to each client method for each service. Additionally, we have a front end website that is written in Angular, but we can modify that code if needed.

**Comment by abhall724** [comment]
Any follow up to this?

**Comment by stepro** [comment]
If you're using ASP .NET Core, there is a [NuGet package](https://www.nuget.org/packages/Microsoft.AspNetCore.HeaderPropagation/) that can help with this. It still requires code changes, but only to your Startup.cs. You might be able to make this work in conjunction with [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration), which would allow you to inject an assembly somewhere that is automatically loaded and contributes the header propagation middleware to your existing code without any other changes. There is also an approach for dynamically loading and running code in other assemblies that isn't ASP .NET Core specific, described [here](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/docs/design/features/host-startup-hook.md).

Hopefully something in here will help!
