### ISSUE TITLE
Unable to route traffic to namespaces deployed manually

### ISSUE THREAD

**Issue by abhall724** [Azure/dev-spaces#246]
We have deployed our application to a default namespace, currently named dev, using our normal kubectl scripts. The pods and containers were all successfully deployed and are running locally in the correct namespaces. We had to use local namespace routing to get the services to reference each other (http://<servicename>.dev.svc.cluster.local). However, when deploying a single service to a child namespace the routing completely break. We can not use the dev spaces routing as it is inteded by either the local namespace (http://<servicename-notdeployed>.dev-child.svc.cluster.local) or the public address we gave our azds deployed service (dev-child.s.dev.<servicename-notdeployed>.<suffix>.eus.azds.io).

**Comment by stepro** [comment]
> We had to use local namespace routing to get the services to reference each other (http://.dev.svc.cluster.local).

Can you explain the reason for this? By fully qualifying service names, you are explicitly stating which namespace you intend to use and routing will not re-route the call to a child namespace.

**Comment by abhall724** [comment]
Couldn't get local routing, (i.e. http://<service-name>/) to work at the moment. We are attempting to route traffic in a local network without exposing the cluster except through an Azure API Management endpoint.

**Comment by stepro** [comment]
@abhall724, sorry for the delay (holidays). A few clarifying questions:

- By "local routing" do you mean when code is running in the cluster, it doesn't work to say "http://myservice" when "myservice" is another service running in the same namespace as the calling code?
- Is your application split across multiple namespaces such that "callingservice" and "myservice" are running in two different namespaces, therefore you need to use a more qualified name like "http://myservice.othernamespace" to call from "callingservice" to "myservice"?
