### ISSUE TITLE
Run AZDS inside a container

### ISSUE THREAD

**Issue by abhall724** [Azure/dev-spaces#247]
Is there a compatible image to run AZDS commands? Running the commands inside the AZCLI image or the Ubuntu image throws an error message.

**Comment by rakeshvanga** [comment]
@abhall724 We do support our CLI on Linux images. To get you started you can try the following Dockefile of an Ubuntu image.
```
FROM ubuntu:18.04
RUN apt-get update && apt-get -y install sudo wget libssl1.0-dev libicu-dev libunwind8
RUN wget -O - https://aka.ms/get-azds-linux | sudo bash
RUN azds --version
```
If you need to do run more complex `azds` commands, add the installation steps for `az cli` as well in this dockerfile. (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)

We have not tested Azure Dev Spaces client on an AzureCLI image.

**Comment by abhall724** [comment]
OK How can you select the controller interactively..If I use az aks use-dev-spaces it prompts for authorization?
