### ISSUE TITLE
VS Code extension and long text in toolbar causes dev spaces to disappear

### ISSUE THREAD

**Issue by JanneMattila** [Azure/dev-spaces#249]
Dev spaces has quite long text in toolbar when connected:
![Connected image](https://user-images.githubusercontent.com/2357647/69716030-ed34d400-1111-11ea-8a35-f81be416a166.png)

Unfortunately this means that if you zoom even a bit in VS Code your dev spaces functionality disappears:
![Dev spaces hidden](https://user-images.githubusercontent.com/2357647/69716078-03db2b00-1112-11ea-927e-7cf35e67c45b.png)

This means that you cannot access easily "Go to ..." functionality:
![go to](https://user-images.githubusercontent.com/2357647/69716167-2ff6ac00-1112-11ea-90a6-073a510ccf08.png)

This is quite confusing for end user so maybe better option would be clip that in case it doesn't fit in long text mode (believe me I was confused when given demo and couldn't find the button I was looking for :laughing:).

**Comment by daniv-msft** [comment]
Thank you Janne for reporting this issue!
The text displayed in the status bar is indeed quite long in this case.
I'm having a look at this and will update this issue once we have a fix.

**Comment by daniv-msft** [comment]
We decided to keep only "Dev Spaces: Connected" in the status bar, so that it is shorter.
This will be available with the next release of the extension, at the beginning of January.
I'll close this issue once the fix is available.

Thanks again @JanneMattila for reporting this issue!

**Comment by daniv-msft** [comment]
The new version of the VS Code extension including this fix was released today!
I'm closing this issue, but please let us know if you run into any other problem.
