### ISSUE TITLE
Bad Gateway when trying to debug a new project in VS 2019 16.3.10

### ISSUE THREAD

**Issue by irharison** [Azure/dev-spaces#250]
I don't seem to be able to access the new web solution that I've created when its running inside Azure.  I get Bad Gateway from azds up as well as when running from debug mode in visual studio.

The web project is a bare bones solution with just the startup page.

Do you have any ideas how I can fix this ?

**Comment by ShrutiPPathak** [comment]
Thanks for reporting the issue. After running azds up, could you please open your Kubernetes dashboard and confirm that the service was built and started successfully? Also, it would be great if you could provide the output of your "azds up" command.

**Comment by jbockle** [comment]
might be related to #253

**Comment by YuzorMa** [comment]
Closing the issue as we need some more information to reproduce or debug.
