### ISSUE TITLE
Build fails only in Azure Dev Spaces

### ISSUE THREAD

**Issue by abhall724** [Azure/dev-spaces#252]
I have a project that builds fine locally and with docker, however when I attempt to deploy it using Azure Dev Spaces it throws an error that it can't find a local class. Request ID: 35f14123-bd38-458e-ab66-e4c1e81410e9

**Comment by xinyanmsft** [comment]
can you let us know whether you are using VSCode, DevSpaces CLI or Visual Studio? 
It generates detailed log file under %temp%\Azure Dev Spaces\ directory. Can you post the log files as well?
