### ISSUE TITLE
running azds behind corporate proxy

### ISSUE THREAD

**Issue by jbockle** [Azure/dev-spaces#253]
I was receiving an SSL handshake failure and turns out azds cli isn't recognizing my system proxy settings.  I was able to workaround that error by adding `"System.Net.Http.UseSocketsHttpHandler": false` to the azds.runtimeconfig.json where azds cli is installed.  

I'm still running into issues, but not entirely sure its related to proxy yet, but wanted to report this as a bug as I would expect it to pull from system settings automatically instead of having to configure the cli.

System Info:
Windows 10 Enterprise 1709
Azure Dev Spaces CLI 1.0.20191204.4
API v3.2

**Comment by xinyanmsft** [comment]
thanks for reporting. we will investigate.

**Comment by rakeshvanga** [comment]
@jbockle, Can you share the logs of azds cli from %TEMP%/Azure Dev Spaces folder?
Also when you say running azds behind the firewall, do you mean running azds cli in a corporate network with a firewall or even your AKS cluster is behind a firewall?
If your aks cluster is also behind a firewall then you need to configure additional things to enable Azure Dev Spaces to work. Can you share the scenario that are not working for you and I let you know how to configure things to unblock you.

**Comment by jbockle** [comment]
@rakeshvanga sorry I edited the post just now to correct, I meant behind a proxy

**Comment by rakeshvanga** [comment]
@jbockle, Thanks for the update. Are you facing any other issue while using our product other than working behind a proxy?

**Comment by jbockle** [comment]
@rakeshvanga , yes, and unfortunately they are difficult to pinpoint due my companies many required security agents/proxy filters.  I did get a bit further.  Is there a list of required ports/endpoints/other requirements that should be considered in order to use it? I haven't been able to find anything specific for it yet.  Right now, I'm able to use 'azds up' to run, but using both the vs/vsc extensions to run and debug is not working.  I'm not on my work PC atm, so I will get back to you with more specifics/logs, but iirc I'm receiving an error along the lines of "Container not available".

**Comment by rakeshvanga** [comment]
@jbockle Thanks for the inputs. 
Regarding ports we do a port forwarding to the AKS cluster from your machine. To define particular ports from your machine and the ports of the container, you can pass `--port <local1>:<remote1>` to `azds up` command and select ports that are enabled on your machine.

If you can provide the subscription you have used to create your AKS cluster, I can look up logs on the server-side to investigate the root cause.

**Comment by jbockle** [comment]
sure the subscription id is `826d5ea2-cb82-48e4-b298-2a848d352edc`.  My prelaunch vscode task does contain the --port switch.  I'm not sure what I did but after recreating my cluster, and setting up a fresh express api and prepping it for azds, I'm not even getting the error anymore, it just hangs on the prelaunch task, below is its output:

```
> Executing task: C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI\azds.exe up --port=58275:9229 --await-exec --keep-alive <

Synchronizing files...22s
Using dev space 'default' with target 'aks-cluster'
Installing Helm chart...1s
Waiting for container image build...3s
Building container image...
Step 1/7 : FROM node:lts
Step 2/7 : EXPOSE 3000
Step 3/7 : WORKDIR /nodeapp
Step 4/7 : COPY package.json .
Step 5/7 : RUN npm install
Step 6/7 : COPY . .
Step 7/7 : CMD ["npm", "start"]
Built container image in <1s
Waiting for container...3s
Service 'nodejs' port 'http' is available at http://default.nodejs.jpcfs649ql.eus2.azds.io/
```

**Comment by jbockle** [comment]
I placed my sample project and the logs in this repo: https://github.com/jbockle/az-aks-azds-testing

**Comment by rakeshvanga** [comment]
hey, @jbockle I have investigated the logs and everything seems to fine. I have tried debugging through vscode your nodejs app and it ran successfully.  
Can you try debugging again using vscode?

**Comment by jbockle** [comment]
I'm still unable to get this working properly.  If I disconnect from my company's VPN and remove system proxy configuration, I can properly use the tooling.

**Comment by jbockle** [comment]
also, the visual studio extension does not work at all, i don't believe it is using azds cli like vscode is, and I'm not sure where to set the `"System.Net.Http.UseSocketsHttpHandler": false` setting

**Comment by rakeshvanga** [comment]
@jbockle, With your company's VPN and proxy configuration enabled, can you check if you are able to port-forward using `kubectl port-forward` to any pod in the cluster?
For Azure Dev Spaces to work, we need to port-forward to the pod running on the cluster. I suspect your company's VPN/proxy configurations are restricting certain network traffic from your dev machine.

For Visual Studio, you can follow the steps mentioned here to add the setting to runtime.config file.
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1#remarks

**Comment by jbockle** [comment]
Hi @rakeshvanga, unfortunately it's not possible over public internet as my company blocks that.  Theoretically, if my AKS cluster was behind an express route and I setup a custom ingress controller, would I be able to use "kubectl port-forward" over the express route instead of public internet from my dev machine?

* If so, is there any documentation or guidance you can provide?  
* If not, is "kubectl proxy" an option?

**Comment by rakeshvanga** [comment]
@jbockle, sorry for the delayed response. 
Yes, if you set up your dev machine and aks cluster to be in the same network via express route, you can use all the functionalities even without a custom ingress controller.
This documentation here provides detailed information about the networking requirements for Azure Dev Spaces:  https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking.

**Comment by jbockle** [comment]
okay thanks, we'll give it a try in the coming months we are still working on setting up our aks infrastructure
