### ISSUE TITLE
Please write a restriction : we can't use the Multi Stage Build of Docker.

### ISSUE THREAD

**Issue by yoshioterada** [Azure/dev-spaces#26]
I tried to execute Dev Space of Java Version.

If we executed the following command, automatically some file will be created.

$ azds prep --public

Especially, in this time I want to say following 3 files.

* Dockerfile
* Dockerfile.develop
* azds.yaml

As default, azds.yaml file was wrote as following.

azds.yaml : default

```
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
```

And in order to create more small size of image, I tried to change the dockerfile to ***Dockerfile*** as follows "removed the .develop".

azds.yaml : Multi Stage Build
```
configurations:
  develop:
    build:
      dockerfile: Dockerfile
```

Then, I executed the following command, then following error was showed.

```
$ azds up
Using dev space 'default' with target 'yoshio-devspace'
Synchronizing files...6s
Installing Helm chart...2s
Waiting for container image build...10s
Building container image...
Step 1/12 : FROM openjdk:8-jre-slim AS base
Error parsing reference: "openjdk:8-jre-slim AS base" is not a valid repository/tag: invalid reference format
Failed to build container image.
Service cannot be started.
Service cannot be started.
```

In fact, the Dockerfile was wrote as Multi Stage Build.

```
FROM openjdk:8-jre-slim AS base
EXPOSE 8080
WORKDIR /app

FROM maven:3.5-jdk-8-slim AS build
WORKDIR /usr/src/app
COPY pom.xml .
RUN ["/usr/local/bin/mvn-entrypoint.sh", "mvn", "verify", "--fail-never"]
COPY . .
RUN ["mvn", "package"]

FROM base AS final
COPY --from=build /usr/src/app/target .
CMD ["java", "-jar", "webfrontend-0.1.0.jar"]
```
However, it is impossible to create the Multi Stage Build in current(latest) AKS version.
Because the Docker version is 1.13.1. As you know the Multi Stage Build was supported since 17.05. ( [FeedBack Request : Increase Kubernetes node docker version to 17.05.x & +](https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917076-increase-kubernetes-node-docker-version-to-17-05-x))
So I assume that the above command failed.

```
$ kubectl get node -o wide
NAME                       STATUS    ROLES     AGE       VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-16231366-0   Ready     agent     3h        v1.11.3   10.240.0.5    <none>        Ubuntu 16.04.5 LTS   4.15.0-1023-azure   docker://1.13.1
```

If you created the Dockerfile of Multi Stage version, please write the ***NOTE*** that we will not be able to use the file now.
Actually I don't know which location is appropriate. I think that following site may be better?

[https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting](https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting)

**Comment by lisaguthrie** [comment]
Thanks @yoshioterada -- we added it in to the troubleshooting document: https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#error-service-cannot-be-started

**Comment by yoshioterada** [comment]
Thank you so much !!
