### ISSUE TITLE
Dev Spaces supporting Helm 3

### ISSUE THREAD

**Issue by greenie-msft** [Azure/dev-spaces#272]
The Dev Spaces team is seeking individuals and/or teams interested in participating in early access of Dev Spaces supporting Helm 3.  If interested, please use the link below to sign-up and we will reach out with further details. 

https://aka.ms/azds-preview-signup

Thank you!
Nick
Azure Dev Spaces Pm

**Comment by YuzorMa** [comment]
Dev spaces now uses Helm3 by default.
