### ISSUE TITLE
Not able to clone from Github

### ISSUE THREAD

**Issue by rnga** [Azure/dev-spaces#274]
PS C:\windows\system32> git clone https://github.com/Azure/dev-spaces
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ git clone https://github.com/Azure/dev-spaces
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by stepro** [comment]
@rnga, if you are following one of our CLI-based tutorials, then an assumed prerequisite is that you have installed Git (in your case, for Windows), likely from [here](https://git-scm.com). Sorry that this is not clear in the documentation.
