### ISSUE TITLE
Helm Install command syntax is incorrect (in instructions)

### ISSUE THREAD

**Issue by thoaingan** [Azure/dev-spaces#284]
**Describe the bug**
The current version of Chart.yaml has the application name as "bikesharingsampleapp". However, the instructions show the Helm Install command to be "bikesharing". It should be updated to say "helm install bikesharingsampleapp [...]"

![image](https://user-images.githubusercontent.com/7240365/74254832-a1c4a780-4cb6-11ea-9d77-240214190bae.png)
 
**To Reproduce**
Steps to follow to reproduce this issue.

![image](https://user-images.githubusercontent.com/7240365/74254812-98d3d600-4cb6-11ea-8e99-f97495660a21.png)

 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Azure Dev Spaces
For OSX/Linux: $TMPDIR/Azure Dev Spaces
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
C:\Repos\dev-spaces\samples\BikeSharingApp\charts>azds --version
Azure Dev Spaces CLI
1.0.20200204.4
API v3.2
Client's version:
Operating System: Windows 10
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by philon-msft** [comment]
@thoaingan, thank you for pointing this out. We'll get the doc updated soon.

**Comment by zr-msft** [comment]
@thoaingan thank you for the feedback. The docs have been updated:
https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-team-development#run-the-sample-application-in-kubernetes

#please-close
