### ISSUE TITLE
Failed to configure container host for Azure Dev Spaces Controller

### ISSUE THREAD

**Issue by leizhang** [Azure/dev-spaces#286]
[azds-sdk-2020-02-16-23-57-23-23044.txt](https://github.com/Azure/dev-spaces/files/4211281/azds-sdk-2020-02-16-23-57-23-23044.txt)
**Describe the bug**

We have Azure kubernetes services instance hosted in Australia East region, 3 nodes. agent nodes is in 'Ready' state,  one node reach 70% of the total CPU. I checked the service principal is valid.  Still getting the following error every time I try to enable azure dev spaces - both in CLI and on web. 

**_Long running operation failed with status 'Failed'. Additional Info:'Failed to configure container host for Azure Dev Spaces Controller. Please check that the service principal used to create the cluster is valid and the agent nodes are in 'Ready' state and not running low on resources._**

**To Reproduce**
Steps to follow to reproduce this issue.

 
**Expected behavior**
 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Azure Dev Spaces
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
Client's version: 
_Azure Dev Spaces CLI
1.0.20200204.4
API v3.2_
Operating System:
Windows 10
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by pragyamehta** [comment]
Hi @leizhang Thank you for reporting this issue. I have logged a bug for our team to investigate this.

**Comment by leizhang** [comment]
> Hi @leizhang Thank you for reporting this issue. I have logged a bug for our team to investigate this.

Thanks, @pragyamehta.

**Comment by sanar-microsoft** [comment]
@leizhang It looks like this controller has been deleted. From our service logs I can see that we were unable to run the pod on this cluster and get the logs from it. 

`tunnelfront` pod in `kube-system` namespace is responsible for maintaining the connection to get logs, deleting it and recreating it can solve the tunneling problem if there is one. Also please check that the cluster nodes have enough CPU and memory.

In case you still see this issue, please don't remove the dev spaces controller for further investigation. Thanks!

**Comment by leizhang** [comment]
@sanar-microsoft,  thank you for your reply! Straight to the point.  After I deleted the tunnelfront pod in kube-system, I'm able to enable dev-space in our instance. Thank you.

> @leizhang It looks like this controller has been deleted. From our service logs I can see that we were unable to run the pod on this cluster and get the logs from it.
> 
> `tunnelfront` pod in `kube-system` namespace is responsible for maintaining the connection to get logs, deleting it and recreating it can solve the tunneling problem if there is one. Also please check that the cluster nodes have enough CPU and memory.
> 
> In case you still see this issue, please don't remove the dev spaces controller for further investigation. Thanks!
