### ISSUE TITLE
Routing to child spaces not working

### ISSUE THREAD

**Issue by aaronwjha** [Azure/dev-spaces#287]
We have configured Dev Spaces for a simple application with an Angular front end and a .NET Core 3.0 webapi. We are able to debug using VisualStudio when running in the parent space, but routing to child spaces is not working. We have added code to propagate the 'azds-route-as' headers and have confirmed that the azds-proxy container is running in all pods. We don't see any 'azds-route-as' headers being added to any calls. What are the best steps to troubleshoot?

**Comment by amsoedal** [comment]
Hi @aaronwjha, thanks for reaching out!  Did you add code for propagating the route-as header to the front end or the webapi or both?  Also, can you send us the host suffix for your controller so we can investigate on our side?  You can find it with the `azds show-context` command.
