### ISSUE TITLE
Dev Spaces with production cluster?

### ISSUE THREAD

**Issue by dahovey** [Azure/dev-spaces#295]
There seems to me conflicting information on using Dev Spaces on a production cluster. Early in the documentation under "Overview" and "About Azure Dev Spaces" it states "...is not intended to run on production AKS clusters". Then under "How to" and "Using CI/CD with Azure Dev Spaces" there is an actual example on how to structure namespaces on a production cluster with Dev Spaces.

While this deals with the content of documentation, and could probably be posted on another repository, I would like to get clarification on the **technical implications on using Dev Spaces on a production cluster.**

I understand that during development, using Dev Spaces, the containers are built using the active AKS cluster? As well there are a few pods required for Dev Spaces instrumentation? What other considerations/implications are there? 

* [https://docs.microsoft.com/en-us/azure/dev-spaces/about](https://docs.microsoft.com/en-us/azure/dev-spaces/about)
* [https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/setup-cicd#dev-spaces-instrumentation-in-production](https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/setup-cicd#dev-spaces-instrumentation-in-production)

**Comment by stepro** [comment]
Hi David,

Dev Spaces is very much a development tool, and is not intended for use in production. What the documentation describes is how you can use Dev Spaces in a non-production cluster, or in a cluster that uses namespaces to separate between non-production and production workloads. The latter is not something we would recommend for isolation reasons, but is possible and may work well for smaller projects where cost is a concern.

The things to think about when enabling Dev Spaces on a production cluster would be:


  *   The extra workloads that are deployed into the “azds” namespace, and the compute required to run these (minimal, but not nothing);
  *   The extra overhead of pods that were deployed using Dev Spaces, where compute is used to build the container image that will be run, and the container image is typically fatter than an optimized production image;
  *   The extra overhead of sidecar containers in namespaces that are designated as Dev Spaces (also rather minimal, but contributes to overall load).

Then of course the security implications of allowing developers to play in the same cluster as production workloads, especially given the fact that today, Dev Spaces effectively gives developers admin access to the cluster so they might inadvertently mess up the production workloads.

Hope that helps,
Stephen

**Comment by dahovey** [comment]
This does help. Thanks.
