### ISSUE TITLE
Error when trying to enable dev spaces

### ISSUE THREAD

**Issue by tdelbosco** [Azure/dev-spaces#299]
**Describe the bug**
When attempting to enable dev spaces on an AKS cluster I got back the error:  
 Creating and selecting Azure Dev Spaces Controller 'k8s-devspaces-ea' in resource group 'shared_ea_eca-east2-rg' that targets resource 'k8s-devspaces-ea' in resource group 'shared_ea_eca-east2-rg'...Failed to create Azure Dev Spaces Controller 'k8s-devspaces-ea' in resource group 'shared_ea_eca-east2-rg' in subscription '343ee394-ba45-424a-8c80-eb113154cff8' - Long running operation failed with status 'Failed'. Additional Info:'Failed to configure container host for Azure Dev Spaces Controller.'

**To Reproduce**
Try to enable dev spaces with command:  az aks use-dev-spaces -g shared_ea_eca-east2-rg -n k8s-devspaces-ea
[azds-sdk-2020-03-27-13-20-54-24380.txt](https://github.com/Azure/dev-spaces/files/4394926/azds-sdk-2020-03-27-13-20-54-24380.txt)

 
Enable dev spaces and create controller
 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Azure Dev Spaces
For OSX/Linux: $TMPDIR/Azure Dev Spaces
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
azds --version
Azure Dev Spaces CLI
1.0.20200320.7
API v3.2
Client's version:
Operating System:
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by sanar-microsoft** [comment]
@tdelbosco From our service logs it looks like we were unable to ensure `traefik` load balancer on the cluster because of policy restrictions in your subscription. This resource type was denied: `Microsoft.Network/publicIPAddresses`. A service of type load balancer will try to create a public IP address in the resource group that contains the agent nodes for the cluster(resource group with name starting with MC_). Dev Spaces uses this public IP address to enable the routing functionality.

If you don't want the routing functionality, you can follow the steps [here](https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking#using-different-endpoint-options) to create a controller resource without traefik load balancer.

**Comment by tdelbosco** [comment]
Sorry for the delayed response,  the article referenced mentions V2.2 of the Azure CLI and my company required that to be approved before I can use it.  After getting V2.3.1, when I run the command to use a private endpoint.  I get the following message:
C:\>az aks use-dev-spaces -g ea-eca-east2-rg -n sbx-k8s-ds-cmdv2 -e private
az: error: unrecognized arguments: -e private

I've verified I'm using the latest az cli version:
C:\>az --version
azure-cli                          2.3.1

**Comment by philon-msft** [comment]
Hi @tdelbosco, could you add the `--update` arg to your command to make sure you have the latest Dev Spaces extension installed for the az CLI? More info here: 
https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/upgrade-tools#update-the-dev-spaces-cli-extension-and-command-line-tools

**Comment by tdelbosco** [comment]
@philon-msft thx for the quick response.  My work laptop is locked down so I can't install software.  I did get what I believe to be the latest version installed:

C:\>azds --version
Azure Dev Spaces CLI
1.0.20200407.9
API v3.2

**Comment by amsoedal** [comment]
Hi @tdelbosco ! Does the issue reproduce if you run `azds use -g <your group> -n <your cluster> -e private`  instead?

**Comment by tdelbosco** [comment]
@amsoedal   That works!  Thx for the help, the documentation [here](https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking#using-different-endpoint-options) needs to be updated.
