### ISSUE TITLE
Problem with dotnet core 2.1

### ISSUE THREAD

**Issue by mclasson** [Azure/dev-spaces#3]
When creating two services (frontend and webapi or whatever) you get a `Host not found`  error  when the one is calling the other that you don't get with _dotnet core sdk 2.0_. It seems it's not emitting the header "azds-route-as"
Could it be so?
I have a little more elaborate decription to reproduce here [link](https://github.com/mclasson/kubernetes-demo/blob/master/Demo-script.md)

**Comment by philon-msft** [comment]
Hi @mclasson, we adjusted our header propagation pattern recently so when your service calls another service, it'll need to explicitly propagate the azds-route-as header. For details see: https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-netcore#call-a-service-running-in-a-separate-container
