### ISSUE TITLE
VS2017 hang after hit F5

### ISSUE THREAD

**Issue by doggy8088** [Azure/dev-spaces#31]
I'm following the [Get Started on Azure Dev Spaces with .NET Core and Visual Studio](https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-netcore-visualstudio) tutorial.  

When I configured Azure Dev Spaces, then hit **F5**.  It's usually hang my Visual Studio 2017 very long long time.  

If I kill all the `devenv.exe` related processes and re-open VS2017 again, then Azure Dev Spaces will works smoothly.

**Comment by lisaguthrie** [comment]
Does this happen consistently?

Can you enable more detailed logging as described here: https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#enabling-detailed-logging
And then send the logs if you're able to reproduce the problem?

**Comment by YuzorMa** [comment]
Closing as it as been over a month.  Please reactivate if this repros again (and provide the logs).
