### ISSUE TITLE
Error related to launchSettings.json error is ambiguous. 

### ISSUE THREAD

**Issue by CraigHead** [Azure/dev-spaces#320]
**Describe the bug**
When I launch my project, I get the following error:
`Errors in 'C:\\code\\Shared\\tests\\Hosting.Tests\\Properties\\launchSettings.json' need to be corrected before applying changes.`
 
**To Reproduce**
Create a project that has the following defintion:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.2" />
        <PackageReference Include="Moq" Version="4.13.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
        <PackageReference Include="xunit" Version="2.4.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
    </ItemGroup>

</Project>
```
Create a launchSettings.json file with the following content:
```json
﻿{
    "profiles": {
        "Server": {
            "commandName": "Project",
            "launchBrowser": false,
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "applicationUrl": "https://localhost:10101;http://localhost:10100"
        }
    }
}
```

 
**Expected behavior**
No error is produced.
 
**Logs**
```json
{
  "timestamp": "2020-04-23 13-19-50.855",
  "message": "Process updated launch settings for a project.",
  "operationName": "ProcessChangedLaunchSettings",
  "stage": "Start"
}
{
  "timestamp": "2020-04-23 13-19-50.867",
  "message": "Process updated launch settings for a project.",
  "operationName": "ProcessChangedLaunchSettings",
  "stage": "End",
  "elapsedTime": "00:00:00.0111064",
  "completionState": "Succeeded"
}
{
  "timestamp": "2020-04-23 13-20-09.458",
  "message": "Errors in 'C:\\code\\Shared\\tests\\Hosting.Tests\\Properties\\launchSettings.json' need to be corrected before applying changes.",
  "projectPath": "C:\\code\\Shared\\tests\\Hosting.Tests\\Hosting.Tests.csproj",
  "exception": {
    "ClassName": "System.Exception",
    "Message": "Errors in 'C:\\code\\Shared\\tests\\Hosting.Tests\\Properties\\launchSettings.json' need to be corrected before applying changes.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsProvider.<GetSnapshotThrowIfErrors>d__85.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsProvider.<>c__DisplayClass81_0.<<AddOrUpdateProfileAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Threading.Tasks.SequentialTaskExecutor.<>c__DisplayClass5_0.<<ExecuteTask>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.ProjectSystem.DevSpacesLaunchProfileInitializer.<CreateNonPersistedDevSpacesLaunchProfileIfNecessaryAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.ProjectSystem.DevSpacesLaunchProfileInitializer.<InitializeAsync>d__13.MoveNext()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nMoveNext\nMicrosoft.VisualStudio.ProjectSystem.Managed, Version=16.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\nMicrosoft.VisualStudio.ProjectSystem.Debug.LaunchSettingsProvider+<GetSnapshotThrowIfErrors>d__85\nVoid MoveNext()",
    "HResult": -2146233088,
    "Source": "Microsoft.VisualStudio.ProjectSystem.Managed",
    "WatsonBuckets": null
  }
}
```
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
VS 2019 Version 16.5.4
Operating System: Windows 10 v1909
 
**Additional context**
Add any other outputs from the clients or context you would like to share.

**Comment by rakeshvanga** [comment]
Hi @CraigHead, Thanks for the detailed inputs.
Are you seeing these errors when using debugging using Azure Dev Spaces and not with the regular F5?
I'm trying to understand if this case is generic error and may be related to Azure Dev Spaces.

**Comment by CraigHead** [comment]
@rakeshvanga thanks for the reply. It only happens during startup of Visual Studio.

**Comment by danegsta** [comment]
@CraigHead I've done some investigation and the only scenario for which I've been able to reproduce this error is if I modify launchSettings.json to have invalid JSON formatting. Can you open the Properties/launchSettings.json for the project in VS check for any ~ marks indicating JSON formatting errors?

**Comment by CraigHead** [comment]
Unless I'm missing something here, I do not see any invalid JSON or squiggles in Visual Studio.

![image](https://user-images.githubusercontent.com/2760345/80837100-6948b180-8bb3-11ea-9ad1-4b3d03156b55.png)

However, I think I've figured this out using a hex editor. 
This is what I had, which I believe is causing the error:

![image](https://user-images.githubusercontent.com/2760345/80838893-44563d80-8bb7-11ea-872c-54aa1575c146.png)

However this fixes it:

![image](https://user-images.githubusercontent.com/2760345/80838924-57690d80-8bb7-11ea-8c60-130bd5bb210e.png)

I've attached sample files. Please take the `.txt` file extension off. 

[launchSettings_ok.json.txt](https://github.com/Azure/dev-spaces/files/4566153/launchSettings_ok.json.txt)
[launchSettings_not_ok.json.txt](https://github.com/Azure/dev-spaces/files/4566155/launchSettings_not_ok.json.txt)

**Comment by danegsta** [comment]
It looks like the UTF8 byte order mark got added twice to the file, so it's getting read as an undisplayable character. That would definitely break the JSON parsing for launchSettings.json, since it wouldn't read that as a whitespace character.

**Comment by CraigHead** [comment]
Assuming the implementation is in .NET, perhaps setting the `UTF8Encoding(Boolean, Boolean)` constructor and set the `throwOnInvalidBytes`? This setting enabled detection an invalid sequence of characters or bytes and will raise an `ArgumentException`. If an `ArgumentException` is thrown, surface a better message to the user?

**Comment by danegsta** [comment]
It looks like the actual exception is thrown by the .NET project system (common base for .csproj, .vbproj, etc.) here: https://github.com/dotnet/project-system/blob/c30aee10ee4ef8944c71fdf621fbbd4c8d05eeb0/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs#L881

We're triggering it as we attempt to scaffold an additional launch settings profile which triggers the launchSettings.json parser to run. It appears the relevant exceptions aren't surfaced by VS during the initial launchSettings.json load at project open.
