### ISSUE TITLE
Feature request/Question: Azure CDN and Dev Spaces

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#327]
Hi!

When developing a GUI for a system, the project often contains alot of static resources like images, css and so on. All theese resources (by default) are syncronised to the docker container used to build the project.

This is fine in smaller systemet but when developing large scale solution containing multiple gui projects (composite gui), serving static resources from docker containers is not optimal.

What you want to do is to serve theese from Azure CDN. 

It would be awsome If I could change the config file for DevSpaces so that some of my static resources are synched to my docker container and some to my Azure CDN.

This way I could setup a "GUI Style" project, that holds my static resources and synchronizing them to Azure CDN, but also handle my tenants custom styles and serving dynamic css from my docker container to all the GUI projects.

**Comment by daniv-msft** [comment]
(Adding @greenie-msft, for FYI)

This is great feedback, thank you @Eneuman!
We are presently preparing new capabilities for Dev Spaces, and our Program Managers are gathering feedback about the current experience, how to improve it and how to integrate this kind of feature requests with it.

If you are willing to discuss with our PM team about these, could you please reach to us as explained here: https://github.com/Azure/dev-spaces/issues/325?

Thanks!
