### ISSUE TITLE
Feature request: Consider use YARP as reverse proxy

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#328]
Microsoft is developing a new reverse proxy "YARP" (https://github.com/microsoft/reverse-proxy) 
The performance in YARP is looking really good. Today Azds uses traefk and it adds alot of ms to the requests and is missing key features (like using SSL in DevSpaces).

Please consider working with the YARP team to add the features needed for AZDS so it can replace traefk :)

**Comment by daniv-msft** [comment]
(Adding @greenie-msft, for FYI)

Good feedback as well. As mentioned in the other issue, would you be willing to reach out to our PM team about this (https://github.com/Azure/dev-spaces/issues/325)?

Thanks!

**Comment by Eneuman** [comment]
Hi,
Yes, of course.
I have spoken to @greenie-msft before so I'll contact him to setup a Teams meeting and i'll share out latest ideas/findings :)
