### ISSUE TITLE
Cannot deploy Service from VS to Kubernetes anymore

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#329]
**Describe the bug**
Today I started to receive this error when trying to debug from VS:

An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = KubernetesExec (ReflectionActivator), Services = [Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.KubernetesExec, Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.ContainerOrchestratorExecBase], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm2Client, System.Func`2[Microsoft.Azure.DevSpaces.Common.Services.Helm3.Model.Helm3ClientConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm3Client], System.Func`3[Microsoft.Azure.DevSpaces.Common.Logging.LoggingConstants+TargetCluster,k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Kubernetes.IKubernetesClient], System.Func`2[k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Spaces.ISpaceManager], System.Lazy`1[Microsoft.AspNetCore.SignalR.IHubContext`2[Microsoft.Azure.DevSpaces.ExecService.SignalR.ExecSignalRHub,Microsoft.Azure.DevSpaces.ExecService.Client.Streaming.IExecStreamingClient]], Microsoft.Azure.DevSpaces.Common.Logging.ILog, Microsoft.Azure.DevSpaces.ExecService.Services.IConfigDocumentStore, Microsoft.Azure.DevSpaces.Common.Cache.ICacheService, Microsoft.Azure.DevSpaces.Common.IO.IFileSystem, Microsoft.Azure.DevSpaces.ExecService.IExecEnvironmentVariables, Microsoft.Azure.DevSpaces.ExecService.KubeConfigProvider)' on type 'KubernetesExec'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.)

I'm getting the same error on all services I'm trying to debug.
This has been working fine before. 
No changes has been made to my local computer or to our cluster.

**Comment by d4devblog** [comment]
I am getting the exact same error.
Trying to work out what has changed, and the only thing I can see, is a possible update to the azds images used when initialising the related pods.

https://hub.docker.com/r/azds/azds-image-prepull/tags

The DaemonSet in my azds namespace is showing image:  ***azds/azds-image-prepull:20200430.4***
Which was last updated 6 days ago.

I don't know how/when new images are pulled in... but all my pods were reinitialised overnight and now I cannot build! 

I am still getting to grips with Devspaces + Kubernetes - so hopefully some of this will make sense to someone and we can get a quick fix.

**Comment by d4devblog** [comment]
@Eneuman Are you able to confirm that images in the azds namespace are running at the same version as mine? Would be good to know if I am on to something - or clutching at straws.

You can get image info usign the following command (assuming you are using kubectl)

`kubectl get pods --namespace azds -o jsonpath="{..image}"`

**Comment by philon-msft** [comment]
Thanks for reporting this! I've identified the issue on our side, and we'll work on getting a fix rolled out ASAP.

**Comment by ynambiar** [comment]
@Eneuman or @d4devblog we have a fix available and would like to verify it on your controllers before deploying everywhere. Please email me (yanambia@microsoft.com) your subscription ids and controller names where you're seeing this issue, and I'll try to patch them.

**Comment by d4devblog** [comment]
Hi @ynambiar Thanks for the quick response on this.
Email sent!

**Comment by philon-msft** [comment]
Apologies to everyone who ran into this issue. A fix has been rolled out and all controllers have been updated. Please give it a try and let us know if you see any problems.
