### ISSUE TITLE
F5 from Visual Studio: An error occurred during the activation of a particular registration

### ISSUE THREAD

**Issue by ironicLemon** [Azure/dev-spaces#330]
**Describe the bug**
Create new dev space for net core 3.1 app in VS 2019 16.5.4, press F5 to run and get the error

{
  "timestamp": "2020-05-05 20-22-12.270",
  "message": "Rebuild the project contained in a service.",
  "exception": {
    "ClassName": "Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException",
    "Message": "An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = KubernetesExec (ReflectionActivator), Services = [Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.KubernetesExec, Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.ContainerOrchestratorExecBase], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm2Client, System.Func`2[Microsoft.Azure.DevSpaces.Common.Services.Helm3.Model.Helm3ClientConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm3Client], System.Func`3[Microsoft.Azure.DevSpaces.Common.Logging.LoggingConstants+TargetCluster,k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Kubernetes.IKubernetesClient], System.Func`2[k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Spaces.ISpaceManager], System.Lazy`1[Microsoft.AspNetCore.SignalR.IHubContext`2[Microsoft.Azure.DevSpaces.ExecService.SignalR.ExecSignalRHub,Microsoft.Azure.DevSpaces.ExecService.Client.Streaming.IExecStreamingClient]], Microsoft.Azure.DevSpaces.Common.Logging.ILog, Microsoft.Azure.DevSpaces.ExecService.Services.IConfigDocumentStore, Microsoft.Azure.DevSpaces.Common.Cache.ICacheService, Microsoft.Azure.DevSpaces.Common.IO.IFileSystem, Microsoft.Azure.DevSpaces.ExecService.IExecEnvironmentVariables, Microsoft.Azure.DevSpaces.ExecService.KubeConfigProvider)' on type 'KubernetesExec'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.)",
    "Data": null,
    "InnerException": {
      "ClassName": "Microsoft.Azure.DevSpaces.Common.Exceptions.ExecInternalServerErrorException",
      "Message": "An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = KubernetesExec (ReflectionActivator), Services = [Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.KubernetesExec, Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.ContainerOrchestratorExecBase], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm2Client, System.Func`2[Microsoft.Azure.DevSpaces.Common.Services.Helm3.Model.Helm3ClientConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm3Client], System.Func`3[Microsoft.Azure.DevSpaces.Common.Logging.LoggingConstants+TargetCluster,k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Kubernetes.IKubernetesClient], System.Func`2[k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Spaces.ISpaceManager], System.Lazy`1[Microsoft.AspNetCore.SignalR.IHubContext`2[Microsoft.Azure.DevSpaces.ExecService.SignalR.ExecSignalRHub,Microsoft.Azure.DevSpaces.ExecService.Client.Streaming.IExecStreamingClient]], Microsoft.Azure.DevSpaces.Common.Logging.ILog, Microsoft.Azure.DevSpaces.ExecService.Services.IConfigDocumentStore, Microsoft.Azure.DevSpaces.Common.Cache.ICacheService, Microsoft.Azure.DevSpaces.Common.IO.IFileSystem, Microsoft.Azure.DevSpaces.ExecService.IExecEnvironmentVariables, Microsoft.Azure.DevSpaces.ExecService.KubeConfigProvider)' on type 'KubernetesExec'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.)",
      "Data": null,
      "InnerException": {
        "ClassName": "Microsoft.AspNetCore.SignalR.HubException",
        "Message": "An unexpected error occurred invoking 'ListAzdsPodsAsync' on the server. ExecInternalServerErrorException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = KubernetesExec (ReflectionActivator), Services = [Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.KubernetesExec, Microsoft.Azure.DevSpaces.ExecService.ContainerOrchestratorExecs.ContainerOrchestratorExecBase], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm2Client, System.Func`2[Microsoft.Azure.DevSpaces.Common.Services.Helm3.Model.Helm3ClientConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Kubernetes.IDevSpacesHelm3Client], System.Func`3[Microsoft.Azure.DevSpaces.Common.Logging.LoggingConstants+TargetCluster,k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Kubernetes.IKubernetesClient], System.Func`2[k8s.KubeConfigModels.K8SConfiguration,Microsoft.Azure.DevSpaces.Common.Services.Spaces.ISpaceManager], System.Lazy`1[Microsoft.AspNetCore.SignalR.IHubContext`2[Microsoft.Azure.DevSpaces.ExecService.SignalR.ExecSignalRHub,Microsoft.Azure.DevSpaces.ExecService.Client.Streaming.IExecStreamingClient]], Microsoft.Azure.DevSpaces.Common.Logging.ILog, Microsoft.Azure.DevSpaces.ExecService.Services.IConfigDocumentStore, Microsoft.Azure.DevSpaces.Common.Cache.ICacheService, Microsoft.Azure.DevSpaces.Common.IO.IFileSystem, Microsoft.Azure.DevSpaces.ExecService.IExecEnvironmentVariables, Microsoft.Azure.DevSpaces.ExecService.KubeConfigProvider)' on type 'KubernetesExec'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.)",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeCoreAsyncCore>d__51.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeCoreAsync>d__45.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<InvokeCoreAsync>d__34`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecSignalRServerProxy.<_RunAsync>d__25`1.MoveNext()",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\nThrowForNonSuccess\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Runtime.CompilerServices.TaskAwaiter\nVoid ThrowForNonSuccess(System.Threading.Tasks.Task)",
        "HResult": -2146233088,
        "Source": "mscorlib",
        "WatsonBuckets": null
      },
      "HelpURL": null,
      "StackTraceString": "   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecSignalRServerProxy.<_RunAsync>d__25`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<>c__DisplayClass48_1.<<ListAzdsPodsAsync>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecSignalRServiceClient.<RunAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecExceptionStrategy.<>c__DisplayClass3_0.<<RunWithHandlingAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecExceptionStrategy.<RunWithHandlingAsync>d__4`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<ListAzdsPodsAsync>d__48.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<GetAzdsReleaseInnerAsync>d__47.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<GetAzdsReleaseAsync>d__46.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<>c__DisplayClass105_0.<<EnsureDeployReleaseForIterateAsync>b__2>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<EnsureDeployReleaseForIterateAsync>d__105.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.<ExecuteNextIterationAsync>d__99.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Client.DevSpacesServiceClient.<>c__DisplayClass28_0.<<StartDebugAsync>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__2.MoveNext()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nMoveNext\nMicrosoft.Azure.DevSpaces.Client, Version=1.0.3287.787, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\nMicrosoft.Azure.DevSpaces.Client.ServiceClients.ExecSignalRServerProxy+<_RunAsync>d__25`1\nVoid MoveNext()",
      "HResult": -2146233088,
      "Source": "Microsoft.Azure.DevSpaces.Client",
      "WatsonBuckets": null
    },
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": null,
    "WatsonBuckets": null
  },
  "operationName": "RunIterate",
  "stage": "End",
  "elapsedTime": "00:00:01.4166870",
  "completionState": "Error"
}

*Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Azure Dev Spaces
For OSX/Linux: $TMPDIR/Azure Dev Spaces
 
**Environment Details**
Client used (Visual Studio): 16.5.4

Client's version:
Operating System: Windows 10
 
**Additional context**
This had been previously working fine

**Comment by ynambiar** [comment]
@ironicLemon thank you for reporting this issue! We have a fix available and would like to verify it on your controller before deploying everywhere. Please email me (yanambia@microsoft.com) your subscription id and controller name where you're seeing this issue, and I'll try to patch them.

**Comment by ironicLemon** [comment]
That appears to have resolved the issue.

Thanks

**Comment by kenneth-trivec** [comment]
Is there an ETA on when this fix will be deployed? We're currently experiencing the same problems.

**Comment by godraffe** [comment]
Hi, I'm having this same problem too. How do I get this resolved?

**Comment by aplantard** [comment]
Hi, I have the same problem. Is there any way to fix it ?

**Comment by philon-msft** [comment]
Apologies to everyone who ran into this issue. A fix has been rolled out and all controllers have been updated. Please give it a try and let us know if you see any problems.
