### ISSUE TITLE
azds CLI error: An assembly specified in the application dependencies manifest (azds.deps.json) was not found

### ISSUE THREAD

**Issue by dahovey** [Azure/dev-spaces#345]
**Describe the bug**
Cannot run any `azds` CLI commands. Receive error at command prompt:
```
PS C:\Users\davidhovey> azds version
Error:
  An assembly specified in the application dependencies manifest (azds.deps.json) was not found:
    package: 'Microsoft.Azure.Management.AppService.Fluent', version: '1.33.0'
    path: 'lib/netstandard1.4/Microsoft.Azure.Management.AppService.Fluent.dll'
```
 
**To Reproduce**

Just installed version 1.0.4120.7 of `Azure Dev Spaces CLI` for Windows.
![image](https://user-images.githubusercontent.com/22330242/83063893-b20a5380-a015-11ea-86c7-7690b95038b6.png)

**Environment Details**
Client used (CLI/VS Code/Visual Studio): CLI 
Client's version: 1.0.4120.7
Operating System: Windows 10 Version 1909

**Comment by philon-msft** [comment]
Hi @dahovey, sorry to see you've run into this issue. We've seen this happen when the CLI installation gets corrupted. Did you have an older version installed previously? Please try uninstalling the CLI and installing the latest version again.

**Comment by dahovey** [comment]
Yes, I had a previous version installed. Un-installing and re-installing worked. Thanks.
