### ISSUE TITLE
Unable to connect to Azure Dev Spaces.

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#346]
Today I started to receive the following error when trying run my application in debug mode from visual studio or doing azds up:

"Unable to connect to Azure Dev Spaces."
Then it says that it coudn't connecto to IP 40.74.30.146:443
Everything was working fine 2 days ago.
No changes has been made to my local machine or my cluster.

The deployed application is working fine so the k8 is up and runing.
It's a blocking issue for us atm since it stops our development.

**Comment by rakeshvanga** [comment]
Hi @Eneuman , The public ips have been changed for Azure Dev Spaces services and the issue you are seeing is because of the DNS caching of the ip address. Can you clear your DNS cache and try again?
On windows run this command: `ipcondig /flushdns`

**Comment by Eneuman** [comment]
Hi and thanks for your quick reply.
I tried that but without luck.
Do you know the DNS Alias that gets resolved to that IP ?

I could try and query the DNS server itself just to see if it is getting cached somewhere else.

**Comment by rakeshvanga** [comment]
Turns out it is a caching issue on our side. Can you try now?
Also, can you try hitting this endpoint to make sure it is not a caching issue at your end: https://azds-21a57d03-52d0-40b2-ae04-eb2322fbca48.weu.azds.io/api/ping?

You should see an output similar to below:
```
{
  "time": "2020-05-28T19:07:58.4026091Z",
  "connection": "okay",
  "buildVersion": "1.0.20200514.11"
}
```

**Comment by Eneuman** [comment]
It's working now :)
Thanks for the help!
