### ISSUE TITLE
GetServiceStatusAsync Error

### ISSUE THREAD

**Issue by spboyer** [Azure/dev-spaces#35]
azds up fails

.NET Core 2.1 project, EastUS

An unexpected error occurred invoking 'GetServiceStatusAsync' on the server. ExecInternalServerErrorException: Operation returned an invalid status code 'BadRequest'
Service cannot be started.

**Comment by jikuma** [comment]
Thanks @spboyer  for reporting the issue. I am looking into it. Can you share your controller name.

**Comment by spboyer** [comment]
Closing issue, was an issue with the Docker image. error not pushing all the way to the console making it hard to debug with `azds up`. Container image build failed here.

Try do build image locally `docker build -t localdev . -f Dockerfile.develop` to diagnose.
