### ISSUE TITLE
Build target

### ISSUE THREAD

**Issue by adam-page-st** [Azure/dev-spaces#359]
**Is your feature request related to a problem? Please describe.** 
Allow the ability to specify a target for the docker build. If this functionality is enabled I can't find where in the azds.yaml file I should put the desired target nor can I find documentation on it. If this is available a single piece of documentation that has all fields of azds.yaml and a brief description of what they do would be *extremely* helpful (example https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops). My problem is we have a target for debugging, but since it doesn't build the target I specify I can't debug.
 
**Describe the solution you'd like**
azds.yaml:
```
build:
  context: .
  dockerfile: Dockerfile
  target: debug
```
Its possible to put this in the yaml, but it doesn't appear to do anything. 

**Describe alternatives you've considered**
1. Specify a manually created image in the chart. This involves building the image, pushing it, as well as updating the helm chart to point at this image (and then undoing that change before check ins).
2. Multiple dockerfiles or env variables rather than multiple stages. This kinda seems to be just forcing the user to ignore the best practices multi-stage docker builds provide. The dockerfiles generated by VS and other tooling use multi-stage builds, because its a great way to make lean, secure, source code free release images.
 
**Additional context**
When I specify target in the way as described above it builds the final stage.

**Comment by daniv-msft** [comment]
Thank you for your feedback about this. We're adding this to our backlog.
In the meantime, I would suggest using one of the alternatives you mention.
