### ISSUE TITLE
Cannot create dev space in cluster

### ISSUE THREAD

**Issue by BenyErnest** [Azure/dev-spaces#368]
**Describe the bug**
I'm trying to create a dev space in a newly created Kubernetes  cluster but I'm receiving the following error:
"The caller represented by the AzureCredentials passed to the management client does not have proper authorization for this Azure Dev Spaces Controller."
 
**To Reproduce**
Create Kubernetes cluster either by the portal or azure cli
Example:
```
az group create --name MyResourceGroup --location eastus
az aks create -g MyResourceGroup -n MyAKS --location eastus --generate-ssh-keys
az aks use-dev-spaces -g MyResourceGroup -n MyAKS
```
 
**Expected behavior**
Create dev space, instead I get the following error:
```
The caller represented by the AzureCredentials passed to the management client does not have proper authorization for this Azure Dev Spaces Controller.
```
 
**Logs**
[azds-sdk-2020-07-02-17-14-13-5628.txt](https://github.com/Azure/dev-spaces/files/4865839/azds-sdk-2020-07-02-17-14-13-5628.txt)
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
 
Client's version:
Azure Dev Spaces CLI
1.0.20200617.2
API v3.2
Operating System:
 10.0.20161 N/A Build 20161

**Comment by DrEsteban** [comment]
Hey @BenyErnest!

Please check the following section of the docs: https://aka.ms/devspaces/rbac

It seems as if you may not have _Contributor_ or _Owner_ access on the controller resource.  Can you confirm?

**Comment by BenyErnest** [comment]
Hi @DrEsteban!
Thanks for answer me. 
I followed the steps from your suggestion: https://aka.ms/devspaces/rbac, but I can't find, the user that is located in my .kube/config file, in the list of available users to give _Contributor_ or _Owner_ role. Regards!

**Comment by DrEsteban** [comment]
@BenyErnest Your user information likely won't be in your kubeconfig file (unless maybe your cluster is [AAD-enabled](https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli)). The "user" in this case is the account you use to authenticate with Azure. E.g. on the Azure Portal or `az login` on the AzureCLI.

Does that help?

**Comment by BenyErnest** [comment]
Thanks!! @DrEsteban  That solved my problem.
