### ISSUE TITLE
mindaro causes issue with Zookeeper

### ISSUE THREAD

**Issue by AceHack** [Azure/dev-spaces#37]
The init container gets access denied errors when trying to start zookeeper.  Chart is attached, installed with the following command line.

`helm upgrade --install --wait --force --debug -f ./zookeeper/values.yaml -f ./zookeeper/platform-zookeeper.yml platform-zookeeper ./zookeeper`

[zookeeper.zip](https://github.com/Azure/dev-spaces/files/2560066/zookeeper.zip)

**Comment by YuzorMa** [comment]
This has been fixed in the latest release of the tools.
