### ISSUE TITLE
Synchronization Timeout running azds up

### ISSUE THREAD

**Issue by ckapatch** [Azure/dev-spaces#373]
When running the command azds up -v, the command fails with the error message "Timed out waiting for file synchronization to complete"

---
azds up -v 
Using dev space 'dev' with controller 'lukla-dev-cluster'
Synchronizing files...4m 0s
Timed out waiting for file synchronization to complete
 
**To Reproduce**
azds up -v
 
**Logs**
[azds-sdk-2020-07-16-20-35-32-2064.txt](https://github.com/Azure/dev-spaces/files/4934069/azds-sdk-2020-07-16-20-35-32-2064.txt)
[azds-cli-2020-07-16-20-35-32-2064.txt](https://github.com/Azure/dev-spaces/files/4934070/azds-cli-2020-07-16-20-35-32-2064.txt)
 
**Environment Details**
Azure Dev Spaces CLI
1.0.20200710.6
API v3.2

I'm stumped here on what else to try, I've restarted the machine, docker, I have no problem connecting to the cluster with kubectl or other azds commands. I also tried creating another dev space but the same problem arises.

**Comment by rakeshvanga** [comment]
@ckapatch , Can you retry now?
We have pushed fixes that should resolve this issue.
Thanks!

**Comment by ckapatch** [comment]
Thanks @rakeshvanga, I can confirm this is working as intended again.
Thanks for the quick response.

**Comment by ckapatch** [comment]
Hate to the bearer of bad news but a similiar timeout occurs on the azds down command: https://github.com/Azure/dev-spaces/issues/375
