### ISSUE TITLE
Time out attempting to bring down a space with azds down

### ISSUE THREAD

**Issue by ckapatch** [Azure/dev-spaces#375]
**Describe the bug**
azds down -n {space} times out after 1m
 
**To Reproduce**
azds down -n {space}
Timed out after 1m trying to list services.

**Logs**
[azds-sdk-2020-07-17-14-55-16-3808.txt](https://github.com/Azure/dev-spaces/files/4938474/azds-sdk-2020-07-17-14-55-16-3808.txt)
[azds-cli-2020-07-17-14-55-15-3808.txt](https://github.com/Azure/dev-spaces/files/4938475/azds-cli-2020-07-17-14-55-15-3808.txt)

**Environment Details**
Azure Dev Spaces CLI
1.0.20200710.6
API v3.2

**Comment by shpathak-msft** [comment]
@ckapatch Apologies for the inconvenience. Could you please email me your subscription id and region at shpathak@microsoft.com for further investigation?

**Comment by ckapatch** [comment]
After help from @shpa-microsoft we found that a failed azds up helm deployment caused the azds down to fail. The solution is to manually uninstall the helm chart.
