### ISSUE TITLE
DevSpaces fails with node:alpine version for Dockerfile

### ISSUE THREAD

**Issue by jldeen** [Azure/dev-spaces#38]
azds up fails when Dockerfile contains node:alpine image. Upon further investigation, running a kubectl logs check on the pod and container reveals this error: 

> k logs -n dev-space ignite2018-5d4d65c676-pf4vx -c ignite2018 Failed to load , error: Error loading shared library libintl.so.8: No such file or directory (needed by /.azds-agent/alpine/libcoreclr.so)
Failed to bind to CoreCLR at '/.azds-agent/alpine/libcoreclr.so'

If I switch to regular node image for Dockerfile, the azds up command will work.

Using latest version of DevSpaces: 
Azure Dev Spaces CLI (Preview)
0.1.20181023.7

Example Dockerfile to recreate issue can be found [here](https://raw.githubusercontent.com/jldeen/ignite2018/jenkins/Dockerfile).

**Comment by xinyanmsft** [comment]
thanks for reporting this issue. the fix for this will be in the next update.
in the mean time, use the "node" base image to work around this issue.

**Comment by YuzorMa** [comment]
This should be fixed in the latest versions of Dev Spaces.  Please let us know if you continue to see issues.
