### ISSUE TITLE
Visual Studio Azure Dev Spaces

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Azure/dev-spaces#389]
Not too long ago we were able to select "Azure Dev Spaces" to start debugging. Recently this option has disappeared from our IDEs. Even after running azds prep and azds up manually we are still not able to find the capability to Debug using Azure Dev Spaces in Visual studio.

If we create an entry into the launchSettings.json (as below) the Azure Dev Spaces option is available to debug however we get an error stating.

"The project doesnt know how to run the profile Azure Dev Spaces"

```
"Azure Dev Spaces": {
      "commandName": "AzureDevSpaces",
      "launchBrowser": true,
      "resourceGroup": "<redacted>",
      "aksName": "<redacted>",
      "subscriptionId": "<redacted>"
    }
```
 
To reproduce this I created a new Solution with a new  dotnet core 3.1 Web Application and ran azds prep. Next I had to manually modify the launchSettings.json file.

**Expected behavior**
As advertised we should be able to debug the projects in Azure Dev Spaces.
 
**Environment Details**
Visual Studio 2019 Enterprise version 16.7.2
Multi project solutions \ single project solutions
dotnet core application using the dotnet core 3.1.7 framework
Windows 10 Enterprise

**Comment by ghostcoach** [comment]
We also have had this problem occur for us when upgrading to 16.7.1 and the problem persist with the 16.7.2 Visual Studio update. 
The project no longer know how to run the profile and the Azure Dev Spaces alternative is not longer available for new profiles.

**Comment by Eneuman** [comment]
I have managed go get around this by doing the following:
in your project .cs file, make sure theese packages are included:

```
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets" Version="1.1.0" />
```

open your "launchSettings.json" file (its in the "Properties" folder) and change 
```
"Azure Dev Spaces": {
...
    }
```

to
```
"Container in Kubernetes": {
...
    }
```

When you select "Container in Kubernetes" from start debugging, you should now get the option to select your k8 cluster.
Unfortently it seems to be a problem with listning Dev Spaces atm. Gonna place a issue about this now.

**Comment by ghostcoach** [comment]
Thanks Eneuman for your reply! Our original profile works without the rename to "Container in Kubernetes" after installing the nuget packages you mention.

**Comment by Nico-VanHaaster** [comment]
@Eneuman thank you for the comment. I can confirm that from a blank solution to get DevSpaces working needed to add those packages (although `Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets` has a dependency on `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` so really only need one). This worked for the blank project and just now trying to replicate this to our larger solutions.

Also adding Container Orchestration and selecting Kubernetes \ Helm will also add that package and enable the "Container in Kubernetes" options.

**Comment by sanar-microsoft** [comment]
Adding container orchestrator support to your project should fix the issue (https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2019#kubernetes-support)

![image](https://user-images.githubusercontent.com/14197477/90697139-98526400-e232-11ea-8433-c695cf24cb34.png)

**Comment by BommagantiKrishnaPrasad** [comment]
I am seeing similar issue in VSCode. Can some one guide me how to fix this issue in VSCode?

**Comment by daniv-msft** [comment]
@BommagantiKrishnaPrasad Could you please create a new issue for what you see in VS Code? The Visual Studio problem mentioned here was specific to Visual Studio, and I expect that your issue isn't the same as the one mentioned above.
