### ISSUE TITLE
Unable to create azure devspace controller

### ISSUE THREAD

**Issue by kenneth-trivec** [Azure/dev-spaces#390]
**Describe the bug**
When trying to create the azure devspace controller with az aks use-dev-spaces -g resourcegroup -n clusterName it crashes with an unexpected error
 
**To Reproduce**
Create azure dev spaces controller with az aks use-dev-spaces -g resourcegroup -n clusterName

**Logs**
[azds-sdk-2020-08-19-08-47-49-10424.txt](https://github.com/Azure/dev-spaces/files/5095349/azds-sdk-2020-08-19-08-47-49-10424.txt)

**Comment by ahaeber** [comment]
We're getting a very similar error as well (AKS cluster is in westeurope region).

First, azds failed to select space. It failed with a 503 Service Unavailable to the dataplane FQDN. Looking at some old github issues we saw a bit of hope by re-creating azds for the cluster. But now we're also stuck with this command failing, and the controller ends up in 'failed' state.

We tried to stop and scale down other deployments to ensure all nodes have less than 80% memory usage.

Once while enabling azds after it has created the 'azds' namespace in the cluster and the pods started running we looked at logs for the pods. Interestingly the logs for azds-webhook-deployment pods look like this:
```
azdslogger: main.go:459: Getting standard service principal token                                                                                                                              
                                                                                                                                                                                               
azdslogger: main.go:499: Acquired token was saved in '/root/.adal/accessToken.json' file                                                                                                       
                                                                                                                                                                                               
azdslogger: main.go:113: Running webhook service using port  5050                                                                                                                              
                                                                                                                                                                                               
azdslogger: main.go:133: Error flushing logs:  503 Service Unavailable      
```

**Comment by kenneth-trivec** [comment]
> We're getting a very similar error as well (AKS cluster is in westeurope region).
> 
> First, azds failed to select space. It failed with a 503 Service Unavailable to the dataplane FQDN. Looking at some old github issues we saw a bit of hope by re-creating azds for the cluster. But now we're also stuck with this command failing, and the controller ends up in 'failed' state.
> 
> We tried to stop and scale down other deployments to ensure all nodes have less than 80% memory usage.
> 
> Once while enabling azds after it has created the 'azds' namespace in the cluster and the pods started running we looked at logs for the pods. Interestingly the logs for azds-webhook-deployment pods look like this:
> 
> ```
> azdslogger: main.go:459: Getting standard service principal token                                                                                                                              
>                                                                                                                                                                                                
> azdslogger: main.go:499: Acquired token was saved in '/root/.adal/accessToken.json' file                                                                                                       
>                                                                                                                                                                                                
> azdslogger: main.go:113: Running webhook service using port  5050                                                                                                                              
>                                                                                                                                                                                                
> azdslogger: main.go:133: Error flushing logs:  503 Service Unavailable      
> ```

That's the exact same reason we tried re-creating the controller, azds space select started returning a 503. Hopefully this can be resolved because it's blocking our development workflows.

**Comment by sanar-microsoft** [comment]
@kenneth-trivec @ahaeber West Europe region is currently facing a resource limit issue right now. We are working on fixing it.

**Comment by sanar-microsoft** [comment]
@kenneth-trivec @ahaeber The issue has been fixed now, please let us know if you are still facing this problem. Thanks for reporting it!

**Comment by ahaeber** [comment]
@sanar-microsoft Thanks for quickly resolving this. I managed to create a new azds controller again :-) Would it be possible to notice this issue from e.g., Azure Service Health, https://status.azure.com/en-us/status or other location? That would help us in the future to avoid wasting our time on something that is not working.

Unfortunately, `azds space select` still fails for our cluster. The log says that it fails to connect to Azure, which is weird since I just created the controller. Could it be a problem with my azds settings (~/.azds/settings.json) or other config?

[azds-cli-2020-08-19-18-30-16-522644.txt](https://github.com/Azure/dev-spaces/files/5098595/azds-cli-2020-08-19-18-30-16-522644.txt)

**Comment by sanar-microsoft** [comment]
@ahaeber  From the logs it looks like the domain could not be resolved while contacting Azure: `No such device or address`
Can you try clearing local DNS cache using `ipconfig /flushdns` ?

Regarding the resource limit issue, that issue unfortunately doesn't show up on Azure Service Health. It is something we hit due to a resource planning problem on our end that only affected new resources, so every existing service/resource still reported healthy.

**Comment by kenneth-trivec** [comment]
> @kenneth-trivec @ahaeber The issue has been fixed now, please let us know if you are still facing this problem. Thanks for reporting it!

Thank you for keeping us up-to-date, the issue has been resolved for us.

**Comment by ahaeber** [comment]
> @ahaeber From the logs it looks like the domain could not be resolved while contacting Azure: `No such device or address`
> Can you try clearing local DNS cache using `ipconfig /flushdns` ?

Thanks, it works fine when testing today.
