### ISSUE TITLE
Unable to connect to Azure Dev Spaces

### ISSUE THREAD

**Issue by BommagantiKrishnaPrasad** [Azure/dev-spaces#396]
When I run the command "az aks use-dev-spaces -g myResourceGroup -n myAKSCluster", I am getting below error.
**Selecting Azure Dev Spaces Controller 'xxxxxx' in resource group 'xxxxxx' that targets resource 'xxxxxx' in resource group 'xxxxxx'...7s
Unable to connect to Azure Dev Spaces. Please check your network connection: No such host is known**

It used to work previously without any issues. I see this issue popping up today.

Can someone suggest the solution for this?

**Comment by BommagantiKrishnaPrasad** [comment]
Also when trying to add a dev space from VS2019, I can see the same error message

![image](https://user-images.githubusercontent.com/30042311/91858073-568bd980-ec86-11ea-89d9-fa9d5495a8ad.png)

**Comment by amsoedal** [comment]
Hi @BommagantiKrishnaPrasad, what do you see when you run "azds controller list"? Is the controller in succeeded or failed state?

**Comment by BommagantiKrishnaPrasad** [comment]
Hi @amsoedal, I see controller in succeeded state as shown below

![image](https://user-images.githubusercontent.com/30042311/91909909-ab057800-eccb-11ea-8169-fb82719c4a89.png)

**Comment by amsoedal** [comment]
@BommagantiKrishnaPrasad that's interesting... what do you see when you run "az aks list"? Is the cluster listed there? If so, can you run a kubeclt command against it (e.g. "kubectl get po")?

**Comment by BommagantiKrishnaPrasad** [comment]
@amsoedal I have run the command "az aks list" and cluster is listed there(attached the file in json format). Also when I apply kubectl command, I can see the list. For example, when I run 'kubectl get namespaces', I can see all the namespaces in the cluster
[az-aks-list.txt](https://github.com/Azure/dev-spaces/files/5159459/az-aks-list.txt)

**Comment by BommagantiKrishnaPrasad** [comment]
Thanks @amsoedal, issue got resolved after flushing the local dns entries. I think  it is better to add this point in the documentation under Troubleshoot section.

**Comment by amsoedal** [comment]
Glad to hear the issue got resolved!
