### ISSUE TITLE
DNS records does not get created automatically

### ISSUE THREAD

**Issue by guybartal** [Azure/dev-spaces#40]
I've followed this [quickstart ](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vs-tools-for-kubernetes#overview) and added Kubernetes/Helm support to my aspnet core project,
hit F5 in Visual Studio on Azure Dev Spaces but no DNS records got created.

![image](https://user-images.githubusercontent.com/3179107/48832024-dd591600-ed80-11e8-87d6-9ce4eb611b73.png)

![image](https://user-images.githubusercontent.com/3179107/48832005-cfa39080-ed80-11e8-9483-17bab7bbc304.png)

**Comment by philon-msft** [comment]
This could be caused by the DNS or ingress pods in your cluster getting into a bad state. Please try recreating them with the steps in our troubleshooting doc and let us know if that helps: https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#dns-name-resolution-fails-for-a-public-url-associated-with-a-dev-spaces-service

**Comment by guybartal** [comment]
I've tried to delete those pods and run dev spaces in debug from visual studio again but still I don't get any DNS records.

> kubectl delete pod -n kube-system -l app=addon-http-application-routing-external-dns
> pod "addon-http-application-routing-external-dns-68b7f5bc6b-kqk97" deleted
> 
> kubectl delete pod -n kube-system -l app=addon-http-application-routing-nginx-ingress
> pod "addon-http-application-routing-nginx-ingress-controller-7bhbsxj" deleted
> 
> kubectl get pods -n kube-system
> NAME                                                              READY     STATUS    RESTARTS   AGE
> addon-http-application-routing-default-http-backend-5f9f55v8cvv   1/1       Running   0          6d
> addon-http-application-routing-external-dns-68b7f5bc6b-mcdhs      1/1       Running   0          36m
> addon-http-application-routing-nginx-ingress-controller-7b5hx62   1/1       Running   0          36m
> heapster-6cd7d5cd54-6kbxc                                         2/2       Running   0          6d
> kube-dns-v20-687545ccc-6sbv5                                      3/3       Running   0          8d
> kube-dns-v20-687545ccc-pzrlp                                      3/3       Running   0          8d
> kube-proxy-qs8p2                                                  1/1       Running   0          6d
> kube-proxy-t9dbd                                                  1/1       Running   0          6d
> kube-proxy-xv8jg                                                  1/1       Running   0          6d
> kube-svc-redirect-854h7                                           2/2       Running   0          8d
> kube-svc-redirect-l6gw4                                           2/2       Running   0          8d
> kube-svc-redirect-tg59r                                           2/2       Running   0          8d
> kubernetes-dashboard-bfd84bcdb-slqwp                              1/1       Running   0          8d
> metrics-server-5778d48cb6-rr2wl                                   1/1       Running   0          6d
> omsagent-rs-6d868564b6-b4zw9                                      1/1       Running   0          8d
> tunnelfront-5cb6bd6c7f-vq5d5                                      1/1       Running   0          17d
> 
> kubectl logs addon-http-application-routing-external-dns-68b7f5bc6b-mcdhs -n kube-system
> time="2018-11-22T14:00:29Z" level=info msg="config: &{Master: KubeConfig: Sources:[service ingress] Namespace: AnnotationFilter:kubernetes.io/ingress.class=addon-http-application-routing FQDNTemplate: Compatibility: PublishInternal:false Provider:azure GoogleProject: DomainFilter:[baec790dc6f148b39f8d.westeurope.aksapp.io] AWSZoneType: AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup:MC_kubernetes-test-rg_Kubernetes-Test_westeurope CloudflareProxied:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InMemoryZones:[] Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:3m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:info}"
> time="2018-11-22T14:00:29Z" level=info msg="Connected to cluster at https://kubernetestest-e782de42.hcp.westeurope.azmk8s.io:443"
> 
> azds list-uris
> Uri                                                       Status
> --------------------------------------------------------  --------
> http://localhost:57842 => gimmonixpixel.project-pixel:80  Tunneled

**Comment by lisaguthrie** [comment]
Can you validate that ingress is enabled in the values.yaml file? (Underneath `charts\<project name>`)

> ingress:
>   **enabled: true**
>   annotations:
>     kubernetes.io/ingress.class: addon-http-application-routing

**Comment by YuzorMa** [comment]
We have changed the way we create DNS records for public services.  Please reactivate if you continue to see issues.
