### ISSUE TITLE
azds up hangs on Waiting for container image build...

### ISSUE THREAD

**Issue by BirkoffHimura** [Azure/dev-spaces#406]
**Describe the bug**
After upgrading the cluster to version 1.17.9 and enabling RBAC on the cluster azure devspaces stopped working, when doing the azds up command the console just stays on "waiting for container image build...".
 
**To Reproduce**
trying to deploy any workload with azds, this is the current setup:
Azure Dev Spaces CLI
1.0.20200827.4
API v3.2

----------------------------
Kubernetes version: 1.17.9
RBAC: enabled
AKS-managed Azure Active Directory: enabled
Resource Location: East US

 
**Expected behavior**
 
**Logs**
[azds-sdk-2020-09-21-13-42-09-28560.txt](https://github.com/Azure/dev-spaces/files/5259010/azds-sdk-2020-09-21-13-42-09-28560.txt)
[azds-sdk-2020-09-21-13-44-09-19728.txt](https://github.com/Azure/dev-spaces/files/5259013/azds-sdk-2020-09-21-13-44-09-19728.txt)
[azds-sdk-2020-09-22-01-49-21-31892.txt](https://github.com/Azure/dev-spaces/files/5259015/azds-sdk-2020-09-22-01-49-21-31892.txt)

 
[kubectl describe pod.txt](https://github.com/Azure/dev-spaces/files/5258978/kubectl.describe.pod.txt)

**Environment Details**
Client used (CLI/VS Code/Visual Studio):
 
Client's version:
Operating System:
 
**Additional context**
Based on the pod information when doing kubectl describe pod I see the following issues(this log is also attached):
  Normal   Scheduled  <unknown>          default-scheduler                         Successfully assigned devspace/backend-service-5d44cc9cb-nv528 to aks-uatnd01-28152486-vmss000033
  Normal   BackOff    19s (x2 over 20s)  kubelet, aks-uatnd01-28152486-vmss000033  Back-off pulling image "mainacr.azurecr.io/dev/backend-service:devspaces-x0174b3840b749c9e"
  Warning  Failed     19s (x2 over 20s)  kubelet, aks-uatnd01-28152486-vmss000033  Error: ImagePullBackOff
  Normal   Pulling    9s (x2 over 21s)   kubelet, aks-uatnd01-28152486-vmss000033  Pulling image "mainacr.azurecr.io/dev/backend-service:devspaces-x0174b3840b749c9e"
  Warning  Failed     8s (x2 over 20s)   kubelet, aks-uatnd01-28152486-vmss000033  Failed to pull image "mainacr.azurecr.io/dev/backend-service:devspaces-x0174b3840b749c9e": [rpc error: code = Unknown desc = Error response from daemon: manifest for mainacr.azurecr.io/dev/backend-service:devspaces-x0174b3840b749c9e not found: manifest unknown: manifest tagged by "devspaces-x0174b3840b749c9e" is not found, rpc error: code = Unknown desc = Error response from daemon: Get https://mainacr.azurecr.io/v2/dev/backend-service/manifests/devspaces-x0174b3840b749c9e: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]
  Warning  Failed     8s (x2 over 20s)   kubelet, aks-uatnd01-28152486-vmss000033  Error: ErrImagePull

**Comment by philon-msft** [comment]
Hi @BirkoffHimura , it looks like your cluster doesn't have permissions to pull images from the mainacr.azurecr.io ACR. Dev Spaces builds the project in the cluster rather than on your development workstation, so you'll need to configure the necessary permissions. See this article for more info: https://docs.microsoft.com/azure/container-registry/container-registry-auth-kubernetes

Or for a simpler experience where you don't need to build code in the cluster, check out our new Bridge to Kubernetes tools (https://devblogs.microsoft.com/visualstudio/bridge-to-kubernetes-ga) as an alternative to Dev Spaces

**Comment by BirkoffHimura** [comment]
@philon-msft I already tried with image pull secret, the acr is also attached to the cluster so I can deploy images from that acr to it. we had this working fine until we updated the version, today we just updated again AKS to version 1.18.8 and still the same. 

Also about the new Bridge to Kubernetes we haven't had any luck with that either, if we can get any of the options working that'd be perfect for us.

**Comment by philon-msft** [comment]
@BirkoffHimura , could you open a new issue on https://github.com/microsoft/mindaro/issues for the problem you're seeing with Bridge to Kubernetes? That route probably has a better chance of success than Dev Spaces.

**Comment by pragyamehta** [comment]
Hi @BirkoffHimura  Thanks for reaching out to us! Bridge to Kubernetes is definitely a more light-weight solution and I would highly recommend giving that a try! We would love to help you out in case you are facing any issues with it. Please open a new issue at the link @philon-msft suggested, and we can take a look. Thanks!

**Comment by BirkoffHimura** [comment]
Thank you very much, I will do so
