### ISSUE TITLE
Specify main file for Nodemon

### ISSUE THREAD

**Issue by khawaga** [Azure/dev-spaces#41]
I currently have a Node.js application where the main file is not `server.js` but actually resides at bin/www, I can change the file name in `launch.json` for the `Launch Server (AZDS)` config, however how do I change that for it to work with nodemon in the `Attach to Server (AZDS)` config?
I can see it still defaults to `server.js` even after setting the main file in `package.json`.

**Comment by stepro** [comment]
Take a look in the tasks.json file for the attach task. You should see the nodemon command there with the `server.js` file that you can change to `bin/www`.

**Comment by khawaga** [comment]
Thank you so much.
