### ISSUE TITLE
Dev Space Controller Keeps Failing

### ISSUE THREAD

**Issue by ckapatch** [Azure/dev-spaces#411]
**Describe the bug**
I have had no issues for the past couple months with Azure Dev Spaces but today my controller wasn't working and reported that the ProvisioningState was failed. I recreated the controller and after about an hour it also failed. I have repeated this 3 times now with the same result.

What else can I do to debug this issue?
 
**To Reproduce**
Create controller: azds controller create --name {name} --target-name {cluster} --resource-group {group}
 
**Environment Details**
Azure Dev Spaces CLI
1.0.20200921.3
API v3.2

**Comment by shpathak-msft** [comment]
@ckapatch Sorry that you are running into this issue. Could you please email me your subscription id and region at shpathak@microsoft.com to investigate further?
