### ISSUE TITLE
Dev Spaces Controller in "Failed" State

### ISSUE THREAD

**Issue by ajaffie** [Azure/dev-spaces#415]
**Describe the bug**
Yesterday our dev spaces controller which had been stable for a while seems to have died. `azds` commands result with "Network connection failed. Please reselect your controller and try running the command again." and then `az aks use-dev-spaces -g Dev -n DevTest -s dev -y` results with:
> The behavior of this command has been altered by the following extension: dev-spaces
> Selecting Azure Dev Spaces Controller 'DevTest' in resource group 'Dev' that targets resource 'DevTest' in resource group 'Dev'...Cannot get connection details for Azure Dev Spaces Controller 'DevTest' because it is in the 'Failed' state. Please remove the controller and try again.

This was fixed after disabling dev spaces in Azure portal (or with `azds remove`), deleting all related namespaces, re-enabling dev spaces and re-deploying all services.
This isn't ideal because it disrupts the entire team during this process, and we use an nginx container configured as a local https-terminating proxy that everyone needs to reconfigure as well.

The issue is that it happened again today, which makes it seem like something has gone wrong.
 
**To Reproduce**
Have cluster with dev spaces enabled.

**Comment by daniv-msft** [comment]
Thank you for reporting this issue and sorry you encountered it.

We have seen a couple of failures across regions, but from what we see they should be resolved now.
Do you still see an issue with your Dev Spaces controller?

Also, the code behind Dev Spaces is quite complex and not fully reliable, which is one of the reasons why we announced its retirement and created a new product to replace it. Did you have a chance to give a try to Bridge to Kubernetes, its successor?
Bridge doesn't require a controller, and at this point our whole engineering team is focused on it so it will be far easier to assist you/help you transition there.

**Comment by ajaffie** [comment]
We haven't really had time to assess if our workflow maps to Bridge. I'll probably open an issue on the mindaro repo at some point in the future for assistance.
For now though, the controller hasn't failed yet since I re-enabled it earlier today so I will report back here if it happens again. Thank you!

**Comment by daniv-msft** [comment]
Thanks for your reply! Yes, please don't hesitate to let us know if you encounter new issues with your controller, and if you need any help transitioning to Bridge to Kubernetes.
