### ISSUE TITLE
This version of Kubernetes is no longer supported. Please upgrade your cluster to a supported Kubernetes version and retry.

### ISSUE THREAD

**Issue by ciacco85** [Azure/dev-spaces#416]
Since today, yesterday was working without problem, this message is shown 

This version of Kubernetes is no longer supported. Please upgrade your cluster to a supported Kubernetes version and retry.

I've the latest version of kubernetes (1.19.3) and 3 node:
1 with 1.18.10 version
2 with 1.19.3 version

I'm using 1.18.10 node version for azds due to containerd upgrade in 1.19.3 since socket to call to dockers aren't available anymore. I've achieved this with nodeSelector in the azds.yaml.
I've obviously tried the other 1.19.3 nodes, without success and with the same error.

I've upgraded the azds version with
`az aks use-dev-spaces -n *** -g *** --update`

I've upgraded the azure CLI (but this warning was shown "No updates available for 'dev-spaces'. Use --debug for more information.")
My azds version is
`1.0.20200921.3`

My development is completely stopped due to lack of functionality of Bridge to Kubernetes like Visual Studio solution not supported, as stated in this issue
https://github.com/microsoft/mindaro/issues/84

**Comment by ciacco85** [comment]
I've downloaded the latest exe for dev space cli and it seems the process is killed right after started!

**Comment by amsoedal** [comment]
Hi @ciacco85, sorry you're running into this issue. If you've applied a nodeselector I think that *should* work. Let me log a bug for our team to investigate and get back to you.

**Comment by ciacco85** [comment]
nodeselector has has worked fine until today!
Maybe the problem is more on the Azure Dev Space CLI upgrade than in kubernetes version and node selection

**Comment by rakeshvanga** [comment]
@ciacco85 Are you blocked with using Azure Dev Spaces when you see the error: `This version of Kubernetes is no longer supported. Please upgrade your cluster to a supported Kubernetes version and retry.`
Can you share in what operation are you seeing this error message? Apart from the CLI install issue I'm trying to understand if there are any other issues that is stopping you from using Azure Dev Spaces.

**Comment by rakeshvanga** [comment]
@ciacco85 I've investigated the issue. No need for additional details from you. We are working on fixing the issue.

**Comment by daniv-msft** [comment]
We deployed a new version that should unblock you. Could you please validate this fix on your side?
Also, could you please let us know if the solution provided in the [other issue](https://github.com/microsoft/mindaro/issues/84) to debug multiple services at the same time in Bridge to Kubernetes works for you?

**Comment by ciacco85** [comment]
After a lot of headache, multiple service debug with bridge to kubernetes is working fine
I'm installing the new release of CLI right now and, at least, the setup has completed successfully. 
Honestly, thanks for your support, but since dev spaces is deprecated, now we'll put our effort on bridge to kubernetes since it's working.
I'll try to give you feedback on dev space asap, I'm not the kind of developer that find a solution for the problem and forget about issues and all work behind this amazing tool, but our priority are obviously project's progress and deadline.

**Comment by daniv-msft** [comment]
Thank you for your reply, and sorry transitioning was more complicated than we would have liked.
No pressure at all to reply on this issue: your deadlines are far more important than replying and, as you mention, Dev Spaces is being retired now.

I'm closing this issue for now, but please let us know if we can help you in the future!
