### ISSUE TITLE
RoutingManager fails with Null ref in AddLoadBalancerTriggersAsync'

### ISSUE THREAD

**Issue by catnip-se** [Azure/dev-spaces#419]
Routing manager throws exception 'Null ref in AddLoadBalancerTriggersAsync' and Visual studio fails to connect displaying message

![image](https://user-images.githubusercontent.com/72073559/103347247-beb4c580-4a96-11eb-9cc9-bbbb408f93ba.png)
[routingmanager.log](https://github.com/Azure/dev-spaces/files/5753973/routingmanager.log)
[bridge-library-2020-12-30-10-59-35-26868.txt](https://github.com/Azure/dev-spaces/files/5753979/bridge-library-2020-12-30-10-59-35-26868.txt)

Visual Studio 16.8.3
Bridge to kubernetes extension version: 2.0.20201216.1

Kubernetes version:
Client: 1.19.3
Server: 1.19.3

**Comment by amsoedal** [comment]
Thanks so much for reporting this @catnip-se! We'll investigate and let you know as soon as the fix is available.

**Comment by catnip-se** [comment]
Some more information.
I have tested on a different cluster (without any ingresses) and even though no exception is thrown in the RoutingManager there the problem with getting the routing manager deployment status from Visual Studio remains.

**Comment by amsoedal** [comment]
@catnip-se, can you attach the routing manager log for the second issue you're seeing?

**Comment by catnip-se** [comment]
Sure, here it is.
[routingmanager.log](https://github.com/Azure/dev-spaces/files/5770874/routingmanager.log)
[bridge-library-2021-01-05-14-49-58-22788.txt](https://github.com/Azure/dev-spaces/files/5770911/bridge-library-2021-01-05-14-49-58-22788.txt)

In  this case it seems to be some timeout problem in VS. If I made a second attempt to connect from VS after the routing manager had completed the startup it was possible to start the debugging pods in this cluster.

**Comment by pragyamehta** [comment]
Hi @catnip-se According to the logs you sent last, It seems as though the envoy pods we start in your cluster for debugging were not able to come up in time. This could be something intermittent with your kube-api, but if you see this consistently, please check if you have enough space on your cluster to spin up these additional pods for setting up debugging. Thanks!

As for the nullref you are seeing, we have fixed it. It will be rolled sometime next week to production. 
Thanks for reporting these issues and do let us know if you see more in the future. Cheers!

**Comment by ghostcoach** [comment]
@pragyamehta Do you have an ETA on the fix for the nullref error? Looking forward to this fix :)

**Comment by pragyamehta** [comment]
Hi @ghostcoach We are releasing the fix tomorrow. Thanks for your patience :)
