### ISSUE TITLE
Failed to get deployment status when enable routing isolation

### ISSUE THREAD

**Issue by ghostcoach** [Azure/dev-spaces#420]
When trying to debug using routing isolation it fails with error message "Failed to get deployment status". When this is disabled debugging using Bridge to Kubernetes works
 
To Reproduce
I followed [this guide](https://docs.microsoft.com/sv-se/visualstudio/containers/bridge-to-kubernetes?view=vs-2019#connect-to-your-cluster-and-debug-a-service) to create a test k8s-cluster and used the same application as in the example. 
 
Logs
[bridge-mindarocli-2021-01-13-11-05-38-20264.txt](https://github.com/Azure/dev-spaces/files/5808219/bridge-mindarocli-2021-01-13-11-05-38-20264.txt)
[bridge-library-2021-01-13-11-05-39-20264.txt](https://github.com/Azure/dev-spaces/files/5808234/bridge-library-2021-01-13-11-05-39-20264.txt)
[routingmanager.txt](https://github.com/Azure/dev-spaces/files/5808257/routingmanager.txt)

Environment
Visual Studio: 16.8.4
Bridge to Kubernetes Extension: 2.0.20201216.1
Kubernetes Client Version: v1.20.0
Kubernetes Server Version: v1.19.3

**Comment by ghostcoach** [comment]
I realized that this issue should be raised in the https://github.com/microsoft/mindaro github and that there is a [similiar issue there ](https://github.com/microsoft/mindaro/issues/103).

Closing the issue to avoid duplicates.

**Comment by pragyamehta** [comment]
Hi @ghostcoach it seems you are using an old version of the extension. Could you update your extension to the version v1.0.120210113 and try again? Let me know if you face issues

**Comment by ghostcoach** [comment]
Thanks for the information @pragyamehta. I can't see the latest version of the extension in Visual Studio or [on this page](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.mindaro). I guess I am missing something? 

![bild](https://user-images.githubusercontent.com/63369949/104514614-d4c39980-55f1-11eb-9925-3e2e0f367a02.png)
![bild](https://user-images.githubusercontent.com/63369949/104514644-e0af5b80-55f1-11eb-9ef4-84bf2ec26aa0.png)

**Comment by pragyamehta** [comment]
I apologize, I thought you were on VSCode. The fix for this on VS would be released sometime this month. In order to get unblocked, you can try our latest extension on VSCode. Thanks!
