### ISSUE TITLE
How do I delete/disable dev spaces?

### ISSUE THREAD

**Issue by AceHack** [Azure/dev-spaces#44]
I would like to also delete any azure resources it created.

**Comment by stepro** [comment]
Option 1: `az aks remove-dev-spaces -g <aks resource group> -n <aks resource name>`
Option 2: go to the portal and delete the dev spaces resource.

**Comment by YuzorMa** [comment]
@AceHack Were you able to successfully delete Dev Spaces?  Please let us know if the steps @stepro  provided did not work.

**Comment by AceHack** [comment]
yes
