### ISSUE TITLE
Install Support for Visual Studio 2019

### ISSUE THREAD

**Issue by evaneenwyk** [Azure/dev-spaces#46]
Tried to install the dev-spaces extension on a computer with only Visual Studio 2019 and it was blocked.

**Comment by mthalman-msft** [comment]
The extension on the Visual Studio Marketplace is only intended for VS 2017.  Going forward, releases of VS 2019 will have the extension "in-the-box" and available to install as part of the VS setup process.

**Comment by YuzorMa** [comment]
The latest preview of Visual Studio 2019 now has support for Azure Dev Spaces "in-the-box".
