### ISSUE TITLE
Use Github releases or a changelog

### ISSUE THREAD

**Issue by giggio** [Azure/dev-spaces#47]
I just got a new release of Visual Studio Tools for Kubernetes but I don't know what's new. Please use some tool to communicate to us what is changing.

**Comment by lisaguthrie** [comment]
Thanks for the feedback. We're exploring some ways to better communicate this information to our users.

**Comment by YuzorMa** [comment]
Release notes can now be found at https://github.com/Azure/dev-spaces/releases
