### ISSUE TITLE
Managing the cluster with dev spaces

### ISSUE THREAD

**Issue by teebszet** [Azure/dev-spaces#49]
Apologies for the vague issue.

Is there any way to use dev spaces without using the `azds prep && azds up` command under each individual application? 

I can't figure out a way to be able to use dev spaces to deploy one application under multiple configurations to the same cluster, as `azds prep` seems to create one helm chart by default.

Consider that I want to take advantage of dev spaces' cross container debugging, but keep a declarative definition of all my services and deployments in one kube config file. Is this possible with the current release, or am I missing the point?

**Comment by lisaguthrie** [comment]
You can deploy services to the cluster however you want. `azds up` of course, but also a direct `helm install`, CI/CD pipeline, etc.

To give an example, suppose you have an application that consists of services A, B, C, D, and E. You are actively working on service A. You have configured the `default` namespace on your cluster as a dev space (e.g. `azds space select -n default`, or select `default` from the space drop-down in Visual Studio)

What you can do is deploy all five services to `default` through, say, a CI/CD pipeline. This is completely outside of Dev Spaces. You'll need to come up with an appropriate build/release definition, or kube config, or Helm chart, or whatever mechanism you want to use to deploy -- Dev Spaces is not opinionated on this, as long as all the services end up running in that `default` namespace.

Once you have this baseline in place, you can `azds up` service A into a child space of `default`, and debug and take advantage of all Dev Spaces functionality.

Hopefully that makes sense. Let me know if you think that will work for your scenario, or if you have additional questions. We are actually working on some documentation right now that goes into detail about how to set up the exact configuration I've described, so your feedback is timely!

**Comment by teebszet** [comment]
Great, thanks for the response. Good to know it's possible before I plough on through.
