### ISSUE TITLE
Error creating AZDS Controller

### ISSUE THREAD

**Issue by aaronwjha** [Azure/dev-spaces#5]
I'm not sure how to troubleshoot this issue. I have tried 2 times with different AKS clusters with the same results. 

"Failed to create Azure Dev Spaces Controller 'MyAKS' in resource group 'AzureDevSpaces' in subscription 'd942ee4d-6452-47ff-afa6-99635a311dd8'.
Please include the following Request ID when contacting support: 61f3f2a4-d622-49ff-bade-27b064aa7b80"

ads controller list gives me:
Azure Dev Spaces Controllers in subscription 'd942ee4d-6452-47ff-afa6-99635a311dd8':
*  Name   ResourceGroup   Location  ProvisioningState
-  -----  --------------  --------  -----------------
   MyAKS  AzureDevSpaces  eastus    Failed

**Comment by lisaguthrie** [comment]
Does your AKS cluster have RBAC enabled? If so, please try creating the controller again. We recently rolled out a new version of the service that allows you to create a controller against an RBAC-enabled AKS cluster.

**Comment by wwaidelich** [comment]
Error and failed state:

```
az aks use-dev-spaces -g test-rg -n test-k8s

The installed extension 'dev-spaces-preview' is in preview.
Installing Dev Spaces (Preview) commands...
A separate window will open to guide you through the installation process.
An Azure Dev Spaces Controller will be created that targets resource 'test-k8s' in resource group 'test-rg'. Continue? (y/N): y

Creating and selecting Azure Dev Spaces Controller test-k8s' in resource group 'test-rg' that targets resource 'test-k8s' in resource group 'test-rg'...19m 43s

Failed to create Azure Dev Spaces Controller 'test-k8s' in resource group 'test-rg' in subscription '6f07da80-69be-40a6...'.
Please include the following Request ID when contacting support: b7848aa7-b979-4992-8421-b2e1c818d186

az aks use-dev-spaces -g test-rg -n test-k8s
Selecting Azure Dev Spaces Controller 'test-k8s' in resource group 'test-rg' that targets resource 'test-k8s' in resource group 'test-rg'...<1s

Cannot get connection details for Azure Dev Spaces Controller 'test-k8s' while it is in 'Failed' state.
```

Can I reset/delete the controller to set it up again?

**Comment by philon-msft** [comment]
Yes, you can use this command to remove the failed controller from your AKS cluster before retrying: 

`az aks remove-dev-spaces -g test-rg -n test-k8s`

**Comment by wwaidelich** [comment]
Thank you!
