### ISSUE TITLE
[Linux] Error while removing or creating the Azure Dev Spaces Controller

### ISSUE THREAD

**Issue by ferantivero** [Azure/dev-spaces#50]
issue and proposal for Troubleshooting page: while creating or removing the controller from linux I'm facing the following err. Running with sudo made the trick

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.DevSpaces.Common.Logging.FileLogger.<.ctor>b__6_0(Object state) in E:\A\_work\390\s\src\common\Logging\Loggers\FileLogger.cs:line 32
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

EDIT: Also, facing similar behavior with other commands using azds (e.g.  ~~prep~~, up).

**Comment by DrEsteban** [comment]
Hey @ferantivero!  Running `azds` with sudo _shouldn't_ be necessary.

1. Where is the `azds` binary located on your machine?  Is it in a protected folder?
2. Do you have access the the /tmp folder on your machine? That's where azds writes logs.  If so, can you try sharing some example logfiles?
3. Can you run `azds --version` and report back what version of azds you're using?

Thanks!

**Comment by ferantivero** [comment]
Hey @DrEsteban  

I think I  might have found one of the folders that could be causing this issue in my environment. It looks like write access to ```.azds``` could be required for some commands:  
> drwxr-xr-x  3 root      root       4096 Jan 24 19:56 .azds

Not so sure how during the installation process ```.azds``` ended up being owned by root. Please note that az-cli is also own by root in my environment and maybe during ```az aks use-dev-space``` is the moment in which this folder gets created for the first time. Please note it is not case of ```/tmp/Azure Dev Space```. Please keep reading to get the answers to your original questions. 

1. Where is the azds binary located on your machine? Is it in a protected folder?
>  /home/parallels/lib/azds-cli
```
drwxr-xr-x  4 root      root      20480 Jan 21 10:40 azds-cli
```

2. Do you have access the the /tmp folder on your machine? That's where azds writes logs. If so, can you try sharing some example logfiles? 
>  a. /tmp: I do not own the folder but yes, I do have access (rwt) 
>  b. /tmp/Azure Dev Spaces/: I am the owner, and also I have access in there (rwx)
```
$ cat /tmp/Azure\ Dev\ Spaces/azds-cli-2019-01-29-13-45-50-1486.txt

"2019-01-29T13:45:50.6595364Z" : {"eventName":"Command.Start","properties":{"arguments":"--version"},"metrics":null}(version=0.1.20190116.6)(apiVersion=2.8)(subscriptionId=d0d422cd-e446-42aa-a2e2-e88806508d3b)(CommandId=b9062e5d-4f27-49bc-b33b-536fedfdef81)(ProcessId=1486)
"2019-01-29T13:45:50.8485196Z" : {"eventName":"Command.End","properties":{"arguments":"--version","successful":"True"},"metrics":{"duration":215.0}}(version=0.1.20190116.6)(apiVersion=2.8)(subscriptionId=d0d422cd-e446-42aa-a2e2-e88806508d3b)(CommandId=b9062e5d-4f27-49bc-b33b-536fedfdef81)(ProcessId=1486)
```

3. Can you run azds --version and report back what version of azds you're using?
```
Azure Dev Spaces CLI (Preview)
0.1.20190116.6
```

> please note that executing ```azds --version``` do not require sudo and it does write /tmp/Azure Dev Spaces folder as shared above. 

OS: Ubuntu 16.04.5 LTS
Others: virtualized over Parallels


Please feel free to close this issue if your consider this is strictly related to my environment configuration.
