### ISSUE TITLE
Unable to determine the project type

### ISSUE THREAD

**Issue by apwestgarth** [Azure/dev-spaces#52]
Whenever I open the project [from this tutorial](https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-netcore) in VSCode, using the Dev-Spaces extension, I am prompted with "Required assets to build and debug are missing from '<AppName>'.  Add them? - Don't Ask Again; Not Now; Yes

I click Yes but see no .vscode directory created at all and then subsequently I see:

[Azure Dev Spaces] Unable to determine the project type for '<AppName>'.  Please manually create the required assets to build and debug.

**Comment by DrEsteban** [comment]
Hey @apwestgarth!

The message you're seeing for "Required assets to build and debug are missing from..." is likely referring to the .NET/C# extensions, not anything directly related to Dev Spaces.

Can you confirm you executed the `Prepare configuration files for Azure Dev Spaces` command in the VS Code command window as part of the "[Initialize debug assets with the VS Code extension](https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-netcore#initialize-debug-assets-with-the-vs-code-extension)" step?  THIS is the step that should generate the .vscode directory for you.

Thanks!

**Comment by xxthegonzxx** [comment]
@apwestgarth Did you ever resolve this?
