### ISSUE TITLE
Invalid dockerfile generated

### ISSUE THREAD

**Issue by Leon99** [Azure/dev-spaces#57]
When following tutorial https://docs.microsoft.com/en-us/azure/dev-spaces/multi-service-netcore-visualstudio and trying to run Dev Spaces:
```
Step 8/12 : RUN dotnet restore "/mywebapi.csproj"
---> Running in d64e15691aa8
MSBUILD : error MSB1001: Unknown switch.
Switch: /mywebapi.csproj
```
Changing the line in Dockerfile(.develop) to `RUN dotnet restore "mywebapi.csproj"` fixes it.

**Comment by philon-msft** [comment]
Hi @Leon99, thanks for reporting this and providing the workaround. We've implemented a fix and will get it released soon.

**Comment by YuzorMa** [comment]
@Leon99 This should be fixed in the latest version of the Kubernetes Tooling for Visual Studio (1.0.1903.1902)
