### ISSUE TITLE
App doesn't start after creating a new dev space

### ISSUE THREAD

**Issue by Leon99** [Azure/dev-spaces#58]
Following https://docs.microsoft.com/en-us/azure/dev-spaces/team-development-netcore-visualstudio, after creating a new dev space and pressing Ctrl+F5:
```
---------------------------
Microsoft Visual Studio
---------------------------
The version of the Dev Spaces configuration file is not supported and needs to be upgraded. The current version will be backed up in the same directory. Do you want to upgrade it now?
---------------------------
Yes   No   
---------------------------
```
Irrespective of pressing Yes or No, nothing happens (i.e. the app doesn't start).

Output window for ADS shows
`Skipping warmup for project 'mywebapi' because the version of the azds.yaml configuration file is not supported.  Launch the project to upgrade the file.`

**Comment by philon-msft** [comment]
Thanks for reporting this - we'll be sure to get a fix out soon. 

Meanwhile, you should be able to workaround the issue by manually upgrading the azds.yaml. In a command shell, navigate to the project directory containing the azds.yaml file and run "azds prep --upgrade".

**Comment by YuzorMa** [comment]
@Leon99 This should be fixed in the latest version of the Kubernetes Tooling for Visual Studio (1.0.1903.1902)
