### ISSUE TITLE
Horizontal Pod Autoscaler (HPA) does not work with AZDS enabled

### ISSUE THREAD

**Issue by cmendible** [Azure/dev-spaces#59]
Hi,

AZDS adds a sidecar for each each deployed pod. That sidecar is added **without limits and requests** and therefore, if you want to use HPA it will not work.

**Comment by lolodi** [comment]
A task has been created to track this, but it's currently low on priority. We'll let you know once this problem is fixed.

**Comment by stepro** [comment]
Hi Carlos - following up after our meeting today. Have you looked at the LimitRange object in Kubernetes? It seems like this might allow you to set default requests and limits for resources in a namespace outside of the pod spec itself. There is some more information [here](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/).

**Comment by cmendible** [comment]
So true! Let me double check with my team. I'll try again next week and come back to you with the results.

**Comment by cmendible** [comment]
Hi Stephen, I can confirm after doing a double check that the **devspaces-proxy** side car somehow does not get limits specified even after setting a **LimitRange** object like this one:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
    - default:
        cpu: 1
      defaultRequest:
        cpu: 150m
      type: Container
```
If you run **describe** on the pod you get the following results. Please note that the **php-apache** container does get the limits from the namespace **LimitRange**

```
Name:               php-apache-55c4bb8b88-mj7r7
Namespace:          default
Priority:           0
PriorityClassName:  
Node:               aks-agentpool-42554519-1/10.240.0.66
Start Time:         Fri, 22 Mar 2019 07:42:41 -0700
Labels:             pod-template-hash=55c4bb8b88
                    run=php-apache
Annotations:        kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container php-apache; cpu limit for container php-apache
Status:             Running
IP:                 10.240.0.84
Controlled By:      ReplicaSet/php-apache-55c4bb8b88
Init Containers:
  devspaces-proxy-init:
    Container ID:   docker://ac8cf0db2140093a382d549ff467277a2dd21a9a0c43ea1f6e1956a54a5483db
    Image:          azds/azds-proxy-init:20190311.3
    Image ID:       docker-pullable://azds/azds-proxy-init@sha256:74c6d4145bb3d28b9a7d197a9e350d1f5535a97bec2eefa7ba7e2ee06424e529
    Port:           
    Host Port:      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 22 Mar 2019 07:42:49 -0700
      Finished:     Fri, 22 Mar 2019 07:42:49 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      BASE_NAMESPACES:  
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b75rq (ro)
Containers:
  php-apache:
    Container ID:   docker://0b45a4b363fa1aedef5fff2cf18531938f534304aaf94164614040d718af9832
    Image:          k8s.gcr.io/hpa-example
    Image ID:       docker-pullable://k8s.gcr.io/hpa-example@sha256:581697a37f0e136db86d6b30392f0db40ce99c8248a7044c770012f4e8491544
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 22 Mar 2019 07:42:51 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:  1
    Requests:
      cpu:  150m
    Environment:
      ...
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b75rq (ro)
  devspaces-proxy:
    Container ID:   docker://678295d6d5372e6720f8f6a8a1a59ff24da34bcdd4c2268b67592753dc92e35e
    Image:          azds/azds-proxy:20190311.3
    Image ID:       docker-pullable://azds/azds-proxy@sha256:381965edb7de8afcc1f704f3cc2443d0462f7776152b8501f146409f1a595fbd
    Port:           
    Host Port:      
    State:          Running
      Started:      Fri, 22 Mar 2019 07:42:52 -0700
    Ready:          True
    Restart Count:  0
    Environment:
	  ...
	Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b75rq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-b75rq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-b75rq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  ...
```

**Comment by stepro** [comment]
Well that's unfortunate. It's probably to do with the order in which the various admission controllers run, where the [limitranger](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go) runs before the one that calls our initializer that injects the sidecar container. Let me get back to you with some additional ideas.

**Comment by stepro** [comment]
@cmendible, it looks like we need to do work on our side for this. My suggestion to the team has been to add an annotation like "azds.io/proxy-resources" that you can set on your pods to a JSON object representing the "resources" section of the container spec for the proxy. If the HPA also needs the init containers to have limits, we would provide a similar "azds.io/init-resources" annotation for those.

At this point, the timeframe for this work is looking to be somewhere in June-July.

**Comment by ShrutiPPathak** [comment]
@cmendible: We now support adding the "azds.io/proxy-resources" annotation. As mentioned in the preview comment, the value for this annotation has to be a JSON object representing the resource requirements that you want to set on the devspace-proxy container, for example:
azds.io/proxy-resources: "{\"Limits\": {\"cpu\": \"300m\",\"memory\": \"400Mi\"},\"Requests\": {\"cpu\": \"150m\",\"memory\": \"200Mi\"}}"

**Comment by cmendible** [comment]
Cool!!! I'm on vacations but I'll try it ASAP and come back to you with my findings.

**Comment by YuzorMa** [comment]
More information can be found at https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#horizontal-pod-autoscaling-not-working-in-a-dev-space

**Comment by cmendible** [comment]
Hey guys sorry I couldn't come back to you sooner. I just tested the solution and can confirm it's working as expected!

Thanks you!!!
