### ISSUE TITLE
AZDS debug configuration missing in vscode

### ISSUE THREAD

**Issue by t1agob** [Azure/dev-spaces#6]
I have been able to follow all the steps from [this documentation ](https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-netcore) up to the part where we need to initialize debug assets in VS Code Extension. I go to the Azure Dev Spaces prepare configuration option but nothing is changed under .vscode so I'm unable to debug my code in AKS directly.

Everytime I restart the project in vscode I get a message saying "Required assets to build and debug are missing from 'projectname'. Add them?". I click 'YES' but nothing happens. 

Is this broken?

**Comment by philon-msft** [comment]
Clicking 'YES' and running the 'Prepare configuration files for Azure Dev Spaces' command should both be generating/updating launch.json and tasks.json files in your .vscode directory. If that's not happening, there may be a problem with the contents of the .vscode directory or the permissions on the files. You could try deleting .vscode so VS creates fresh valid files the next time you click 'YES' on the prompt.
