### ISSUE TITLE
Running Azure Dev Spaces on kubernetes continaer project .Net Core 2.2 with reference to simple project fail to run on no reference found

### ISSUE THREAD

**Issue by HaimAudioburst** [Azure/dev-spaces#60]
I created in Visual Studio 2017 with latest update and latest kubernetes tools "Container application for Kubernetes". I added from this project a reference to simple .Net Core class library project names **EmptyProject**.
1. Build ended successfully
2. Running this project via IIS runs successfully
3. Running this project without adding reference runs successfully
When I try to run it with the reference it fails with the following message:

Step 8/12 : RUN dotnet restore "AudioBurst.Podcasts.Analysis.Service/AudioBurst.Podcasts.Analysis.Service.csproj"
---> Running in fa221fa5004e
**Skipping project "/src/EmptyProject/EmptyProject.csproj" because it was not found.
Skipping project "/src/EmptyProject/EmptyProject.csproj" because it was not found.**
Restoring packages for /src/AudioBurst.Podcasts.Analysis.Service/AudioBurst.Podcasts.Analysis.Service.csproj...
Installing Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.1.1.
Installing Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets 1.0.0.
Generating MSBuild file /src/AudioBurst.Podcasts.Analysis.Service/obj/AudioBurst.Podcasts.Analysis.Service.csproj.nuget.g.props.
Generating MSBuild file /src/AudioBurst.Podcasts.Analysis.Service/obj/AudioBurst.Podcasts.Analysis.Service.csproj.nuget.g.targets.
Restore completed in 1.79 sec for /src/AudioBurst.Podcasts.Analysis.Service/AudioBurst.Podcasts.Analysis.Service.csproj.
Removing intermediate container fa221fa5004e
---> da90182c15f7
Step 9/12 : COPY . .
---> 73f5e5e6fb01
Step 10/12 : WORKDIR "/src/AudioBurst.Podcasts.Analysis.Service"
---> Running in 7385687e3843
Removing intermediate container 7385687e3843
---> 38de363c4348
Step 11/12 : RUN dotnet build --no-restore "AudioBurst.Podcasts.Analysis.Service.csproj" -c $BUILD_CONFIGURATION
---> Running in 163b4f8988d2
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/share/dotnet/sdk/2.2.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file '/src/EmptyProject/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/src/EmptyProject/EmptyProject.csproj]
Build FAILED.
/usr/share/dotnet/sdk/2.2.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file '/src/EmptyProject/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/src/EmptyProject/EmptyProject.csproj]
0 Warning(s)
1 Error(s)
Time Elapsed 00:00:01.09

**Comment by ShrutiPPathak** [comment]
Thanks for reporting the issue. Can you please confirm if the Dockerfile that was auto-generated contains instructions to copy "EmptyProject.csproj". I suspect this happened because the Dockerfile was generated when the reference to "EmptyProject.csproj" did not exist.

**Comment by YuzorMa** [comment]
Closing as we need more details to investigate and have not heard back in over a month.

**Comment by saitejaprattipati** [comment]
I have same issue raised here, 
I am trying to run asp.net core webapi application in devspaces azure kubernetes service it is running good but when i am referencing dotnercore class library to webapi project and trying to run the application i am getting error as follows
`Skipping project "/src/CommandStack/ClassLibrary1/ClassLibrary1.csproj" because it was not found. "/usr/share/dotnet/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file '/src/CommandStack/ClassLibrary1/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/src/CommandStack/ClassLibrary1/ClassLibrary1.csproj]"`

My docker file is as follows:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["CommandStack/WebApplication1/WebApplication1.csproj", "CommandStack/WebApplication1/"]
COPY ["CommandStack/ClassLibrary1/ClassLibrary1.csproj", "CommandStack/ClassLibrary1/"]
RUN dotnet restore "CommandStack/WebApplication1/WebApplication1.csproj"
COPY . .
WORKDIR "/src/CommandStack/WebApplication1"
RUN dotnet build "WebApplication1.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebApplication1.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```
However i am able to run the application using IISExpress.

Any suggestions will be great help.

**Comment by HaimAudioburst** [comment]
Hi,
I am little bit confused about this mail.
We opened a support call on Kubernetes and CronJob with dev spaces.
I don’t understand this ticket.
