### ISSUE TITLE
Linux tar gzipped archives not sync'd

### ISSUE THREAD

**Issue by andrewstevenson** [Azure/dev-spaces#61]
Archives required for docker builds are not sync'd causing the docker build to fail.
for example, 

`my-archive.tar.gz` not sync'd but `my-achive.tar` is. Tyring to add these files to the docker therefore fails.

**Comment by YuzorMa** [comment]
@andrewstevenson Can you check your ignore files (.gitignore, .dockerignore, etc.) to make sure that you're not excluding tar.gz files.  Dev Spaces will honor the rules of your ignore files and not sync files and folders that are ignored.
