### ISSUE TITLE
Azure DevSpaces VS extension incompatible with Service Fabric debugging

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#64]
When having the DevSpace VS extension installed and trying to debug a Service Fabric application, you recive the following error:

![image](https://user-images.githubusercontent.com/12099277/54144930-1e0e9500-442d-11e9-9a67-aeaa093ab270.png)

To reproduce:
1) Install Service Fabric toolings
2) Install DevSpaces VS extension
3) Create a default Service Fabric web project
4) Start SF Application in debug mode

**Comment by dbreshears** [comment]
Thanks for reporting.    We have a fix for this that should be coming this week..

**Comment by Eneuman** [comment]
Nice
I'll wait for the new release and after testing it i'll close this issue :)

**Comment by dbreshears** [comment]
@Eneuman ,  have you had  chance to test this?

**Comment by Eneuman** [comment]
Yes, this resolved now so I’m closing this issue.
