### ISSUE TITLE
DevSpaces CLI problem when having mutiple subscriptions

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#65]
If you have a account with mutiple different subscriptions, dev spaces VS extenion and CLI will fail with mutiple problems.

To reproduce:
1) Create a new Azure Account.
2) Add a Subscription of type "DEV/Test"
3) Add a Subscription of type "Pay as you go"
4) Create a AKS cluster in your "DEV/Test" subscription

This will all work fine so far.

Now If you start VS and create a a new web app and point it to your newly created AKS cluster, you will be asked to setup dev spaces. You press okey and after a few min it says that the new controller is installed.

If you start debug now, you will recived "Cannot sync files. DevSpace out of space."
If you try and use the cli, it will show you that it cannot find the resource group, in the selected subscription X.

Where X is the "Pay as you go" subscription. It looks like it defaults to the wrong subscription for the cli, and the error message in VS console show the wrong message.

After I removd my AKS from my DEV/Test and setup a new cluster in my "Pay as you go" subscription, everything worked fine, except for my Nuget privat feed issues, but that's for another Issue ;)

**Comment by lisaguthrie** [comment]
The VS extension uses the subscription you select in the VS UI, while the CLI uses the default subscription you've configured. You can choose a different default subscription for the CLI using the `az account set` command.

Sounds like there may have been an issue with the cluster associated with your dev/test subscription. Happy to help with troubleshooting if you want to give it another shot.

**Comment by Eneuman** [comment]
Sure :)
I'll setup a new cluster in my Dev/Test subscription and try to reproduce the issue again.
Gonna take me 30 min or so.

**Comment by Eneuman** [comment]
After setting up a new AKS in my DEV/Test subscription it seems to working fine :)
Maby this was a transient problem since I cannot reproduce it again. 
I'm closing this issue for now.
