### ISSUE TITLE
Automatically align DevSpace with source branch

### ISSUE THREAD

**Issue by jelster** [Azure/dev-spaces#66]
As an application developer and product manager, I would like to have a DevSpace automatically created and selected for me that corresponds to and is named the same as the current source control branch so that I am less likely to mess up or forget to change and/or set my DevSpace across different code branches

The docs supply a diagram illustrating a hypothetical CI/CD process. This diagram implies to me that aligning a dev space with source branches should have some accommodation within the DevSpace framework.

**Comment by johnsta** [comment]
Hi jelster, I'm on the Dev Spaces product team. That's a really interesting suggestion that's been made by several users. I'd like to learn more about your scenarios and how you would use this feature. Would you be ok with a quick 30 min phone call to discuss more? Feel free to reach out to me at john.stallo@microsoft.com.

**Comment by YuzorMa** [comment]
@jelster I'm not sure if you're seen it, but we published a post recently that builds on the scenario you describe: https://medium.com/microsoftazure/kubernetes-github-and-devops-putting-it-all-together-to-increase-confidence-in-pull-request-3797e8fea3f7.  If you get a moment, try it out and let us know what you think.

**Comment by jelster** [comment]
Great post in your link, @YuzorMa!

![image](https://user-images.githubusercontent.com/1508500/59781892-6cc89800-9282-11e9-8217-21f3dcc056b2.png)

No words. They should've sent a poet. *sniff* :)

In all seriousness, this is exactly the thing that I think has massive potential for just about everyone involved in a project. This is a great step to broadening participation in the development process out of the trenches and out into the entire organization (big picture), while still improving productivity by reducing friction right now (immediate picture) for developers.

I'm going to take it for a test spin hopefully sometime this week, will post back here with impressions. 

Thanks again for listening to feedback and including the community!
