### ISSUE TITLE
AZDS can't prepare configuration files for debug

### ISSUE THREAD

**Issue by immortalpl** [Azure/dev-spaces#68]
Hi,
Basing on tutorial: https://docs.microsoft.com/pl-pl/azure/dev-spaces/quickstart-java 
I'm not able to debug sample "webfrontend" JAVA application. Below instruction is unfortunately not working for me:

"Open the Command Palette (using the View | Command Palette menu), and use auto-complete to type and select this command: Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces. This adds debug configuration for Azure Dev Spaces under the .vscode folder."

There is completely no reaction on command selection. Launch.json and settings.json files are not modified, there is no new debug configuration possible to select as "Launch Java Program (AZDS) ". 
My files:

```
launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    ]
}
```

```
settings.json
{
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    }
}
```

In Log(Windows) there is new entry:
```
[2019-03-21 14:26:25.148] [renderer1] [error] Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
	at module.exports.e.DependencyDataProvider.revealPaths.n.find.t (C:\Users\bsu8wz\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:26196)
	at Array.find (<anonymous>)
	at module.exports.e.DependencyDataProvider.<anonymous> (C:\Users\bsu8wz\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:26177)
	at Generator.next (<anonymous>)
	at s (C:\Users\bsu8wz\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:24568)
	at o (C:\Users\bsu8wz\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at C:\Users\bsu8wz\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474
```

I was trying to:
1. Reinstall extensions
2. Delete .vscode and json files
3. Running Visual Studio Code as administrator.
4. Copy project to different location
nothing help.

I'm using versions:
Visual Studio Code: 1.32.3
Java for Azure Dev Spaces: 0.2.1
Azure Dev Spaces 0.1.120190228
Debugger for Java: 0.17.0
Java Extension Pack 0.6.0
Language Support for Java(TM) by Red Hat: 0.41.0
Java Dependency Viewer: 0.3.0

**Comment by andxu** [comment]
hi @immortalpl  Thank you for trying java in Azure Dev Spaces, the error message in vscode-java-dependency is trivial and not the reason for your problem(it will be fixed on next version of vscode-java-dependency about a week later), have you installed maven, or are you working on a new environment with maven newly installed?  In the latter case, there will be considerable time in downloading the required maven packages (over 5 minutes). If you have installed maven and could you please open a java file in vscode and tell me whether or not there is the icon in status bar like the picture below(which indicates your vscode java environment is ready):
![image](https://user-images.githubusercontent.com/17075863/54968767-ce94a100-4fb6-11e9-938d-2bfdc36c65cb.png)

**Comment by YuzorMa** [comment]
@immortalpl  Please let us know if yo uare still seeing this with @andxu's comments.  Closing for now as we have not heard back in 1 month.

**Comment by wely** [comment]
I am having similar error though my app is NodeJS. After consulting Andy, it was solved. Here're the steps:
1) The VS Code Root Folder need to be set to where our app is pointed. 
2) Remove previously auto-generated files (if any) like azds.yaml and chart folder (if any).
3) Then Run Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces.

It works now!
![image](https://user-images.githubusercontent.com/1658657/69298295-5fa44080-0c48-11ea-9b2f-1e4f383c410b.png)

Thank you @andxu
