### ISSUE TITLE
Getting SSL error when attempting to use azds up 

### ISSUE THREAD

**Issue by antiph0n** [Azure/dev-spaces#7]
Using dev space 'default' with target 'DevSpaces'
Synchronizing files...10s
Installing Helm chart...The SSL connection could not be established, see inner exception.

Unsure how to see the inner exception. This is a .Net Core 2.1 project.

**Comment by sanar-microsoft** [comment]
Sorry, we had an issue with our infrastructure in East US region and this should be fixed now, please try running the command again.
