### ISSUE TITLE
azds list-uris do not show any uri

### ISSUE THREAD

**Issue by eiximenis** [Azure/dev-spaces#75]
Hi!
I use `azds list-uris` to get the URIs of my current devspace but I do not get any Uri. I must use `-a` modifier to get the uris.

![image](https://user-images.githubusercontent.com/5191049/55023448-1b9b6600-4ffd-11e9-8c49-bd28cac43ca3.png)

As you can see in the image I am in the devspace "demo" and I have two services on it (webbff is in another devspace). Ingresses were created in the "demo" namespace but `azds list-uris` returns empty. I have to use `-a` to get the uris.

**Comment by YuzorMa** [comment]
Thanks @eiximenis  We're investigating a similar bug where list-uris returns "inconsistent" behavior.  We have not found the source of the issue yet, but we will post back here once we identify it and if there is a workaround.

**Comment by YuzorMa** [comment]
This should be fixed in the latest version of the tools.
