### ISSUE TITLE
Stuck with Waiting for container image build...

### ISSUE THREAD

**Issue by puzits** [Azure/dev-spaces#77]
Trying to run Azure dev spaces with the helm chart modified to fit our needs. It is able to install the helm chart but not able to build the container image it fails with timeout. 

When i see the pod status it says 
"Container image "gwravailabilityapi/devspaces-x0169ddd533bbfbf6" is not present with pull policy of Never 
Error: ErrImageNeverPull "
Azure dev spaces output log:
Release "azds-ed9bd4-default-gwr-availability-api" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Apr  2 11:35:35 2019
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1beta1/Ingress
NAME                  HOSTS                                               ADDRESS         PORTS    AGE
availability-ingress  default.gwravailabilityapi.npp5qkkfg6.eus2.azds.io  137.116.34.240  80, 443  1h
==> v1/Pod(related)
NAME                                 READY  STATUS       RESTARTS  AGE
gwravailabilityapi-77f67bf4bc-cvd9s  1/2    Terminating  0         11m
gwravailabilityapi-96d94667d-xt8qg   0/2    Init:0/1     0         0s
==> v1/Service
NAME                TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)   AGE
gwravailabilityapi  ClusterIP  10.0.16.189  <none>       5000/TCP  1h
==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
gwravailabilityapi  1        1        0           0          1h
NOTES:
1. Get the application URL by running these commands:
  https://default.gwravailabilityapi.npp5qkkfg6.eus2.azds.io/availability
Installed chart in 2s

Waiting for container image build...

Streaming build container logs for service 'gwr-availability-api' failed with: Timed out after 10m trying to start build logs streaming operation. 10m 3s

Container image build failed

**Comment by amsoedal** [comment]
Hi @puzits, can you examine your dockerfile? Our logs indicate that in this scenario the build succeeded but that actually running the image is failing.  Thanks for raising this issue, we'll try to provide better feedback in this scenario to make troubleshooting easier.

**Comment by puzits** [comment]
Hi @amsoedal  thanks for replying. I was able to fix the above issue by changing the container image name. Now it is able to build an image from the pod.  But for some reason pod logs show following message. 
![image](https://user-images.githubusercontent.com/10223948/55456134-e0ec8b80-5603-11e9-8b4d-424d34e6ad1e.png)

**Comment by sanar-microsoft** [comment]
@puzits I've seen this error when the ENTRYPOINT is incorrect. Is the assembly name 'GWR.Availability.API.dll' correct?

**Comment by puzits** [comment]
hi @sanar-microsoft , i was able to fix it. The reason for the issue was in azds.yaml develop configuration i was not pointing to Dockerfile.develop. 
Once that corrected issue is fixed.
