### ISSUE TITLE
VS17 stuck at "Waiting for container..." when trying to debug quickstart app using Dev Spaces

### ISSUE THREAD

**Issue by alecor191** [Azure/dev-spaces#8]
Hi,

I tried to follow the [quickstart](https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-netcore-visualstudio) steps using VS17 and unfortunately I got stuck. This is what I have observed:
- AKS version is 1.10.5 (also tried with 1.10.3)
- Namespace 'azds' created (with 3 pods in it). All pods report that they're healthy.
- My quickstart MVC app got deployed successfully to the 'default' namespace (I see the pod, it reports it's healthy)
- Successful registration of my MVC app in Azure DNS
- AKS cluster is healthy (no errors/warnings, pods deployed to it work fine)
- I see an Ingress configuration for the MVC app that points to the registered DNS name
- AKS cluster is deployed to `westeurope`

### Additional info
- I created multiple AKS clusters (using Azure CLI as well as Azure Portal wizard)
- I created multiple MVC apps and let VS Tools for K8S add dockerfile and Dev Spaces files (as described in quickstart guide)

I always end up with VS not being able to debug into the container using "Azure Dev Spaces".

#### MVC App container logs
```
λ  kubectl logs webapplication7-589b9545cb-bzx7w -c webapplication7
Info 2018-07-14T11:45:54.1801851Z agent running on 50051
```

#### VS Output when pressing "F5"
```
Starting warmup for project 'WebApplication7'.
Failed to get service status: Failed to get status of service 'webapplication7' in space 'default'.
Using dev space 'default' with target 'tmp9-cluster'
NAME:   default-webapplication7-201408c8
LAST DEPLOYED: Sat Jul 14 11:45:23 2018
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Service
NAME             TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)  AGE
webapplication7  ClusterIP  10.0.74.75  <none>       80/TCP   1s
==> v1beta2/Deployment
NAME             DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
webapplication7  1        1        1           0          1s
==> v1beta1/Ingress
NAME             HOSTS                                                      ADDRESS  PORTS  AGE
webapplication7  webapplication7.db7a345116c24911b92d.westeurope.aksapp.io  80       1s
==> v1/Pod(related)
NAME                              READY  STATUS   RESTARTS  AGE
webapplication7-589b9545cb-bzx7w  0/2    Pending  0         0s
NOTES:
1. Get the application URL by running these commands:
  http://webapplication7.db7a345116c24911b92d.westeurope.aksapp.io/
Building container image...
Sending build context to Docker daemon  2.444MB
Step 1/12 : FROM microsoft/aspnetcore-build:2.0
 ---> 7fed40fbb647
Step 2/12 : ENV ASPNETCORE_ENVIRONMENT Development
 ---> Using cache
 ---> 85f6a63d88c8
Step 3/12 : ENV DOTNET_USE_POLLING_FILE_WATCHER true
 ---> Using cache
 ---> 25e00721ba59
Step 4/12 : EXPOSE 80
 ---> Using cache
 ---> 83424721a7d3
Step 5/12 : WORKDIR /src
 ---> Using cache
 ---> c417833e55a1
Step 6/12 : COPY WebApplication7.sln ./
 ---> Using cache
 ---> 70a6c8cd16e4
Step 7/12 : COPY WebApplication7/WebApplication7.csproj WebApplication7/
 ---> Using cache
 ---> 69af23acbaac
Step 8/12 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Using cache
 ---> b96da181be4d
Step 9/12 : COPY . .
 ---> Using cache
 ---> b50bdecd3e73
Step 10/12 : WORKDIR "/src/WebApplication7"
 ---> Using cache
 ---> 16cd2549742e
Step 11/12 : RUN dotnet build "WebApplication7.csproj"
 ---> Using cache
 ---> f793f0995951
Step 12/12 : CMD dotnet run --no-restore --no-build --no-launch-profile
 ---> Using cache
 ---> 793671362def
Successfully built 793671362def
Built container image in 8s
Waiting for container...
```

Notice the error message in the second line above:
```
Failed to get service status: Failed to get status of service 'webapplication7' in space 'default'.
```

VS is stuck at the last line `Waiting for container...`.

#### Response when sending a request to the MVC app's host name:
Sending a request to `http://webapplication7.db7a345116c24911b92d.westeurope.aksapp.io` shows:
```
502 Bad Gateway
nginx/1.13.12
```

#### Last Ingress controller logs
```
W0714 11:31:36.157594       7 controller.go:1117] unexpected error obtaining service endpoints: could not find endpoints for service default/webapplication7
W0714 11:31:36.157807       7 controller.go:775] service default/webapplication7 does not have any active endpoints
I0714 11:31:36.157925       7 controller.go:170] backend reload required
I0714 11:31:36.309684       7 controller.go:179] ingress backend successfully reloaded...
W0714 11:31:42.788356       7 controller.go:775] service default/webapplication7 does not have any active endpoints
```

#### Logs from WebApplication7 container
```
Info 2018-07-14T11:45:54.1801851Z agent running on 50051
```
I was expecting a bit more here as by default the ASP.NET Core apps created through VS template log to the console. So we should see a bunch of logs coming from the app while it's starting up ASP.NET Core.

Any suggestions how to further troubleshoot this? I'm new to Docker/K8S/AKS, so I may be missing something obvious. To me it looks like that WebApplication7 container is not properly working? However, I verified that the container works fine running locally. I also have a couple ASP.NET Core containers running in the same AKS cluster and they work fine.

**Comment by pragyamehta** [comment]
Hi there! Thank you for using Azure Dev Spaces!
To troubleshoot your problem, Could you please share if the chart that you are using was generated by Visual Studio or did you create one yourself?

**Comment by alecor191** [comment]
Thanks @pragyamehta for the follow up: Correct, the chart was generated by VS. I followed the quickstart guide by the letter. I tried it a couple of times with different, freshly created, AKS clusters. Unfortunately, they all led to the same result.

**Comment by pragyamehta** [comment]
I see. Next, in VS, can you open Tools -> Options -> Projects and Solutions -> Build and Run and set MSBuild project build output verbosity to "Detailed" and run through the scenario again? Then open the Output window -> Show output from "Azure Dev Spaces" and please copy paste what you see in that window once it fails.
I would also request you to hang on to the controller that is failing for you so that we can investigate further. It would be helpful if you could share the controller name with us.

**Comment by ferronsw** [comment]
I've the same issue. The Kubernetes pod has the following error:

`container "application1" in pod "application1-54cccb7747-jhscv" is waiting to start: ErrImageNeverPull`

**Comment by SamuelMcAravey-NVP** [comment]
We also see this when using the sample project as well as with our own code. Trying to run this from the CLI. This AKS cluster was just created in the last couple of days.

Azure CLI version:  **2.0.43**
Azure Dev Spaces CLI (Preview): **0.1.20180727.4**
Kubernetes version: **1.10.6**
AKS Location: **West US 2**

After calling `azds up` it hangs on `Waiting for container image to build...` and cancels after 10 minutes. Looking in the cluster dashboard we see the same error as @ferronsw:

![image](https://user-images.githubusercontent.com/14908190/43909323-eab18900-9bae-11e8-9f05-c716431a2c87.png)

**Comment by lisaguthrie** [comment]
Thanks @SamuelMcAravey-NVP and @ferronsw - we'll look into this.

**Comment by sanar-microsoft** [comment]
@SamuelMcAravey-NVP @ferronsw Could you share your controller name for investigating this issue?

**Comment by sanar-microsoft** [comment]
@SamuelMcAravey-NVP @ferronsw Is it possible that the initializerconfiguration deployed on the AKS cluster for dev spaces was deleted? An error like this indicates that there was a failure in initializing the pod and an init container(build) was never injected to your pod.

**Comment by ferronsw** [comment]
@sanar-microsoft I've deleted and recreated the dev spaces controller multiple times within my AKS cluster. Everything looks promising when I do that, till I get the message "Waiting for container..." then after 10 minutes it times out.

**Comment by SamuelMcAravey-NVP** [comment]
Same here. We also spun up a brand new cluster and tried to configure Dev Spaces again and got the same error. As far as I can tell, everything in the azds namespace is working as it should. Here is the output of several kubectl commands I ran against the azds namespace as well as the Dev Space namespace I created:

**AZDS namespace:**
```powershell
PS C:\> kubectl get deployment -n azds
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
azds-initializer   1         1         1            1           5d
tiller-deploy      1         1         1            1           5d

PS C:\> kubectl get pods -n azds
NAME                                READY     STATUS    RESTARTS   AGE
azds-image-prepull-q22lf            1/1       Running   0          3d
azds-image-prepull-vjgbg            1/1       Running   1          4d
azds-initializer-57db9b7cb7-2v9k5   1/1       Running   1          4d
tiller-deploy-754cfd459c-79g5r      1/1       Running   1          5d

PS C:\> kubectl get services -n azds
NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
tiller-deploy   ClusterIP   10.0.3.174   <none>        44134/TCP   5d

PS C:\> kubectl get replicasets -n azds
NAME                          DESIRED   CURRENT   READY     AGE
azds-initializer-57db9b7cb7   1         1         1         4d
azds-initializer-7c47ff7cbd   0         0         0         5d
tiller-deploy-754cfd459c      1         1         1         5d

PS C:\> kubectl get daemonsets -n azds
NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
azds-image-prepull   2         2         2         2            2           <none>          5d
```

**Testspace namespace:**
```powershell
PS C:\> kubectl get deployment -n testspace
NAME          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
webfrontend   1         1         1            0           3d

PS C:\> kubectl get pods -n testspace
NAME                           READY     STATUS              RESTARTS   AGE
webfrontend-645fd8bf69-h8gds   0/1       ErrImageNeverPull   0          3d

PS C:\> kubectl get services -n testspace
NAME          TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
webfrontend   ClusterIP   10.0.0.103   <none>        80/TCP    3d

PS C:\> kubectl get replicasets -n testspace
NAME                     DESIRED   CURRENT   READY     AGE
webfrontend-645fd8bf69   1         1         0         3d

PS C:\> kubectl get ingress -n testspace
NAME          HOSTS                                                                 ADDRESS   PORTS     AGE
webfrontend   testspace.s.webfrontend.33ad63f3fcf1466dbead.westus2.aksapp.io             80        3d
```

Note that for the pod in the testspace namespace has the status `ErrImageNeverPull`. I used the sample project from the documentation, and followed the steps against a brand new AKS cluster.

**Comment by sanar-microsoft** [comment]
@SamuelMcAravey-NVP I just patched your cluster, it was missing the initializerconfiguration. You can verify it by running, 'kubectl get initializerconfiguration/azds'. Let me know if it fixed the issue.

@ferronsw Please share the controller information so that I can patch your cluster. Although I believe deleting and recreating the controller should've solved it too.

**Comment by sanar-microsoft** [comment]
@ferronsw You can run 'azds controller list' to see all the created controllers or 'azds show-context' to see currently selected controller information. Please let me know the region as well, it will be part of the controller list command output.

**Comment by sanar-microsoft** [comment]
I believe something might've gone wrong with patching of your cluster before that caused the controller to be in this state. Sorry for all the trouble.

You can get the yaml config for the initializerconfiguration (run 'kubectl get initializerconfiguration/azds -o yaml') and save it in a file, in case it happens again you can just run 'kubectl apply -f <yaml config> -n azds' to deploy this configuration again. 

An easier way to fix any configuration issue would be to dele and recreate , to delete a controller run 'azds remove -n <controller name> -g <resource group name>'. Although you'll have to select dev space again in this case.
