### ISSUE TITLE
az aks use-dev-spaces fails with no output

### ISSUE THREAD

**Issue by tylerjwatson** [Azure/dev-spaces#83]
The Azure CLI on Ubuntu 19.04 fails to run the `az aks use-dev-spaces` command with no output an no `azds` command being added to the path of the working environment.

Below is an excerpt from the terminal

```bash
zapien git:(es2015) MS_VS_AZUREDEVSPACES_TOOLS_LOGGING_ENABLED=1 az  aks  use-dev-spaces -g rapid-platform -n rapid-platform --verbose
/home/tw/lib/azure-cli/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Suppress exception Return value is not string
command ran in 1.969 seconds.
```

Azure CLI was installed with the bash script.

**Comment by JerryWang20** [comment]
i also meet the issue for i run ' az aks use-dev-spaces -g mygroup -n mycluster' and it responds with '[K - Searching ..' what's the solution for it?

**Comment by rakeshvanga** [comment]
@tylerjwatson are you able to run other azure cli commands properly?
It seems to be an issue with azure cli dependencies as mentioned in this issue: https://github.com/Azure/azure-cli/issues/6513.
Can you trying re-installing azure cli using a different method?

**Comment by rakeshvanga** [comment]
@JerryWang20 Can you provide more details of the issue? Are you seeing exactly the same error as tyler has? 
On what plat form are you running this command?
Also can you provide the error messages that you get from the console?
Thanks!

**Comment by tylerjwatson** [comment]
> @tylerjwatson are you able to run other azure cli commands properly?
> It seems to be an issue with azure cli dependencies as mentioned in this issue: [Azure/azure-cli#6513](https://github.com/Azure/azure-cli/issues/6513).
> Can you trying re-installing azure cli using a different method?

Sure, I uninstalled it under bash and installed the .deb package and the symptoms stay the same.
I also installed the .msi under windows 10 and still the same issue.

**Comment by tylerjwatson** [comment]
Some more diagnostic information that may be of use to you:

```bash
➜  ~ dpkg -s azure-cli 
Package: azure-cli
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 429855
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Architecture: all
Version: 2.0.62-1~cosmic
Depends: libc6 (>= 2.28), libssl1.1 (>= 1.1.0)
Conffiles:
 /etc/bash_completion.d/azure-cli c84398bd5fcef515a11afad8f1a7827e
Description: Azure CLI
 A great cloud needs great tools; we're excited to introduce Azure CLI,
 our next generation multi-platform command line experience for Azure.
Homepage: https://github.com/azure/azure-cli
```

```bash
➜  ~ az extension list
[]
```

It appears an `azds` binary is not included with the package; is it downloaded?

```bash
➜  ~ dpkg -L azure-cli  |grep -i azds
➜  ~ 
```

**Comment by JerryWang20** [comment]
i upgrade the Azure Cli to the latest version of 2.0.63. And it return the different error:
Downloaded to C:\Users\u587212\AppData\Local\Temp\tmpenn_0583\dev_spaces-1.0.0-py2.py3-none-any.whl
Validating the extension C:\Users\u587212\AppData\Local\Temp\tmpenn_0583\dev_spaces-1.0.0-py2.py3-none-any.whl
Invalid checksum for C:\Users\u587212\AppData\Local\Temp\tmpenn_0583\dev_spaces-1.0.0-py2.py3-none-any.whl. Expected 'd6
336308305746718893d4e88089b083ebb0f7f82e74f71c98bf40acbc804ccb', computed '2ddeb251c45d022f8bf5bb86a18fa69587cc759cbe623
c18067ba20da75cb6ce'.

**Comment by amsoedal** [comment]
@JerryWang20 Both the issues of mismatched checksums & "- Searching..." should be fixed by a PR that got merged into the az-cli-extensions repo last night:  https://github.com/Azure/azure-cli-extensions/pull/648  
Can you try again now and see if you see the same error?

**Comment by tylerjwatson** [comment]
> @tylerjwatson Can you also try again, and if it doesn't work try upgrading to 2.0.63?

Hi @amsoedal - it seems to have fixed it on Windows 10, Ubuntu is still a work in progress.  Many thanks on the support from everyone in this thread, it's not ideal but at least I have _some_ avenue forward in my research.  :+1:

**Comment by tylerjwatson** [comment]
The `az aks use-dev-spaces` command is adament that it wants to install the .NET Core runtime, even though one is present and `DOTNET_HOME` environment variable is set.  

The "official" installer does not work for ubuntu disco as it has not been packaged yet in the official repo, hence the manual installation of a dotnet sdk, which works otherwise.

I'm inclined to close this issue as it's technically a different problem, however the `az aks use-dev-spaces` ultimately is still not functional.  Please advise if another issue is required

**Comment by rakeshvanga** [comment]
@tylerjwatson Close this issue and feel free to open a new one for forcing the installation of .NET Core runtime. This is a separate issue that is related to Ubuntu 19.04.
