### ISSUE TITLE
preLaunch task fails with: SSL connection could not be established

### ISSUE THREAD

**Issue by travisnielsen** [Azure/dev-spaces#85]
I'm experience an issue very similar to #7 (closed) in VS Code on mac. When running in debug mode, I receive the following error:

```
Built container image in 1s
Waiting for container...10s
The SSL connection could not be established, see inner exception.
The terminal process terminated with exit code: 1
```
Here is my launch.json

```
    {
        "name": ".NET Core Launch (AZDS)",
        "type": "coreclr",
        "request": "launch",
        "preLaunchTask": "azds: prelaunch",
        "pipeTransport": {
            "pipeCwd": "${workspaceFolder}",
            "pipeProgram": "azds",
            "pipeArgs": [
                "exec",
                "--interactive",
                "--on-exit-resume-up",
                "--"
            ],
            "debuggerPath": "/vsdbg/vsdbg",
            "quoteArgs": false
        },
        "cwd": "/src",
        "program": "/src/bin/Debug/netcoreapp2.2/dev-spaces-api.dll",
        "sourceFileMap": {
            "/src": "${workspaceFolder}/."
        }
    }
```
The same code works fine from a Windows 10 VM running Visual Studio 2017 so I don't believe this is a cluster or Azure infrastructure issue.

**Comment by sanar-microsoft** [comment]
@travisnielsen 
Can you share AZDS logs from your machine and CLI, VSCode extension version? 
The logs should be present in $TMPDIR on mac under Azure Dev Spaces subdirectory, and you can run `azds --version` to get the CLI version.

**Comment by YuzorMa** [comment]
@travisnielsen Closing this issue as we need the client logs to investigate further,
