### ISSUE TITLE
Integrating user secrets.json into inner loop

### ISSUE THREAD

**Issue by markphillips100** [Azure/dev-spaces#91]
Azure Dev-Spaces makes use of extra yaml files to include secrets as part of an inner-loop deployment.  The azds.yaml makes reference to optional secrets.dev.yaml for this purpose.

When our projects are .Net core we have a really nice user secrets management per project.  Is it possible the dev-spaces can make use of these secrets.json files when the project in question is .net?

**Comment by stepro** [comment]
@markphillips100, can you point us to some docs for the secrets.json approach you are using in your .NET projects? Or give us a quick description? The primary challenge with consuming a different secret file is knowing how to translate the content of one into the expected set of Helm chart values.

**Comment by markphillips100** [comment]
Sure @stepro, here are the Microsoft docs I refer to for using User Secrets in .net core projects. [https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows).  Keep in mind I'm assuming dev-spaces is supposed to be resolving an inner-loop experience for AKS agnostic of the project SDK, but in my case I only use .net core.

I've used docker-compose in the past and the default generated files for that map the .net user secrets root folder so it's available to the docker image.  Obviously that's not an option here.

The docker context issue (or design) of not being able to access a file (like the userprofile's user secrets.json) outside of it's location is troublesome.  So far I've only considered maybe using a docker build arg to hold the contents of the project's secrets.json file and then cat-pipe it into a file in a location available to the underlying aspnetcore code, but alas I've reached the limit of my knowledge.

**Comment by stepro** [comment]
Thanks for the info. I see that the documentation talkes about how to manage secrets at development time. The purpose of dev spaces is to give you an inner loop with more production fidelity, so ideally when you are running your code in AKS, you would not be managing secrets in the manner appropriate for development, but rather in the way you actually intend to consume secrets in production.

Dev Spaces is (currently) built on the assumption that you are using Helm to deploy your workloads to AKS, and the parameterization story there involves passing input values either on the `helm install` command line or through a values file like secrets.yaml. By modifying the Helm chart, you can always choose how exactly your app consumes the secret values, say through Kubernetes secrets mounted as environment variables (our default setup) or mounted as a file in a particular location (maybe what you are looking for).

Once you have this in place, the best we have right now is for you to manually create the necessary Helm input values files that contain the secrets, or manually deploy the secrets to AKS for your Helm chart to consume. It isn't on our radar to add a mechanism that automatically consumes secrets.json and propagates it into AKS as that isn't intended to be a production ready way of running code in the cluster.

Hope that makes sense!

**Comment by markphillips100** [comment]
Thanks for the clarity @stepro. It all makes sense thanks, and I like the strategy of getting closer to the production deployment mechanism too by using Helm and how it supports supplying a "values" file.  I guess I got side-tracked a little having been so used to the .net user secrets.  I'll stick to only using those when debugging locally.

Just for some extra context, my CI/CD process transforms a `values.cd.yaml` that lives in the project's source code repo alongside the `chart.yaml`.  This file contains token placeholders for property values that get replaced during a specific environment deployment.  The process then supplies this transformed file to a `helm update`.

It would be simple to just use a `values.dev.yaml` (not source controlled) to provide custom data, secret or otherwise, as you have suggested.  In other words, follow the documented approach.

"Dev Spaces is **(currently)** built on the assumption that you are using Helm to deploy your workloads to AKS" - are there alternative deployment mechanisms coming?  I only know of `kubectl apply` or `Helm`.

**Comment by stepro** [comment]
By "currently" I wasn't implying that anything else is planned. There's a relatively new approach using kustomize.io that has been added to kubectl apply as an alternative to templating. We'll be watching how that lands and may look into supporting it as well as Helm.
