### ISSUE TITLE
Azure Dev Spaces does not work on Kubernetes version 1.14

### ISSUE THREAD

**Issue by YuzorMa** [Azure/dev-spaces#95]
Adding Dev Spaces to a cluster with Kubernetes version 1.14 will fail.

The original implementation of Dev Spaces used the Kubernetes Initializers feature which has been deprected in Kubernetes 1.14.  Our newest versions no longer use Initializers, but we still deploy older versions to support older clients.  We will be deprecating these versions shortly but in the meantime, please do not use Kuberentes version 1.14 if you want to use Dev Spaces.

**Comment by tslavik** [comment]
Do we have some estimation when will be this issue fixed?

**Comment by stepro** [comment]
The work required to resolve this issue is ongoing and we estimate it will be about two weeks before the necessary changes are in production.

**Comment by YuzorMa** [comment]
The fix to support 1.14 went live in all regions last week.  Resolving the issue,
