### ISSUE TITLE
Helm install failed

### ISSUE THREAD

**Issue by matt-landers** [Azure/dev-spaces#96]
I'm getting the error below when running `azds up`

`
Helm install failed with exit code '1': Error: UPGRADE FAILED: render error in "myproj/templates/secrets.yaml": template: horseman-api/templates/secrets.yaml:9:26: executing "myproj/templates/secrets.yaml" at <b64enc>: wrong type for value; expected string; got map[string]interface {}
`

Here is the secrets.yaml file that was generated with `azds up`:
```
{{- $root := . }}
{{- range $name, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "horseman-api.fullname" $root }}-{{ $name | lower }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
```
CLI 1.0.20190423.8
API v3.2

**Comment by stepro** [comment]
Hi @matt-landers, this indicates that in your secrets.yaml file, you have specified an object as one of the secret values, something like this:

```
secrets:
  mysecret:
    myvalue:
      foo: bar
```

where the `foo: bar` part represents an object as the value of `myvalue`, rather than something like `myvalue: a string value`.

What are you trying to pass in as the value? Making sure it is parsed as a string by quoting it in the yaml would help.

**Comment by sanar-microsoft** [comment]
@matt-landers Is your secret value in json/yaml format?
In that case changing this line `{{ $key }}: {{ $value | b64enc }}` to the following will probably fix the issue:

- `{{ $key }}: {{ toYaml $value | b64enc }}`
- `{{ $key }}: {{ toJson $value | b64enc }}`

**Comment by matt-landers** [comment]
@sanar-microsoft I was following the docs found here: https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/manage-secrets

I assumed that the env vars would come out in a format with _ for each level. There isn't anything describing how that happens.

**Comment by sanar-microsoft** [comment]
Looks like you are adding another level in `secrets.yaml`. As per the example:

```secrets:
  redis:
    port: "6380"
    host: "contosodevredis.redis.cache.windows.net"
    key: "secretkeyhere"
```
$name will be equal to redis in this statement `name: {{ template "horseman-api.fullname" $root }}-{{ $name | lower }}`

Everything under redis will be treated as key-value pair and will be part of the data under the secret here:
```
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
```

If you have another level under a key, the value will be treated like a map[string] but `secrets.yaml` expects a string.

**Comment by matt-landers** [comment]
@sanar-microsoft Thanks! That makes sense. The docs probably need to be updated.
