### ISSUE TITLE
Devspace won't upload large files during file synchronization

### ISSUE THREAD

**Issue by midebell** [Azure/dev-spaces#99]
I am running devspace for local development, folder contains Dockerfile, azds.yaml, charts and jar file up to 50MB. When I run azds up, I am getting this error _"There is no more space available for file synchronization. Please remove unused spaces by running 'azds down', reduce the size of your workspace, and retry later."_ . If I run it without the jar file, file synchronization succeeds. Any help in fixing this would be highly appreciated.

**Comment by stepro** [comment]
@midebell, what's the reason for having a jar file in your source code? Normally we would expect that the jar file is built as part of the Docker image, using steps in the Dockerfile.

**Comment by midebell** [comment]
The jar file was built prior to running devspace, so I do not want to build it again. All I need is just upload it and pass it during entrypoint.

**Comment by stepro** [comment]
Ok. There is currently a limit of 200Mb of which we allow usage up to about 80% before giving the message you see. Do you have other projects with similarly large files to be synchronized that you have previously deployed using `azds up`?

**Comment by midebell** [comment]
Yes I do. How can I go past this limit ?

**Comment by stepro** [comment]
We don't currently have a way to change this limit. The remote volume we create was designed to hold source code, not binaries, and 200Mb was our first estimate for the space needed to hold source code for a reasonable number of projects.

I'd be interested to understand more about your choice to build the jar file outside of the container and then including it as source code, instead of building the jar file as part of the Docker build process. Changing the approach here would likely solve your problem.

**Comment by midebell** [comment]
As part of CICD pipeline, the jar file is built centrally where other applications/services consume it. Devspace is one of them. To avoid repetition, I just felt uploading it and referencing it in the entrypoint would do the trick.

**Comment by stepro** [comment]
I see. Is your primary use case for dev spaces to run `azds up` as part of your CI/CD pipeline? Or are you also doing that from your client machine as part of your development experience?

File synchronization is configured inside of the `azds.yaml` file. If you search for `sync` you'll find a list of glob patterns that identify which files to synchronize. If you remove this list, no files will be synchronized.
